/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type { DomainTemplateCreateRequest, DomainTemplateEntitiesResponse, DomainTemplateUpdateRequest, MsaReplyMetaOnly, MsaspecQueryResponse, MsaspecResponseFields } from "../models/index";
import {
    DomainTemplateCreateRequestFromJSON,
    DomainTemplateCreateRequestToJSON,
    DomainTemplateEntitiesResponseFromJSON,
    DomainTemplateEntitiesResponseToJSON,
    DomainTemplateUpdateRequestFromJSON,
    DomainTemplateUpdateRequestToJSON,
    MsaReplyMetaOnlyFromJSON,
    MsaReplyMetaOnlyToJSON,
    MsaspecQueryResponseFromJSON,
    MsaspecQueryResponseToJSON,
    MsaspecResponseFieldsFromJSON,
    MsaspecResponseFieldsToJSON,
} from "../models/index";

export interface NetworkScanTemplatesApiCreateTemplatesRequest {
    body: Array<DomainTemplateCreateRequest>;
    xCSUSERUUID?: string;
}

export interface NetworkScanTemplatesApiDeleteTemplatesRequest {
    ids: Array<string>;
    xCSUSERUUID?: string;
}

export interface NetworkScanTemplatesApiGetTemplateConfigsRequest {
    xCSUSERUUID?: string;
}

export interface NetworkScanTemplatesApiGetTemplatesRequest {
    ids: Array<string>;
    xCSUSERUUID?: string;
}

export interface NetworkScanTemplatesApiQueryTemplatesRequest {
    xCSUSERUUID?: string;
    offset?: number;
    limit?: number;
    sort?: string;
    filter?: string;
}

export interface NetworkScanTemplatesApiUpdateTemplatesRequest {
    body: Array<DomainTemplateUpdateRequest>;
    xCSUSERUUID?: string;
}

/**
 *
 */
export class NetworkScanTemplatesApi extends runtime.BaseAPI {
    /**
     * Create \"templates\" using provided specifications
     */
    async createTemplatesRaw(
        requestParameters: NetworkScanTemplatesApiCreateTemplatesRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<DomainTemplateEntitiesResponse>> {
        if (requestParameters["body"] == null) {
            throw new runtime.RequiredError("body", 'Required parameter "body" was null or undefined when calling createTemplates().');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (requestParameters["xCSUSERUUID"] != null) {
            headerParameters["X-CS-USERUUID"] = String(requestParameters["xCSUSERUUID"]);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["network-scan:write"]);
        }

        const response = await this.request(
            {
                path: `/netscan/entities/templates/v1`,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
                body: requestParameters["body"]!.map(DomainTemplateCreateRequestToJSON),
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainTemplateEntitiesResponseFromJSON(jsonValue));
    }

    /**
     * Create \"templates\" using provided specifications
     */
    async createTemplates(body: Array<DomainTemplateCreateRequest>, xCSUSERUUID?: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainTemplateEntitiesResponse> {
        const response = await this.createTemplatesRaw({ body: body, xCSUSERUUID: xCSUSERUUID }, initOverrides);
        return await response.value();
    }

    /**
     * Delete \"templates\" by their IDs
     */
    async deleteTemplatesRaw(
        requestParameters: NetworkScanTemplatesApiDeleteTemplatesRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<MsaspecQueryResponse>> {
        if (requestParameters["ids"] == null) {
            throw new runtime.RequiredError("ids", 'Required parameter "ids" was null or undefined when calling deleteTemplates().');
        }

        const queryParameters: any = {};

        if (requestParameters["ids"] != null) {
            queryParameters["ids"] = requestParameters["ids"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters["xCSUSERUUID"] != null) {
            headerParameters["X-CS-USERUUID"] = String(requestParameters["xCSUSERUUID"]);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["network-scan:write"]);
        }

        const response = await this.request(
            {
                path: `/netscan/entities/templates/v1`,
                method: "DELETE",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => MsaspecQueryResponseFromJSON(jsonValue));
    }

    /**
     * Delete \"templates\" by their IDs
     */
    async deleteTemplates(ids: Array<string>, xCSUSERUUID?: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MsaspecQueryResponse> {
        const response = await this.deleteTemplatesRaw({ ids: ids, xCSUSERUUID: xCSUSERUUID }, initOverrides);
        return await response.value();
    }

    /**
     * Get details on the network scan template configurations
     */
    async getTemplateConfigsRaw(
        requestParameters: NetworkScanTemplatesApiGetTemplateConfigsRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<MsaspecQueryResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters["xCSUSERUUID"] != null) {
            headerParameters["X-CS-USERUUID"] = String(requestParameters["xCSUSERUUID"]);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["network-scan:read"]);
        }

        const response = await this.request(
            {
                path: `/netscan/entities/template-configs/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => MsaspecQueryResponseFromJSON(jsonValue));
    }

    /**
     * Get details on the network scan template configurations
     */
    async getTemplateConfigs(xCSUSERUUID?: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MsaspecQueryResponse> {
        const response = await this.getTemplateConfigsRaw({ xCSUSERUUID: xCSUSERUUID }, initOverrides);
        return await response.value();
    }

    /**
     * Get \"templates\" by their IDs
     */
    async getTemplatesRaw(
        requestParameters: NetworkScanTemplatesApiGetTemplatesRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<DomainTemplateEntitiesResponse>> {
        if (requestParameters["ids"] == null) {
            throw new runtime.RequiredError("ids", 'Required parameter "ids" was null or undefined when calling getTemplates().');
        }

        const queryParameters: any = {};

        if (requestParameters["ids"] != null) {
            queryParameters["ids"] = requestParameters["ids"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters["xCSUSERUUID"] != null) {
            headerParameters["X-CS-USERUUID"] = String(requestParameters["xCSUSERUUID"]);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["network-scan:read"]);
        }

        const response = await this.request(
            {
                path: `/netscan/entities/templates/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainTemplateEntitiesResponseFromJSON(jsonValue));
    }

    /**
     * Get \"templates\" by their IDs
     */
    async getTemplates(ids: Array<string>, xCSUSERUUID?: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainTemplateEntitiesResponse> {
        const response = await this.getTemplatesRaw({ ids: ids, xCSUSERUUID: xCSUSERUUID }, initOverrides);
        return await response.value();
    }

    /**
     * Get \"templates IDs\" by filter
     */
    async queryTemplatesRaw(
        requestParameters: NetworkScanTemplatesApiQueryTemplatesRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<MsaspecQueryResponse>> {
        const queryParameters: any = {};

        if (requestParameters["offset"] != null) {
            queryParameters["offset"] = requestParameters["offset"];
        }

        if (requestParameters["limit"] != null) {
            queryParameters["limit"] = requestParameters["limit"];
        }

        if (requestParameters["sort"] != null) {
            queryParameters["sort"] = requestParameters["sort"];
        }

        if (requestParameters["filter"] != null) {
            queryParameters["filter"] = requestParameters["filter"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters["xCSUSERUUID"] != null) {
            headerParameters["X-CS-USERUUID"] = String(requestParameters["xCSUSERUUID"]);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["network-scan:read"]);
        }

        const response = await this.request(
            {
                path: `/netscan/queries/templates/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => MsaspecQueryResponseFromJSON(jsonValue));
    }

    /**
     * Get \"templates IDs\" by filter
     */
    async queryTemplates(
        xCSUSERUUID?: string,
        offset?: number,
        limit?: number,
        sort?: string,
        filter?: string,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<MsaspecQueryResponse> {
        const response = await this.queryTemplatesRaw({ xCSUSERUUID: xCSUSERUUID, offset: offset, limit: limit, sort: sort, filter: filter }, initOverrides);
        return await response.value();
    }

    /**
     * Update \"templates\" using provided specifications
     */
    async updateTemplatesRaw(
        requestParameters: NetworkScanTemplatesApiUpdateTemplatesRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<DomainTemplateEntitiesResponse>> {
        if (requestParameters["body"] == null) {
            throw new runtime.RequiredError("body", 'Required parameter "body" was null or undefined when calling updateTemplates().');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (requestParameters["xCSUSERUUID"] != null) {
            headerParameters["X-CS-USERUUID"] = String(requestParameters["xCSUSERUUID"]);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["network-scan:write"]);
        }

        const response = await this.request(
            {
                path: `/netscan/entities/templates/v1`,
                method: "PATCH",
                headers: headerParameters,
                query: queryParameters,
                body: requestParameters["body"]!.map(DomainTemplateUpdateRequestToJSON),
            },
            initOverrides,
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainTemplateEntitiesResponseFromJSON(jsonValue));
    }

    /**
     * Update \"templates\" using provided specifications
     */
    async updateTemplates(body: Array<DomainTemplateUpdateRequest>, xCSUSERUUID?: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainTemplateEntitiesResponse> {
        const response = await this.updateTemplatesRaw({ body: body, xCSUSERUUID: xCSUSERUUID }, initOverrides);
        return await response.value();
    }
}
