/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and more information about API endpoints that don\'t yet support OAuth2, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation). To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`. Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import {
    MsaEntityActionRequestV2,
    MsaEntityActionRequestV2FromJSON,
    MsaEntityActionRequestV2ToJSON,
    MsaErrorsOnly,
    MsaErrorsOnlyFromJSON,
    MsaErrorsOnlyToJSON,
    MsaQueryResponse,
    MsaQueryResponseFromJSON,
    MsaQueryResponseToJSON,
    MsaReplyMetaOnly,
    MsaReplyMetaOnlyFromJSON,
    MsaReplyMetaOnlyToJSON,
    RequestsCreatePreventionPoliciesV1,
    RequestsCreatePreventionPoliciesV1FromJSON,
    RequestsCreatePreventionPoliciesV1ToJSON,
    RequestsSetPolicyPrecedenceReqV1,
    RequestsSetPolicyPrecedenceReqV1FromJSON,
    RequestsSetPolicyPrecedenceReqV1ToJSON,
    RequestsUpdatePreventionPoliciesV1,
    RequestsUpdatePreventionPoliciesV1FromJSON,
    RequestsUpdatePreventionPoliciesV1ToJSON,
    ResponsesPolicyMembersRespV1,
    ResponsesPolicyMembersRespV1FromJSON,
    ResponsesPolicyMembersRespV1ToJSON,
    ResponsesPreventionPoliciesV1,
    ResponsesPreventionPoliciesV1FromJSON,
    ResponsesPreventionPoliciesV1ToJSON,
} from "../models";

export interface CreatePreventionPoliciesRequest {
    body: RequestsCreatePreventionPoliciesV1;
}

export interface DeletePreventionPoliciesRequest {
    ids: Array<string>;
}

export interface GetPreventionPoliciesRequest {
    ids: Array<string>;
}

export interface PerformPreventionPoliciesActionRequest {
    actionName: PerformPreventionPoliciesActionActionNameEnum;
    body: MsaEntityActionRequestV2;
}

export interface QueryCombinedPreventionPoliciesRequest {
    filter?: string;
    offset?: number;
    limit?: number;
    sort?: QueryCombinedPreventionPoliciesSortEnum;
}

export interface QueryCombinedPreventionPolicyMembersRequest {
    id?: string;
    filter?: string;
    offset?: number;
    limit?: number;
    sort?: string;
}

export interface QueryPreventionPoliciesRequest {
    filter?: string;
    offset?: number;
    limit?: number;
    sort?: QueryPreventionPoliciesSortEnum;
}

export interface QueryPreventionPolicyMembersRequest {
    id?: string;
    filter?: string;
    offset?: number;
    limit?: number;
    sort?: string;
}

export interface SetPreventionPoliciesPrecedenceRequest {
    body: RequestsSetPolicyPrecedenceReqV1;
}

export interface UpdatePreventionPoliciesRequest {
    body: RequestsUpdatePreventionPoliciesV1;
}

/**
 *
 */
export class PreventionPoliciesApi extends runtime.BaseAPI {
    /**
     * Create Prevention Policies by specifying details about the policy to create
     */
    async createPreventionPoliciesRaw(requestParameters: CreatePreventionPoliciesRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ResponsesPreventionPoliciesV1>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError("body", "Required parameter requestParameters.body was null or undefined when calling createPreventionPolicies.");
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["prevention-policies:write"]);
        }

        const response = await this.request(
            {
                path: `/policy/entities/prevention/v1`,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
                body: RequestsCreatePreventionPoliciesV1ToJSON(requestParameters.body),
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponsesPreventionPoliciesV1FromJSON(jsonValue));
    }

    /**
     * Create Prevention Policies by specifying details about the policy to create
     */
    async createPreventionPolicies(body: RequestsCreatePreventionPoliciesV1, initOverrides?: RequestInit): Promise<ResponsesPreventionPoliciesV1> {
        const response = await this.createPreventionPoliciesRaw({ body: body }, initOverrides);
        return await response.value();
    }

    /**
     * Delete a set of Prevention Policies by specifying their IDs
     */
    async deletePreventionPoliciesRaw(requestParameters: DeletePreventionPoliciesRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<MsaQueryResponse>> {
        if (requestParameters.ids === null || requestParameters.ids === undefined) {
            throw new runtime.RequiredError("ids", "Required parameter requestParameters.ids was null or undefined when calling deletePreventionPolicies.");
        }

        const queryParameters: any = {};

        if (requestParameters.ids) {
            queryParameters["ids"] = requestParameters.ids;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["prevention-policies:write"]);
        }

        const response = await this.request(
            {
                path: `/policy/entities/prevention/v1`,
                method: "DELETE",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => MsaQueryResponseFromJSON(jsonValue));
    }

    /**
     * Delete a set of Prevention Policies by specifying their IDs
     */
    async deletePreventionPolicies(ids: Array<string>, initOverrides?: RequestInit): Promise<MsaQueryResponse> {
        const response = await this.deletePreventionPoliciesRaw({ ids: ids }, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve a set of Prevention Policies by specifying their IDs
     */
    async getPreventionPoliciesRaw(requestParameters: GetPreventionPoliciesRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ResponsesPreventionPoliciesV1>> {
        if (requestParameters.ids === null || requestParameters.ids === undefined) {
            throw new runtime.RequiredError("ids", "Required parameter requestParameters.ids was null or undefined when calling getPreventionPolicies.");
        }

        const queryParameters: any = {};

        if (requestParameters.ids) {
            queryParameters["ids"] = requestParameters.ids;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["prevention-policies:read"]);
        }

        const response = await this.request(
            {
                path: `/policy/entities/prevention/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponsesPreventionPoliciesV1FromJSON(jsonValue));
    }

    /**
     * Retrieve a set of Prevention Policies by specifying their IDs
     */
    async getPreventionPolicies(ids: Array<string>, initOverrides?: RequestInit): Promise<ResponsesPreventionPoliciesV1> {
        const response = await this.getPreventionPoliciesRaw({ ids: ids }, initOverrides);
        return await response.value();
    }

    /**
     * Perform the specified action on the Prevention Policies specified in the request
     */
    async performPreventionPoliciesActionRaw(requestParameters: PerformPreventionPoliciesActionRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ResponsesPreventionPoliciesV1>> {
        if (requestParameters.actionName === null || requestParameters.actionName === undefined) {
            throw new runtime.RequiredError("actionName", "Required parameter requestParameters.actionName was null or undefined when calling performPreventionPoliciesAction.");
        }

        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError("body", "Required parameter requestParameters.body was null or undefined when calling performPreventionPoliciesAction.");
        }

        const queryParameters: any = {};

        if (requestParameters.actionName !== undefined) {
            queryParameters["action_name"] = requestParameters.actionName;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["prevention-policies:write"]);
        }

        const response = await this.request(
            {
                path: `/policy/entities/prevention-actions/v1`,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
                body: MsaEntityActionRequestV2ToJSON(requestParameters.body),
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponsesPreventionPoliciesV1FromJSON(jsonValue));
    }

    /**
     * Perform the specified action on the Prevention Policies specified in the request
     */
    async performPreventionPoliciesAction(
        actionName: PerformPreventionPoliciesActionActionNameEnum,
        body: MsaEntityActionRequestV2,
        initOverrides?: RequestInit
    ): Promise<ResponsesPreventionPoliciesV1> {
        const response = await this.performPreventionPoliciesActionRaw({ actionName: actionName, body: body }, initOverrides);
        return await response.value();
    }

    /**
     * Search for Prevention Policies in your environment by providing an FQL filter and paging details. Returns a set of Prevention Policies which match the filter criteria
     */
    async queryCombinedPreventionPoliciesRaw(requestParameters: QueryCombinedPreventionPoliciesRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ResponsesPreventionPoliciesV1>> {
        const queryParameters: any = {};

        if (requestParameters.filter !== undefined) {
            queryParameters["filter"] = requestParameters.filter;
        }

        if (requestParameters.offset !== undefined) {
            queryParameters["offset"] = requestParameters.offset;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters["limit"] = requestParameters.limit;
        }

        if (requestParameters.sort !== undefined) {
            queryParameters["sort"] = requestParameters.sort;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["prevention-policies:read"]);
        }

        const response = await this.request(
            {
                path: `/policy/combined/prevention/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponsesPreventionPoliciesV1FromJSON(jsonValue));
    }

    /**
     * Search for Prevention Policies in your environment by providing an FQL filter and paging details. Returns a set of Prevention Policies which match the filter criteria
     */
    async queryCombinedPreventionPolicies(
        filter?: string,
        offset?: number,
        limit?: number,
        sort?: QueryCombinedPreventionPoliciesSortEnum,
        initOverrides?: RequestInit
    ): Promise<ResponsesPreventionPoliciesV1> {
        const response = await this.queryCombinedPreventionPoliciesRaw({ filter: filter, offset: offset, limit: limit, sort: sort }, initOverrides);
        return await response.value();
    }

    /**
     * Search for members of a Prevention Policy in your environment by providing an FQL filter and paging details. Returns a set of host details which match the filter criteria
     */
    async queryCombinedPreventionPolicyMembersRaw(
        requestParameters: QueryCombinedPreventionPolicyMembersRequest,
        initOverrides?: RequestInit
    ): Promise<runtime.ApiResponse<ResponsesPolicyMembersRespV1>> {
        const queryParameters: any = {};

        if (requestParameters.id !== undefined) {
            queryParameters["id"] = requestParameters.id;
        }

        if (requestParameters.filter !== undefined) {
            queryParameters["filter"] = requestParameters.filter;
        }

        if (requestParameters.offset !== undefined) {
            queryParameters["offset"] = requestParameters.offset;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters["limit"] = requestParameters.limit;
        }

        if (requestParameters.sort !== undefined) {
            queryParameters["sort"] = requestParameters.sort;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["prevention-policies:read"]);
        }

        const response = await this.request(
            {
                path: `/policy/combined/prevention-members/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponsesPolicyMembersRespV1FromJSON(jsonValue));
    }

    /**
     * Search for members of a Prevention Policy in your environment by providing an FQL filter and paging details. Returns a set of host details which match the filter criteria
     */
    async queryCombinedPreventionPolicyMembers(id?: string, filter?: string, offset?: number, limit?: number, sort?: string, initOverrides?: RequestInit): Promise<ResponsesPolicyMembersRespV1> {
        const response = await this.queryCombinedPreventionPolicyMembersRaw({ id: id, filter: filter, offset: offset, limit: limit, sort: sort }, initOverrides);
        return await response.value();
    }

    /**
     * Search for Prevention Policies in your environment by providing an FQL filter and paging details. Returns a set of Prevention Policy IDs which match the filter criteria
     */
    async queryPreventionPoliciesRaw(requestParameters: QueryPreventionPoliciesRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<MsaQueryResponse>> {
        const queryParameters: any = {};

        if (requestParameters.filter !== undefined) {
            queryParameters["filter"] = requestParameters.filter;
        }

        if (requestParameters.offset !== undefined) {
            queryParameters["offset"] = requestParameters.offset;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters["limit"] = requestParameters.limit;
        }

        if (requestParameters.sort !== undefined) {
            queryParameters["sort"] = requestParameters.sort;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["prevention-policies:read"]);
        }

        const response = await this.request(
            {
                path: `/policy/queries/prevention/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => MsaQueryResponseFromJSON(jsonValue));
    }

    /**
     * Search for Prevention Policies in your environment by providing an FQL filter and paging details. Returns a set of Prevention Policy IDs which match the filter criteria
     */
    async queryPreventionPolicies(filter?: string, offset?: number, limit?: number, sort?: QueryPreventionPoliciesSortEnum, initOverrides?: RequestInit): Promise<MsaQueryResponse> {
        const response = await this.queryPreventionPoliciesRaw({ filter: filter, offset: offset, limit: limit, sort: sort }, initOverrides);
        return await response.value();
    }

    /**
     * Search for members of a Prevention Policy in your environment by providing an FQL filter and paging details. Returns a set of Agent IDs which match the filter criteria
     */
    async queryPreventionPolicyMembersRaw(requestParameters: QueryPreventionPolicyMembersRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<MsaQueryResponse>> {
        const queryParameters: any = {};

        if (requestParameters.id !== undefined) {
            queryParameters["id"] = requestParameters.id;
        }

        if (requestParameters.filter !== undefined) {
            queryParameters["filter"] = requestParameters.filter;
        }

        if (requestParameters.offset !== undefined) {
            queryParameters["offset"] = requestParameters.offset;
        }

        if (requestParameters.limit !== undefined) {
            queryParameters["limit"] = requestParameters.limit;
        }

        if (requestParameters.sort !== undefined) {
            queryParameters["sort"] = requestParameters.sort;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["prevention-policies:read"]);
        }

        const response = await this.request(
            {
                path: `/policy/queries/prevention-members/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => MsaQueryResponseFromJSON(jsonValue));
    }

    /**
     * Search for members of a Prevention Policy in your environment by providing an FQL filter and paging details. Returns a set of Agent IDs which match the filter criteria
     */
    async queryPreventionPolicyMembers(id?: string, filter?: string, offset?: number, limit?: number, sort?: string, initOverrides?: RequestInit): Promise<MsaQueryResponse> {
        const response = await this.queryPreventionPolicyMembersRaw({ id: id, filter: filter, offset: offset, limit: limit, sort: sort }, initOverrides);
        return await response.value();
    }

    /**
     * Sets the precedence of Prevention Policies based on the order of IDs specified in the request. The first ID specified will have the highest precedence and the last ID specified will have the lowest. You must specify all non-Default Policies for a platform when updating precedence
     */
    async setPreventionPoliciesPrecedenceRaw(requestParameters: SetPreventionPoliciesPrecedenceRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<MsaQueryResponse>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError("body", "Required parameter requestParameters.body was null or undefined when calling setPreventionPoliciesPrecedence.");
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["prevention-policies:write"]);
        }

        const response = await this.request(
            {
                path: `/policy/entities/prevention-precedence/v1`,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
                body: RequestsSetPolicyPrecedenceReqV1ToJSON(requestParameters.body),
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => MsaQueryResponseFromJSON(jsonValue));
    }

    /**
     * Sets the precedence of Prevention Policies based on the order of IDs specified in the request. The first ID specified will have the highest precedence and the last ID specified will have the lowest. You must specify all non-Default Policies for a platform when updating precedence
     */
    async setPreventionPoliciesPrecedence(body: RequestsSetPolicyPrecedenceReqV1, initOverrides?: RequestInit): Promise<MsaQueryResponse> {
        const response = await this.setPreventionPoliciesPrecedenceRaw({ body: body }, initOverrides);
        return await response.value();
    }

    /**
     * Update Prevention Policies by specifying the ID of the policy and details to update
     */
    async updatePreventionPoliciesRaw(requestParameters: UpdatePreventionPoliciesRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<ResponsesPreventionPoliciesV1>> {
        if (requestParameters.body === null || requestParameters.body === undefined) {
            throw new runtime.RequiredError("body", "Required parameter requestParameters.body was null or undefined when calling updatePreventionPolicies.");
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["prevention-policies:write"]);
        }

        const response = await this.request(
            {
                path: `/policy/entities/prevention/v1`,
                method: "PATCH",
                headers: headerParameters,
                query: queryParameters,
                body: RequestsUpdatePreventionPoliciesV1ToJSON(requestParameters.body),
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponsesPreventionPoliciesV1FromJSON(jsonValue));
    }

    /**
     * Update Prevention Policies by specifying the ID of the policy and details to update
     */
    async updatePreventionPolicies(body: RequestsUpdatePreventionPoliciesV1, initOverrides?: RequestInit): Promise<ResponsesPreventionPoliciesV1> {
        const response = await this.updatePreventionPoliciesRaw({ body: body }, initOverrides);
        return await response.value();
    }
}

/**
 * @export
 * @enum {string}
 */
export enum PerformPreventionPoliciesActionActionNameEnum {
    AddHostGroup = "add-host-group",
    AddRuleGroup = "add-rule-group",
    Disable = "disable",
    Enable = "enable",
    RemoveHostGroup = "remove-host-group",
    RemoveRuleGroup = "remove-rule-group",
}
/**
 * @export
 * @enum {string}
 */
export enum QueryCombinedPreventionPoliciesSortEnum {
    CreatedByAsc = "created_by.asc",
    CreatedByDesc = "created_by.desc",
    CreatedTimestampAsc = "created_timestamp.asc",
    CreatedTimestampDesc = "created_timestamp.desc",
    EnabledAsc = "enabled.asc",
    EnabledDesc = "enabled.desc",
    ModifiedByAsc = "modified_by.asc",
    ModifiedByDesc = "modified_by.desc",
    ModifiedTimestampAsc = "modified_timestamp.asc",
    ModifiedTimestampDesc = "modified_timestamp.desc",
    NameAsc = "name.asc",
    NameDesc = "name.desc",
    PlatformNameAsc = "platform_name.asc",
    PlatformNameDesc = "platform_name.desc",
    PrecedenceAsc = "precedence.asc",
    PrecedenceDesc = "precedence.desc",
}
/**
 * @export
 * @enum {string}
 */
export enum QueryPreventionPoliciesSortEnum {
    CreatedByAsc = "created_by.asc",
    CreatedByDesc = "created_by.desc",
    CreatedTimestampAsc = "created_timestamp.asc",
    CreatedTimestampDesc = "created_timestamp.desc",
    EnabledAsc = "enabled.asc",
    EnabledDesc = "enabled.desc",
    ModifiedByAsc = "modified_by.asc",
    ModifiedByDesc = "modified_by.desc",
    ModifiedTimestampAsc = "modified_timestamp.asc",
    ModifiedTimestampDesc = "modified_timestamp.desc",
    NameAsc = "name.asc",
    NameDesc = "name.desc",
    PlatformNameAsc = "platform_name.asc",
    PlatformNameDesc = "platform_name.desc",
    PrecedenceAsc = "precedence.asc",
    PrecedenceDesc = "precedence.desc",
}
