/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
    ApiNotificationExposedDataRecordEntitiesResponseV1,
    DomainActionEntitiesResponseV1,
    DomainAggregatesResponse,
    DomainErrorsOnly,
    DomainExportJobEntitiesResponseV1,
    DomainExportJobIDResponseV1,
    DomainLaunchExportJobRequestV1,
    DomainLaunchExportJobResponseV1,
    DomainNotificationDetailsResponseV1,
    DomainNotificationEntitiesResponseV1,
    DomainNotificationIDResponse,
    DomainQueryResponse,
    DomainRegisterActionsRequest,
    DomainRulePreviewRequest,
    DomainRuleQueryResponseV1,
    DomainRulesEntitiesResponseV1,
    DomainUpdateActionRequest,
    DomainUpdateNotificationRequestV1,
    DomainUpdateRuleRequestV1,
    MsaAggregateQueryRequest,
    MsaReplyMetaOnly,
    MsaspecResponseFields,
    SadomainCreateRuleRequestV1,
} from "../models/index";
import {
    ApiNotificationExposedDataRecordEntitiesResponseV1FromJSON,
    ApiNotificationExposedDataRecordEntitiesResponseV1ToJSON,
    DomainActionEntitiesResponseV1FromJSON,
    DomainActionEntitiesResponseV1ToJSON,
    DomainAggregatesResponseFromJSON,
    DomainAggregatesResponseToJSON,
    DomainErrorsOnlyFromJSON,
    DomainErrorsOnlyToJSON,
    DomainExportJobEntitiesResponseV1FromJSON,
    DomainExportJobEntitiesResponseV1ToJSON,
    DomainExportJobIDResponseV1FromJSON,
    DomainExportJobIDResponseV1ToJSON,
    DomainLaunchExportJobRequestV1FromJSON,
    DomainLaunchExportJobRequestV1ToJSON,
    DomainLaunchExportJobResponseV1FromJSON,
    DomainLaunchExportJobResponseV1ToJSON,
    DomainNotificationDetailsResponseV1FromJSON,
    DomainNotificationDetailsResponseV1ToJSON,
    DomainNotificationEntitiesResponseV1FromJSON,
    DomainNotificationEntitiesResponseV1ToJSON,
    DomainNotificationIDResponseFromJSON,
    DomainNotificationIDResponseToJSON,
    DomainQueryResponseFromJSON,
    DomainQueryResponseToJSON,
    DomainRegisterActionsRequestFromJSON,
    DomainRegisterActionsRequestToJSON,
    DomainRulePreviewRequestFromJSON,
    DomainRulePreviewRequestToJSON,
    DomainRuleQueryResponseV1FromJSON,
    DomainRuleQueryResponseV1ToJSON,
    DomainRulesEntitiesResponseV1FromJSON,
    DomainRulesEntitiesResponseV1ToJSON,
    DomainUpdateActionRequestFromJSON,
    DomainUpdateActionRequestToJSON,
    DomainUpdateNotificationRequestV1FromJSON,
    DomainUpdateNotificationRequestV1ToJSON,
    DomainUpdateRuleRequestV1FromJSON,
    DomainUpdateRuleRequestV1ToJSON,
    MsaAggregateQueryRequestFromJSON,
    MsaAggregateQueryRequestToJSON,
    MsaReplyMetaOnlyFromJSON,
    MsaReplyMetaOnlyToJSON,
    MsaspecResponseFieldsFromJSON,
    MsaspecResponseFieldsToJSON,
    SadomainCreateRuleRequestV1FromJSON,
    SadomainCreateRuleRequestV1ToJSON,
} from "../models/index";

export interface ReconApiAggregateNotificationsExposedDataRecordsV1Request {
    body: Array<MsaAggregateQueryRequest>;
}

export interface ReconApiAggregateNotificationsV1Request {
    body: Array<MsaAggregateQueryRequest>;
}

export interface ReconApiCreateActionsV1Request {
    body: DomainRegisterActionsRequest;
}

export interface ReconApiCreateExportJobsV1Request {
    body: Array<DomainLaunchExportJobRequestV1>;
}

export interface ReconApiCreateRulesV1Request {
    body: Array<SadomainCreateRuleRequestV1>;
}

export interface ReconApiDeleteActionV1Request {
    id: string;
}

export interface ReconApiDeleteExportJobsV1Request {
    ids: Array<string>;
}

export interface ReconApiDeleteNotificationsV1Request {
    ids: Array<string>;
}

export interface ReconApiDeleteRulesV1Request {
    ids: Array<string>;
    notificationsDeletionRequested?: boolean;
}

export interface ReconApiGetActionsV1Request {
    ids: Array<string>;
}

export interface ReconApiGetExportJobsV1Request {
    ids: Array<string>;
}

export interface ReconApiGetFileContentForExportJobsV1Request {
    id: string;
}

export interface ReconApiGetNotificationsDetailedTranslatedV1Request {
    ids: Array<string>;
}

export interface ReconApiGetNotificationsDetailedV1Request {
    ids: Array<string>;
}

export interface ReconApiGetNotificationsExposedDataRecordsV1Request {
    ids: Array<string>;
}

export interface ReconApiGetNotificationsTranslatedV1Request {
    ids: Array<string>;
}

export interface ReconApiGetNotificationsV1Request {
    ids: Array<string>;
}

export interface ReconApiGetRulesV1Request {
    ids: Array<string>;
}

export interface ReconApiPreviewRuleV1Request {
    body: DomainRulePreviewRequest;
}

export interface ReconApiQueryActionsV1Request {
    offset?: number;
    limit?: number;
    sort?: string;
    filter?: string;
    q?: string;
}

export interface ReconApiQueryNotificationsExposedDataRecordsV1Request {
    offset?: number;
    limit?: number;
    sort?: string;
    filter?: string;
    q?: string;
}

export interface ReconApiQueryNotificationsV1Request {
    offset?: number;
    limit?: number;
    sort?: string;
    filter?: string;
    q?: string;
}

export interface ReconApiQueryRulesV1Request {
    offset?: number;
    limit?: number;
    sort?: string;
    filter?: string;
    q?: string;
    secondarySort?: string;
}

export interface ReconApiUpdateActionV1Request {
    body: DomainUpdateActionRequest;
}

export interface ReconApiUpdateNotificationsV1Request {
    body: Array<DomainUpdateNotificationRequestV1>;
}

export interface ReconApiUpdateRulesV1Request {
    body: Array<DomainUpdateRuleRequestV1>;
}

/**
 *
 */
export class ReconApi extends runtime.BaseAPI {
    /**
     * Get notification exposed data record aggregates as specified via JSON in request body. The valid aggregation fields are: [cid notification_id created_date rule.id rule.name rule.topic source_category site author file.name credential_status bot.operating_system.hardware_id bot.bot_id]
     */
    async aggregateNotificationsExposedDataRecordsV1Raw(
        requestParameters: ReconApiAggregateNotificationsExposedDataRecordsV1Request,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<DomainAggregatesResponse>> {
        if (requestParameters["body"] == null) {
            throw new runtime.RequiredError("body", 'Required parameter "body" was null or undefined when calling aggregateNotificationsExposedDataRecordsV1().');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["recon-monitoring-rules:read"]);
        }

        const response = await this.request(
            {
                path: `/recon/aggregates/notifications-exposed-data-records/GET/v1`,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
                body: requestParameters["body"]!.map(MsaAggregateQueryRequestToJSON),
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainAggregatesResponseFromJSON(jsonValue));
    }

    /**
     * Get notification exposed data record aggregates as specified via JSON in request body. The valid aggregation fields are: [cid notification_id created_date rule.id rule.name rule.topic source_category site author file.name credential_status bot.operating_system.hardware_id bot.bot_id]
     */
    async aggregateNotificationsExposedDataRecordsV1(body: Array<MsaAggregateQueryRequest>, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainAggregatesResponse> {
        const response = await this.aggregateNotificationsExposedDataRecordsV1Raw({ body: body }, initOverrides);
        return await response.value();
    }

    /**
     * Get notification aggregates as specified via JSON in request body.
     */
    async aggregateNotificationsV1Raw(
        requestParameters: ReconApiAggregateNotificationsV1Request,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<DomainAggregatesResponse>> {
        if (requestParameters["body"] == null) {
            throw new runtime.RequiredError("body", 'Required parameter "body" was null or undefined when calling aggregateNotificationsV1().');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["recon-monitoring-rules:read"]);
        }

        const response = await this.request(
            {
                path: `/recon/aggregates/notifications/GET/v1`,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
                body: requestParameters["body"]!.map(MsaAggregateQueryRequestToJSON),
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainAggregatesResponseFromJSON(jsonValue));
    }

    /**
     * Get notification aggregates as specified via JSON in request body.
     */
    async aggregateNotificationsV1(body: Array<MsaAggregateQueryRequest>, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainAggregatesResponse> {
        const response = await this.aggregateNotificationsV1Raw({ body: body }, initOverrides);
        return await response.value();
    }

    /**
     * Create actions for a monitoring rule. Accepts a list of actions that will be attached to the monitoring rule.
     */
    async createActionsV1Raw(
        requestParameters: ReconApiCreateActionsV1Request,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<DomainActionEntitiesResponseV1>> {
        if (requestParameters["body"] == null) {
            throw new runtime.RequiredError("body", 'Required parameter "body" was null or undefined when calling createActionsV1().');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["recon-monitoring-rules:write"]);
        }

        const response = await this.request(
            {
                path: `/recon/entities/actions/v1`,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
                body: DomainRegisterActionsRequestToJSON(requestParameters["body"]),
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainActionEntitiesResponseV1FromJSON(jsonValue));
    }

    /**
     * Create actions for a monitoring rule. Accepts a list of actions that will be attached to the monitoring rule.
     */
    async createActionsV1(body: DomainRegisterActionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainActionEntitiesResponseV1> {
        const response = await this.createActionsV1Raw({ body: body }, initOverrides);
        return await response.value();
    }

    /**
     * Launch asynchronous export job. Use the job ID to poll the status of the job using GET /entities/exports/v1.
     */
    async createExportJobsV1Raw(
        requestParameters: ReconApiCreateExportJobsV1Request,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<DomainLaunchExportJobResponseV1>> {
        if (requestParameters["body"] == null) {
            throw new runtime.RequiredError("body", 'Required parameter "body" was null or undefined when calling createExportJobsV1().');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["recon-monitoring-rules:write"]);
        }

        const response = await this.request(
            {
                path: `/recon/entities/exports/v1`,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
                body: requestParameters["body"]!.map(DomainLaunchExportJobRequestV1ToJSON),
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainLaunchExportJobResponseV1FromJSON(jsonValue));
    }

    /**
     * Launch asynchronous export job. Use the job ID to poll the status of the job using GET /entities/exports/v1.
     */
    async createExportJobsV1(body: Array<DomainLaunchExportJobRequestV1>, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainLaunchExportJobResponseV1> {
        const response = await this.createExportJobsV1Raw({ body: body }, initOverrides);
        return await response.value();
    }

    /**
     * Create monitoring rules.
     */
    async createRulesV1Raw(requestParameters: ReconApiCreateRulesV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DomainRulesEntitiesResponseV1>> {
        if (requestParameters["body"] == null) {
            throw new runtime.RequiredError("body", 'Required parameter "body" was null or undefined when calling createRulesV1().');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["recon-monitoring-rules:write"]);
        }

        const response = await this.request(
            {
                path: `/recon/entities/rules/v1`,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
                body: requestParameters["body"]!.map(SadomainCreateRuleRequestV1ToJSON),
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainRulesEntitiesResponseV1FromJSON(jsonValue));
    }

    /**
     * Create monitoring rules.
     */
    async createRulesV1(body: Array<SadomainCreateRuleRequestV1>, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainRulesEntitiesResponseV1> {
        const response = await this.createRulesV1Raw({ body: body }, initOverrides);
        return await response.value();
    }

    /**
     * Delete an action from a monitoring rule based on the action ID.
     */
    async deleteActionV1Raw(requestParameters: ReconApiDeleteActionV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DomainQueryResponse>> {
        if (requestParameters["id"] == null) {
            throw new runtime.RequiredError("id", 'Required parameter "id" was null or undefined when calling deleteActionV1().');
        }

        const queryParameters: any = {};

        if (requestParameters["id"] != null) {
            queryParameters["id"] = requestParameters["id"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["recon-monitoring-rules:write"]);
        }

        const response = await this.request(
            {
                path: `/recon/entities/actions/v1`,
                method: "DELETE",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainQueryResponseFromJSON(jsonValue));
    }

    /**
     * Delete an action from a monitoring rule based on the action ID.
     */
    async deleteActionV1(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainQueryResponse> {
        const response = await this.deleteActionV1Raw({ id: id }, initOverrides);
        return await response.value();
    }

    /**
     * Delete export jobs (and their associated file(s)) based on their IDs.
     */
    async deleteExportJobsV1Raw(
        requestParameters: ReconApiDeleteExportJobsV1Request,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<DomainExportJobIDResponseV1>> {
        if (requestParameters["ids"] == null) {
            throw new runtime.RequiredError("ids", 'Required parameter "ids" was null or undefined when calling deleteExportJobsV1().');
        }

        const queryParameters: any = {};

        if (requestParameters["ids"] != null) {
            queryParameters["ids"] = requestParameters["ids"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["recon-monitoring-rules:write"]);
        }

        const response = await this.request(
            {
                path: `/recon/entities/exports/v1`,
                method: "DELETE",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainExportJobIDResponseV1FromJSON(jsonValue));
    }

    /**
     * Delete export jobs (and their associated file(s)) based on their IDs.
     */
    async deleteExportJobsV1(ids: Array<string>, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainExportJobIDResponseV1> {
        const response = await this.deleteExportJobsV1Raw({ ids: ids }, initOverrides);
        return await response.value();
    }

    /**
     * Delete notifications based on IDs. Notifications cannot be recovered after they are deleted.
     */
    async deleteNotificationsV1Raw(
        requestParameters: ReconApiDeleteNotificationsV1Request,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<DomainNotificationIDResponse>> {
        if (requestParameters["ids"] == null) {
            throw new runtime.RequiredError("ids", 'Required parameter "ids" was null or undefined when calling deleteNotificationsV1().');
        }

        const queryParameters: any = {};

        if (requestParameters["ids"] != null) {
            queryParameters["ids"] = requestParameters["ids"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["recon-monitoring-rules:write"]);
        }

        const response = await this.request(
            {
                path: `/recon/entities/notifications/v1`,
                method: "DELETE",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainNotificationIDResponseFromJSON(jsonValue));
    }

    /**
     * Delete notifications based on IDs. Notifications cannot be recovered after they are deleted.
     */
    async deleteNotificationsV1(ids: Array<string>, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainNotificationIDResponse> {
        const response = await this.deleteNotificationsV1Raw({ ids: ids }, initOverrides);
        return await response.value();
    }

    /**
     * Delete monitoring rules.
     */
    async deleteRulesV1Raw(requestParameters: ReconApiDeleteRulesV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DomainRuleQueryResponseV1>> {
        if (requestParameters["ids"] == null) {
            throw new runtime.RequiredError("ids", 'Required parameter "ids" was null or undefined when calling deleteRulesV1().');
        }

        const queryParameters: any = {};

        if (requestParameters["ids"] != null) {
            queryParameters["ids"] = requestParameters["ids"];
        }

        if (requestParameters["notificationsDeletionRequested"] != null) {
            queryParameters["notificationsDeletionRequested"] = requestParameters["notificationsDeletionRequested"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["recon-monitoring-rules:write"]);
        }

        const response = await this.request(
            {
                path: `/recon/entities/rules/v1`,
                method: "DELETE",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainRuleQueryResponseV1FromJSON(jsonValue));
    }

    /**
     * Delete monitoring rules.
     */
    async deleteRulesV1(ids: Array<string>, notificationsDeletionRequested?: boolean, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainRuleQueryResponseV1> {
        const response = await this.deleteRulesV1Raw({ ids: ids, notificationsDeletionRequested: notificationsDeletionRequested }, initOverrides);
        return await response.value();
    }

    /**
     * Get actions based on their IDs. IDs can be retrieved using the GET /queries/actions/v1 endpoint.
     */
    async getActionsV1Raw(requestParameters: ReconApiGetActionsV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DomainActionEntitiesResponseV1>> {
        if (requestParameters["ids"] == null) {
            throw new runtime.RequiredError("ids", 'Required parameter "ids" was null or undefined when calling getActionsV1().');
        }

        const queryParameters: any = {};

        if (requestParameters["ids"] != null) {
            queryParameters["ids"] = requestParameters["ids"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["recon-monitoring-rules:read"]);
        }

        const response = await this.request(
            {
                path: `/recon/entities/actions/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainActionEntitiesResponseV1FromJSON(jsonValue));
    }

    /**
     * Get actions based on their IDs. IDs can be retrieved using the GET /queries/actions/v1 endpoint.
     */
    async getActionsV1(ids: Array<string>, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainActionEntitiesResponseV1> {
        const response = await this.getActionsV1Raw({ ids: ids }, initOverrides);
        return await response.value();
    }

    /**
     * Get the status of export jobs based on their IDs. Export jobs can be launched by calling POST /entities/exports/v1. When a job is complete, use the job ID to download the file(s) associated with it using GET entities/export-files/v1.
     */
    async getExportJobsV1Raw(
        requestParameters: ReconApiGetExportJobsV1Request,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<DomainExportJobEntitiesResponseV1>> {
        if (requestParameters["ids"] == null) {
            throw new runtime.RequiredError("ids", 'Required parameter "ids" was null or undefined when calling getExportJobsV1().');
        }

        const queryParameters: any = {};

        if (requestParameters["ids"] != null) {
            queryParameters["ids"] = requestParameters["ids"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["recon-monitoring-rules:read"]);
        }

        const response = await this.request(
            {
                path: `/recon/entities/exports/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainExportJobEntitiesResponseV1FromJSON(jsonValue));
    }

    /**
     * Get the status of export jobs based on their IDs. Export jobs can be launched by calling POST /entities/exports/v1. When a job is complete, use the job ID to download the file(s) associated with it using GET entities/export-files/v1.
     */
    async getExportJobsV1(ids: Array<string>, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainExportJobEntitiesResponseV1> {
        const response = await this.getExportJobsV1Raw({ ids: ids }, initOverrides);
        return await response.value();
    }

    /**
     * Download the file associated with a job ID.
     */
    async getFileContentForExportJobsV1Raw(
        requestParameters: ReconApiGetFileContentForExportJobsV1Request,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<Array<number>>> {
        if (requestParameters["id"] == null) {
            throw new runtime.RequiredError("id", 'Required parameter "id" was null or undefined when calling getFileContentForExportJobsV1().');
        }

        const queryParameters: any = {};

        if (requestParameters["id"] != null) {
            queryParameters["id"] = requestParameters["id"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["recon-monitoring-rules:read"]);
        }

        const response = await this.request(
            {
                path: `/recon/entities/export-files/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Download the file associated with a job ID.
     */
    async getFileContentForExportJobsV1(id: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<number>> {
        const response = await this.getFileContentForExportJobsV1Raw({ id: id }, initOverrides);
        return await response.value();
    }

    /**
     * Get detailed notifications based on their IDs. These include the translated raw intelligence content that generated the match or part of it. This API endpoint will return translated notification content. The only target language available is English. A single notification can be translated per request. In case the item\'s content is only partial, a URL is provided under the resource\'s \'details.full_content_url\' path, but the content available at this URL will be the original one.
     * Get detailed notifications based on their IDs. These include the translated raw intelligence content that generated the match or part of it.
     */
    async getNotificationsDetailedTranslatedV1Raw(
        requestParameters: ReconApiGetNotificationsDetailedTranslatedV1Request,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<DomainNotificationDetailsResponseV1>> {
        if (requestParameters["ids"] == null) {
            throw new runtime.RequiredError("ids", 'Required parameter "ids" was null or undefined when calling getNotificationsDetailedTranslatedV1().');
        }

        const queryParameters: any = {};

        if (requestParameters["ids"] != null) {
            queryParameters["ids"] = requestParameters["ids"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["recon-monitoring-rules:read"]);
        }

        const response = await this.request(
            {
                path: `/recon/entities/notifications-detailed-translated/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainNotificationDetailsResponseV1FromJSON(jsonValue));
    }

    /**
     * Get detailed notifications based on their IDs. These include the translated raw intelligence content that generated the match or part of it. This API endpoint will return translated notification content. The only target language available is English. A single notification can be translated per request. In case the item\'s content is only partial, a URL is provided under the resource\'s \'details.full_content_url\' path, but the content available at this URL will be the original one.
     * Get detailed notifications based on their IDs. These include the translated raw intelligence content that generated the match or part of it.
     */
    async getNotificationsDetailedTranslatedV1(ids: Array<string>, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainNotificationDetailsResponseV1> {
        const response = await this.getNotificationsDetailedTranslatedV1Raw({ ids: ids }, initOverrides);
        return await response.value();
    }

    /**
     * Get detailed notifications based on their IDs. These include the raw intelligence content that generated the match or part of it. In case the content is only partial, a URL is provided under the resource\'s \'details.full_content_url\' path. When present, use this URL to retrieve the full raw text content of the item. Please note this URL has a limited TTL. To get a fresh valid one, perform a new call to this API endpoint.
     * Get detailed notifications based on their IDs. These include the raw intelligence content that generated the match or part of it.
     */
    async getNotificationsDetailedV1Raw(
        requestParameters: ReconApiGetNotificationsDetailedV1Request,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<DomainNotificationDetailsResponseV1>> {
        if (requestParameters["ids"] == null) {
            throw new runtime.RequiredError("ids", 'Required parameter "ids" was null or undefined when calling getNotificationsDetailedV1().');
        }

        const queryParameters: any = {};

        if (requestParameters["ids"] != null) {
            queryParameters["ids"] = requestParameters["ids"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["recon-monitoring-rules:read"]);
        }

        const response = await this.request(
            {
                path: `/recon/entities/notifications-detailed/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainNotificationDetailsResponseV1FromJSON(jsonValue));
    }

    /**
     * Get detailed notifications based on their IDs. These include the raw intelligence content that generated the match or part of it. In case the content is only partial, a URL is provided under the resource\'s \'details.full_content_url\' path. When present, use this URL to retrieve the full raw text content of the item. Please note this URL has a limited TTL. To get a fresh valid one, perform a new call to this API endpoint.
     * Get detailed notifications based on their IDs. These include the raw intelligence content that generated the match or part of it.
     */
    async getNotificationsDetailedV1(ids: Array<string>, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainNotificationDetailsResponseV1> {
        const response = await this.getNotificationsDetailedV1Raw({ ids: ids }, initOverrides);
        return await response.value();
    }

    /**
     * Get notifications exposed data records based on their IDs. IDs can be retrieved using the GET /queries/notifications-exposed-data-records/v1 endpoint. The associate notification can be fetched using the /entities/notifications/v* endpoints
     */
    async getNotificationsExposedDataRecordsV1Raw(
        requestParameters: ReconApiGetNotificationsExposedDataRecordsV1Request,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<ApiNotificationExposedDataRecordEntitiesResponseV1>> {
        if (requestParameters["ids"] == null) {
            throw new runtime.RequiredError("ids", 'Required parameter "ids" was null or undefined when calling getNotificationsExposedDataRecordsV1().');
        }

        const queryParameters: any = {};

        if (requestParameters["ids"] != null) {
            queryParameters["ids"] = requestParameters["ids"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["recon-monitoring-rules:read"]);
        }

        const response = await this.request(
            {
                path: `/recon/entities/notifications-exposed-data-records/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiNotificationExposedDataRecordEntitiesResponseV1FromJSON(jsonValue));
    }

    /**
     * Get notifications exposed data records based on their IDs. IDs can be retrieved using the GET /queries/notifications-exposed-data-records/v1 endpoint. The associate notification can be fetched using the /entities/notifications/v* endpoints
     */
    async getNotificationsExposedDataRecordsV1(ids: Array<string>, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiNotificationExposedDataRecordEntitiesResponseV1> {
        const response = await this.getNotificationsExposedDataRecordsV1Raw({ ids: ids }, initOverrides);
        return await response.value();
    }

    /**
     * Get notifications based on their IDs. IDs can be retrieved using the GET /queries/notifications/v1 endpoint. This endpoint will return translated notification content. The only target language available is English.
     */
    async getNotificationsTranslatedV1Raw(
        requestParameters: ReconApiGetNotificationsTranslatedV1Request,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<DomainNotificationEntitiesResponseV1>> {
        if (requestParameters["ids"] == null) {
            throw new runtime.RequiredError("ids", 'Required parameter "ids" was null or undefined when calling getNotificationsTranslatedV1().');
        }

        const queryParameters: any = {};

        if (requestParameters["ids"] != null) {
            queryParameters["ids"] = requestParameters["ids"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["recon-monitoring-rules:read"]);
        }

        const response = await this.request(
            {
                path: `/recon/entities/notifications-translated/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainNotificationEntitiesResponseV1FromJSON(jsonValue));
    }

    /**
     * Get notifications based on their IDs. IDs can be retrieved using the GET /queries/notifications/v1 endpoint. This endpoint will return translated notification content. The only target language available is English.
     */
    async getNotificationsTranslatedV1(ids: Array<string>, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainNotificationEntitiesResponseV1> {
        const response = await this.getNotificationsTranslatedV1Raw({ ids: ids }, initOverrides);
        return await response.value();
    }

    /**
     * Get notifications based on their IDs. IDs can be retrieved using the GET /queries/notifications/v1 endpoint.
     */
    async getNotificationsV1Raw(
        requestParameters: ReconApiGetNotificationsV1Request,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<DomainNotificationEntitiesResponseV1>> {
        if (requestParameters["ids"] == null) {
            throw new runtime.RequiredError("ids", 'Required parameter "ids" was null or undefined when calling getNotificationsV1().');
        }

        const queryParameters: any = {};

        if (requestParameters["ids"] != null) {
            queryParameters["ids"] = requestParameters["ids"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["recon-monitoring-rules:read"]);
        }

        const response = await this.request(
            {
                path: `/recon/entities/notifications/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainNotificationEntitiesResponseV1FromJSON(jsonValue));
    }

    /**
     * Get notifications based on their IDs. IDs can be retrieved using the GET /queries/notifications/v1 endpoint.
     */
    async getNotificationsV1(ids: Array<string>, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainNotificationEntitiesResponseV1> {
        const response = await this.getNotificationsV1Raw({ ids: ids }, initOverrides);
        return await response.value();
    }

    /**
     * Get monitoring rules based on their IDs. IDs can be retrieved using the GET /queries/rules/v1 endpoint.
     */
    async getRulesV1Raw(requestParameters: ReconApiGetRulesV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DomainRulesEntitiesResponseV1>> {
        if (requestParameters["ids"] == null) {
            throw new runtime.RequiredError("ids", 'Required parameter "ids" was null or undefined when calling getRulesV1().');
        }

        const queryParameters: any = {};

        if (requestParameters["ids"] != null) {
            queryParameters["ids"] = requestParameters["ids"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["recon-monitoring-rules:read"]);
        }

        const response = await this.request(
            {
                path: `/recon/entities/rules/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainRulesEntitiesResponseV1FromJSON(jsonValue));
    }

    /**
     * Get monitoring rules based on their IDs. IDs can be retrieved using the GET /queries/rules/v1 endpoint.
     */
    async getRulesV1(ids: Array<string>, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainRulesEntitiesResponseV1> {
        const response = await this.getRulesV1Raw({ ids: ids }, initOverrides);
        return await response.value();
    }

    /**
     * Preview rules notification count and distribution. This will return aggregations on: channel, count, site.
     */
    async previewRuleV1Raw(requestParameters: ReconApiPreviewRuleV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DomainAggregatesResponse>> {
        if (requestParameters["body"] == null) {
            throw new runtime.RequiredError("body", 'Required parameter "body" was null or undefined when calling previewRuleV1().');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["recon-monitoring-rules:read"]);
        }

        const response = await this.request(
            {
                path: `/recon/aggregates/rules-preview/GET/v1`,
                method: "POST",
                headers: headerParameters,
                query: queryParameters,
                body: DomainRulePreviewRequestToJSON(requestParameters["body"]),
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainAggregatesResponseFromJSON(jsonValue));
    }

    /**
     * Preview rules notification count and distribution. This will return aggregations on: channel, count, site.
     */
    async previewRuleV1(body: DomainRulePreviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainAggregatesResponse> {
        const response = await this.previewRuleV1Raw({ body: body }, initOverrides);
        return await response.value();
    }

    /**
     * Query actions based on provided criteria. Use the IDs from this response to get the action entities on GET /entities/actions/v1.
     */
    async queryActionsV1Raw(requestParameters: ReconApiQueryActionsV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DomainQueryResponse>> {
        const queryParameters: any = {};

        if (requestParameters["offset"] != null) {
            queryParameters["offset"] = requestParameters["offset"];
        }

        if (requestParameters["limit"] != null) {
            queryParameters["limit"] = requestParameters["limit"];
        }

        if (requestParameters["sort"] != null) {
            queryParameters["sort"] = requestParameters["sort"];
        }

        if (requestParameters["filter"] != null) {
            queryParameters["filter"] = requestParameters["filter"];
        }

        if (requestParameters["q"] != null) {
            queryParameters["q"] = requestParameters["q"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["recon-monitoring-rules:read"]);
        }

        const response = await this.request(
            {
                path: `/recon/queries/actions/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainQueryResponseFromJSON(jsonValue));
    }

    /**
     * Query actions based on provided criteria. Use the IDs from this response to get the action entities on GET /entities/actions/v1.
     */
    async queryActionsV1(offset?: number, limit?: number, sort?: string, filter?: string, q?: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainQueryResponse> {
        const response = await this.queryActionsV1Raw({ offset: offset, limit: limit, sort: sort, filter: filter, q: q }, initOverrides);
        return await response.value();
    }

    /**
     * Query notifications exposed data records based on provided criteria. Use the IDs from this response to get the notification +entities on GET /entities/notifications-exposed-data-records/v1
     */
    async queryNotificationsExposedDataRecordsV1Raw(
        requestParameters: ReconApiQueryNotificationsExposedDataRecordsV1Request,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<DomainQueryResponse>> {
        const queryParameters: any = {};

        if (requestParameters["offset"] != null) {
            queryParameters["offset"] = requestParameters["offset"];
        }

        if (requestParameters["limit"] != null) {
            queryParameters["limit"] = requestParameters["limit"];
        }

        if (requestParameters["sort"] != null) {
            queryParameters["sort"] = requestParameters["sort"];
        }

        if (requestParameters["filter"] != null) {
            queryParameters["filter"] = requestParameters["filter"];
        }

        if (requestParameters["q"] != null) {
            queryParameters["q"] = requestParameters["q"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["recon-monitoring-rules:read"]);
        }

        const response = await this.request(
            {
                path: `/recon/queries/notifications-exposed-data-records/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainQueryResponseFromJSON(jsonValue));
    }

    /**
     * Query notifications exposed data records based on provided criteria. Use the IDs from this response to get the notification +entities on GET /entities/notifications-exposed-data-records/v1
     */
    async queryNotificationsExposedDataRecordsV1(
        offset?: number,
        limit?: number,
        sort?: string,
        filter?: string,
        q?: string,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<DomainQueryResponse> {
        const response = await this.queryNotificationsExposedDataRecordsV1Raw({ offset: offset, limit: limit, sort: sort, filter: filter, q: q }, initOverrides);
        return await response.value();
    }

    /**
     * Query notifications based on provided criteria. Use the IDs from this response to get the notification +entities on GET /entities/notifications/v1, GET /entities/notifications-detailed/v1, +GET /entities/notifications-translated/v1 or GET /entities/notifications-detailed-translated/v1.
     */
    async queryNotificationsV1Raw(
        requestParameters: ReconApiQueryNotificationsV1Request,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<DomainQueryResponse>> {
        const queryParameters: any = {};

        if (requestParameters["offset"] != null) {
            queryParameters["offset"] = requestParameters["offset"];
        }

        if (requestParameters["limit"] != null) {
            queryParameters["limit"] = requestParameters["limit"];
        }

        if (requestParameters["sort"] != null) {
            queryParameters["sort"] = requestParameters["sort"];
        }

        if (requestParameters["filter"] != null) {
            queryParameters["filter"] = requestParameters["filter"];
        }

        if (requestParameters["q"] != null) {
            queryParameters["q"] = requestParameters["q"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["recon-monitoring-rules:read"]);
        }

        const response = await this.request(
            {
                path: `/recon/queries/notifications/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainQueryResponseFromJSON(jsonValue));
    }

    /**
     * Query notifications based on provided criteria. Use the IDs from this response to get the notification +entities on GET /entities/notifications/v1, GET /entities/notifications-detailed/v1, +GET /entities/notifications-translated/v1 or GET /entities/notifications-detailed-translated/v1.
     */
    async queryNotificationsV1(offset?: number, limit?: number, sort?: string, filter?: string, q?: string, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainQueryResponse> {
        const response = await this.queryNotificationsV1Raw({ offset: offset, limit: limit, sort: sort, filter: filter, q: q }, initOverrides);
        return await response.value();
    }

    /**
     * Query monitoring rules based on provided criteria. Use the IDs from this response to fetch the rules on /entities/rules/v1.
     */
    async queryRulesV1Raw(requestParameters: ReconApiQueryRulesV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DomainRuleQueryResponseV1>> {
        const queryParameters: any = {};

        if (requestParameters["offset"] != null) {
            queryParameters["offset"] = requestParameters["offset"];
        }

        if (requestParameters["limit"] != null) {
            queryParameters["limit"] = requestParameters["limit"];
        }

        if (requestParameters["sort"] != null) {
            queryParameters["sort"] = requestParameters["sort"];
        }

        if (requestParameters["filter"] != null) {
            queryParameters["filter"] = requestParameters["filter"];
        }

        if (requestParameters["q"] != null) {
            queryParameters["q"] = requestParameters["q"];
        }

        if (requestParameters["secondarySort"] != null) {
            queryParameters["secondarySort"] = requestParameters["secondarySort"];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["recon-monitoring-rules:read"]);
        }

        const response = await this.request(
            {
                path: `/recon/queries/rules/v1`,
                method: "GET",
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainRuleQueryResponseV1FromJSON(jsonValue));
    }

    /**
     * Query monitoring rules based on provided criteria. Use the IDs from this response to fetch the rules on /entities/rules/v1.
     */
    async queryRulesV1(
        offset?: number,
        limit?: number,
        sort?: string,
        filter?: string,
        q?: string,
        secondarySort?: string,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<DomainRuleQueryResponseV1> {
        const response = await this.queryRulesV1Raw({ offset: offset, limit: limit, sort: sort, filter: filter, q: q, secondarySort: secondarySort }, initOverrides);
        return await response.value();
    }

    /**
     * Update an action for a monitoring rule.
     */
    async updateActionV1Raw(
        requestParameters: ReconApiUpdateActionV1Request,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<DomainActionEntitiesResponseV1>> {
        if (requestParameters["body"] == null) {
            throw new runtime.RequiredError("body", 'Required parameter "body" was null or undefined when calling updateActionV1().');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["recon-monitoring-rules:write"]);
        }

        const response = await this.request(
            {
                path: `/recon/entities/actions/v1`,
                method: "PATCH",
                headers: headerParameters,
                query: queryParameters,
                body: DomainUpdateActionRequestToJSON(requestParameters["body"]),
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainActionEntitiesResponseV1FromJSON(jsonValue));
    }

    /**
     * Update an action for a monitoring rule.
     */
    async updateActionV1(body: DomainUpdateActionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainActionEntitiesResponseV1> {
        const response = await this.updateActionV1Raw({ body: body }, initOverrides);
        return await response.value();
    }

    /**
     * Update notification status or assignee. Accepts bulk requests
     */
    async updateNotificationsV1Raw(
        requestParameters: ReconApiUpdateNotificationsV1Request,
        initOverrides?: RequestInit | runtime.InitOverrideFunction
    ): Promise<runtime.ApiResponse<DomainNotificationEntitiesResponseV1>> {
        if (requestParameters["body"] == null) {
            throw new runtime.RequiredError("body", 'Required parameter "body" was null or undefined when calling updateNotificationsV1().');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["recon-monitoring-rules:write"]);
        }

        const response = await this.request(
            {
                path: `/recon/entities/notifications/v1`,
                method: "PATCH",
                headers: headerParameters,
                query: queryParameters,
                body: requestParameters["body"]!.map(DomainUpdateNotificationRequestV1ToJSON),
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainNotificationEntitiesResponseV1FromJSON(jsonValue));
    }

    /**
     * Update notification status or assignee. Accepts bulk requests
     */
    async updateNotificationsV1(body: Array<DomainUpdateNotificationRequestV1>, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainNotificationEntitiesResponseV1> {
        const response = await this.updateNotificationsV1Raw({ body: body }, initOverrides);
        return await response.value();
    }

    /**
     * Update monitoring rules.
     */
    async updateRulesV1Raw(requestParameters: ReconApiUpdateRulesV1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DomainRulesEntitiesResponseV1>> {
        if (requestParameters["body"] == null) {
            throw new runtime.RequiredError("body", 'Required parameter "body" was null or undefined when calling updateRulesV1().');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters["Content-Type"] = "application/json";

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("oauth2", ["recon-monitoring-rules:write"]);
        }

        const response = await this.request(
            {
                path: `/recon/entities/rules/v1`,
                method: "PATCH",
                headers: headerParameters,
                query: queryParameters,
                body: requestParameters["body"]!.map(DomainUpdateRuleRequestV1ToJSON),
            },
            initOverrides
        );

        return new runtime.JSONApiResponse(response, (jsonValue) => DomainRulesEntitiesResponseV1FromJSON(jsonValue));
    }

    /**
     * Update monitoring rules.
     */
    async updateRulesV1(body: Array<DomainUpdateRuleRequestV1>, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DomainRulesEntitiesResponseV1> {
        const response = await this.updateRulesV1Raw({ body: body }, initOverrides);
        return await response.value();
    }
}
