/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ApiAssertionOnFieldWasOrphaned } from "./ApiAssertionOnFieldWasOrphaned";
import { ApiAssertionOnFieldWasOrphanedFromJSON, ApiAssertionOnFieldWasOrphanedFromJSONTyped, ApiAssertionOnFieldWasOrphanedToJSON } from "./ApiAssertionOnFieldWasOrphaned";
import type { ApiFieldHadConflictingAssertions } from "./ApiFieldHadConflictingAssertions";
import { ApiFieldHadConflictingAssertionsFromJSON, ApiFieldHadConflictingAssertionsFromJSONTyped, ApiFieldHadConflictingAssertionsToJSON } from "./ApiFieldHadConflictingAssertions";
import type { ApiFieldHadUnexpectedValue } from "./ApiFieldHadUnexpectedValue";
import { ApiFieldHadUnexpectedValueFromJSON, ApiFieldHadUnexpectedValueFromJSONTyped, ApiFieldHadUnexpectedValueToJSON } from "./ApiFieldHadUnexpectedValue";
import type { ApiFieldUnexpectedlyPresent } from "./ApiFieldUnexpectedlyPresent";
import { ApiFieldUnexpectedlyPresentFromJSON, ApiFieldUnexpectedlyPresentFromJSONTyped, ApiFieldUnexpectedlyPresentToJSON } from "./ApiFieldUnexpectedlyPresent";

/**
 *
 * @export
 * @interface ApiAssertionFailureOnField
 */
export interface ApiAssertionFailureOnField {
    /**
     *
     * @type {ApiAssertionOnFieldWasOrphaned}
     * @memberof ApiAssertionFailureOnField
     */
    assertionOnFieldWasOrphaned?: ApiAssertionOnFieldWasOrphaned;
    /**
     *
     * @type {ApiFieldHadConflictingAssertions}
     * @memberof ApiAssertionFailureOnField
     */
    fieldHadConflictingAssertions?: ApiFieldHadConflictingAssertions;
    /**
     *
     * @type {ApiFieldHadUnexpectedValue}
     * @memberof ApiAssertionFailureOnField
     */
    fieldHadUnexpectedValue?: ApiFieldHadUnexpectedValue;
    /**
     *
     * @type {ApiFieldUnexpectedlyPresent}
     * @memberof ApiAssertionFailureOnField
     */
    fieldUnexpectedlyPresent?: ApiFieldUnexpectedlyPresent;
    /**
     * Type name of the failure
     * @type {string}
     * @memberof ApiAssertionFailureOnField
     */
    typename: string;
}

/**
 * Check if a given object implements the ApiAssertionFailureOnField interface.
 */
export function instanceOfApiAssertionFailureOnField(value: object): value is ApiAssertionFailureOnField {
    if (!("typename" in value) || value["typename"] === undefined) return false;
    return true;
}

export function ApiAssertionFailureOnFieldFromJSON(json: any): ApiAssertionFailureOnField {
    return ApiAssertionFailureOnFieldFromJSONTyped(json, false);
}

export function ApiAssertionFailureOnFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiAssertionFailureOnField {
    if (json == null) {
        return json;
    }
    return {
        assertionOnFieldWasOrphaned: json["assertion_on_field_was_orphaned"] == null ? undefined : ApiAssertionOnFieldWasOrphanedFromJSON(json["assertion_on_field_was_orphaned"]),
        fieldHadConflictingAssertions: json["field_had_conflicting_assertions"] == null ? undefined : ApiFieldHadConflictingAssertionsFromJSON(json["field_had_conflicting_assertions"]),
        fieldHadUnexpectedValue: json["field_had_unexpected_value"] == null ? undefined : ApiFieldHadUnexpectedValueFromJSON(json["field_had_unexpected_value"]),
        fieldUnexpectedlyPresent: json["field_unexpectedly_present"] == null ? undefined : ApiFieldUnexpectedlyPresentFromJSON(json["field_unexpectedly_present"]),
        typename: json["typename"],
    };
}

export function ApiAssertionFailureOnFieldToJSON(value?: ApiAssertionFailureOnField | null): any {
    if (value == null) {
        return value;
    }
    return {
        assertion_on_field_was_orphaned: ApiAssertionOnFieldWasOrphanedToJSON(value["assertionOnFieldWasOrphaned"]),
        field_had_conflicting_assertions: ApiFieldHadConflictingAssertionsToJSON(value["fieldHadConflictingAssertions"]),
        field_had_unexpected_value: ApiFieldHadUnexpectedValueToJSON(value["fieldHadUnexpectedValue"]),
        field_unexpectedly_present: ApiFieldUnexpectedlyPresentToJSON(value["fieldUnexpectedlyPresent"]),
        typename: value["typename"],
    };
}
