/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ApiLocalApplicationCreateRequestV1
 */
export interface ApiLocalApplicationCreateRequestV1 {
    /**
     *
     * @type {boolean}
     * @memberof ApiLocalApplicationCreateRequestV1
     */
    applyRulesForChildrenProcesses: boolean;
    /**
     *
     * @type {boolean}
     * @memberof ApiLocalApplicationCreateRequestV1
     */
    emitRuleMatchedEventsOnly: boolean;
    /**
     *
     * @type {boolean}
     * @memberof ApiLocalApplicationCreateRequestV1
     */
    enableRenameDetection: boolean;
    /**
     *
     * @type {string}
     * @memberof ApiLocalApplicationCreateRequestV1
     */
    executableName: string;
    /**
     *
     * @type {Array<string>}
     * @memberof ApiLocalApplicationCreateRequestV1
     */
    groupIds: Array<string>;
    /**
     *
     * @type {string}
     * @memberof ApiLocalApplicationCreateRequestV1
     */
    name: string;
}

/**
 * Check if a given object implements the ApiLocalApplicationCreateRequestV1 interface.
 */
export function instanceOfApiLocalApplicationCreateRequestV1(value: object): value is ApiLocalApplicationCreateRequestV1 {
    if (!("applyRulesForChildrenProcesses" in value) || value["applyRulesForChildrenProcesses"] === undefined) return false;
    if (!("emitRuleMatchedEventsOnly" in value) || value["emitRuleMatchedEventsOnly"] === undefined) return false;
    if (!("enableRenameDetection" in value) || value["enableRenameDetection"] === undefined) return false;
    if (!("executableName" in value) || value["executableName"] === undefined) return false;
    if (!("groupIds" in value) || value["groupIds"] === undefined) return false;
    if (!("name" in value) || value["name"] === undefined) return false;
    return true;
}

export function ApiLocalApplicationCreateRequestV1FromJSON(json: any): ApiLocalApplicationCreateRequestV1 {
    return ApiLocalApplicationCreateRequestV1FromJSONTyped(json, false);
}

export function ApiLocalApplicationCreateRequestV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiLocalApplicationCreateRequestV1 {
    if (json == null) {
        return json;
    }
    return {
        applyRulesForChildrenProcesses: json["apply_rules_for_children_processes"],
        emitRuleMatchedEventsOnly: json["emit_rule_matched_events_only"],
        enableRenameDetection: json["enable_rename_detection"],
        executableName: json["executable_name"],
        groupIds: json["group_ids"],
        name: json["name"],
    };
}

export function ApiLocalApplicationCreateRequestV1ToJSON(value?: ApiLocalApplicationCreateRequestV1 | null): any {
    if (value == null) {
        return value;
    }
    return {
        apply_rules_for_children_processes: value["applyRulesForChildrenProcesses"],
        emit_rule_matched_events_only: value["emitRuleMatchedEventsOnly"],
        enable_rename_detection: value["enableRenameDetection"],
        executable_name: value["executableName"],
        group_ids: value["groupIds"],
        name: value["name"],
    };
}
