/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ApimodelsSecurityFramework } from "./ApimodelsSecurityFramework";
import { ApimodelsSecurityFrameworkFromJSON, ApimodelsSecurityFrameworkFromJSONTyped, ApimodelsSecurityFrameworkToJSON } from "./ApimodelsSecurityFramework";

/**
 *
 * @export
 * @interface ApimodelsControl
 */
export interface ApimodelsControl {
    /**
     *
     * @type {Array<string>}
     * @memberof ApimodelsControl
     */
    applicableProfiles?: Array<string>;
    /**
     *
     * @type {string}
     * @memberof ApimodelsControl
     */
    authority: string;
    /**
     *
     * @type {string}
     * @memberof ApimodelsControl
     */
    code: string;
    /**
     *
     * @type {string}
     * @memberof ApimodelsControl
     */
    controlType?: string;
    /**
     *
     * @type {string}
     * @memberof ApimodelsControl
     */
    controlVersion?: string;
    /**
     *
     * @type {string}
     * @memberof ApimodelsControl
     */
    description?: string;
    /**
     *
     * @type {string}
     * @memberof ApimodelsControl
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof ApimodelsControl
     */
    origin: string;
    /**
     *
     * @type {string}
     * @memberof ApimodelsControl
     */
    requirement?: string;
    /**
     *
     * @type {string}
     * @memberof ApimodelsControl
     */
    sectionName?: string;
    /**
     *
     * @type {Array<ApimodelsSecurityFramework>}
     * @memberof ApimodelsControl
     */
    securityFramework?: Array<ApimodelsSecurityFramework>;
    /**
     *
     * @type {string}
     * @memberof ApimodelsControl
     */
    uuid: string;
}

/**
 * Check if a given object implements the ApimodelsControl interface.
 */
export function instanceOfApimodelsControl(value: object): value is ApimodelsControl {
    if (!("authority" in value) || value["authority"] === undefined) return false;
    if (!("code" in value) || value["code"] === undefined) return false;
    if (!("name" in value) || value["name"] === undefined) return false;
    if (!("origin" in value) || value["origin"] === undefined) return false;
    if (!("uuid" in value) || value["uuid"] === undefined) return false;
    return true;
}

export function ApimodelsControlFromJSON(json: any): ApimodelsControl {
    return ApimodelsControlFromJSONTyped(json, false);
}

export function ApimodelsControlFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApimodelsControl {
    if (json == null) {
        return json;
    }
    return {
        applicableProfiles: json["applicable_profiles"] == null ? undefined : json["applicable_profiles"],
        authority: json["authority"],
        code: json["code"],
        controlType: json["control_type"] == null ? undefined : json["control_type"],
        controlVersion: json["control_version"] == null ? undefined : json["control_version"],
        description: json["description"] == null ? undefined : json["description"],
        name: json["name"],
        origin: json["origin"],
        requirement: json["requirement"] == null ? undefined : json["requirement"],
        sectionName: json["section_name"] == null ? undefined : json["section_name"],
        securityFramework: json["security_framework"] == null ? undefined : (json["security_framework"] as Array<any>).map(ApimodelsSecurityFrameworkFromJSON),
        uuid: json["uuid"],
    };
}

export function ApimodelsControlToJSON(value?: ApimodelsControl | null): any {
    if (value == null) {
        return value;
    }
    return {
        applicable_profiles: value["applicableProfiles"],
        authority: value["authority"],
        code: value["code"],
        control_type: value["controlType"],
        control_version: value["controlVersion"],
        description: value["description"],
        name: value["name"],
        origin: value["origin"],
        requirement: value["requirement"],
        section_name: value["sectionName"],
        security_framework: value["securityFramework"] == null ? undefined : (value["securityFramework"] as Array<any>).map(ApimodelsSecurityFrameworkToJSON),
        uuid: value["uuid"],
    };
}
