/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ApiFieldV1UpdateRequest } from "./ApiFieldV1UpdateRequest";
import { ApiFieldV1UpdateRequestFromJSON, ApiFieldV1UpdateRequestFromJSONTyped, ApiFieldV1UpdateRequestToJSON } from "./ApiFieldV1UpdateRequest";
import type { ApiWorkflowV1 } from "./ApiWorkflowV1";
import { ApiWorkflowV1FromJSON, ApiWorkflowV1FromJSONTyped, ApiWorkflowV1ToJSON } from "./ApiWorkflowV1";
import type { ApiTemplateSLARuleV1UpdateRequest } from "./ApiTemplateSLARuleV1UpdateRequest";
import { ApiTemplateSLARuleV1UpdateRequestFromJSON, ApiTemplateSLARuleV1UpdateRequestFromJSONTyped, ApiTemplateSLARuleV1UpdateRequestToJSON } from "./ApiTemplateSLARuleV1UpdateRequest";
import type { ApiAccessTagV1 } from "./ApiAccessTagV1";
import { ApiAccessTagV1FromJSON, ApiAccessTagV1FromJSONTyped, ApiAccessTagV1ToJSON } from "./ApiAccessTagV1";

/**
 *
 * @export
 * @interface ApiTemplateV1UpdateRequest
 */
export interface ApiTemplateV1UpdateRequest {
    /**
     *
     * @type {Array<ApiAccessTagV1>}
     * @memberof ApiTemplateV1UpdateRequest
     */
    accessTags?: Array<ApiAccessTagV1>;
    /**
     *
     * @type {string}
     * @memberof ApiTemplateV1UpdateRequest
     */
    description?: string;
    /**
     *
     * @type {Array<ApiFieldV1UpdateRequest>}
     * @memberof ApiTemplateV1UpdateRequest
     */
    fields?: Array<ApiFieldV1UpdateRequest>;
    /**
     *
     * @type {string}
     * @memberof ApiTemplateV1UpdateRequest
     */
    id: string;
    /**
     *
     * @type {string}
     * @memberof ApiTemplateV1UpdateRequest
     */
    name: string;
    /**
     *
     * @type {string}
     * @memberof ApiTemplateV1UpdateRequest
     */
    slaId?: string;
    /**
     *
     * @type {Array<ApiTemplateSLARuleV1UpdateRequest>}
     * @memberof ApiTemplateV1UpdateRequest
     */
    slaRules?: Array<ApiTemplateSLARuleV1UpdateRequest>;
    /**
     *
     * @type {Array<ApiWorkflowV1>}
     * @memberof ApiTemplateV1UpdateRequest
     */
    workflows?: Array<ApiWorkflowV1>;
}

/**
 * Check if a given object implements the ApiTemplateV1UpdateRequest interface.
 */
export function instanceOfApiTemplateV1UpdateRequest(value: object): value is ApiTemplateV1UpdateRequest {
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("name" in value) || value["name"] === undefined) return false;
    return true;
}

export function ApiTemplateV1UpdateRequestFromJSON(json: any): ApiTemplateV1UpdateRequest {
    return ApiTemplateV1UpdateRequestFromJSONTyped(json, false);
}

export function ApiTemplateV1UpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiTemplateV1UpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        accessTags: json["access_tags"] == null ? undefined : (json["access_tags"] as Array<any>).map(ApiAccessTagV1FromJSON),
        description: json["description"] == null ? undefined : json["description"],
        fields: json["fields"] == null ? undefined : (json["fields"] as Array<any>).map(ApiFieldV1UpdateRequestFromJSON),
        id: json["id"],
        name: json["name"],
        slaId: json["sla_id"] == null ? undefined : json["sla_id"],
        slaRules: json["sla_rules"] == null ? undefined : (json["sla_rules"] as Array<any>).map(ApiTemplateSLARuleV1UpdateRequestFromJSON),
        workflows: json["workflows"] == null ? undefined : (json["workflows"] as Array<any>).map(ApiWorkflowV1FromJSON),
    };
}

export function ApiTemplateV1UpdateRequestToJSON(value?: ApiTemplateV1UpdateRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        access_tags: value["accessTags"] == null ? undefined : (value["accessTags"] as Array<any>).map(ApiAccessTagV1ToJSON),
        description: value["description"],
        fields: value["fields"] == null ? undefined : (value["fields"] as Array<any>).map(ApiFieldV1UpdateRequestToJSON),
        id: value["id"],
        name: value["name"],
        sla_id: value["slaId"],
        sla_rules: value["slaRules"] == null ? undefined : (value["slaRules"] as Array<any>).map(ApiTemplateSLARuleV1UpdateRequestToJSON),
        workflows: value["workflows"] == null ? undefined : (value["workflows"] as Array<any>).map(ApiWorkflowV1ToJSON),
    };
}
