/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface AssetGetAssetInventory
 */
export interface AssetGetAssetInventory {
    /**
     *
     * @type {string}
     * @memberof AssetGetAssetInventory
     */
    accessLevel?: string;
    /**
     *
     * @type {string}
     * @memberof AssetGetAssetInventory
     */
    accountId: string;
    /**
     *
     * @type {string}
     * @memberof AssetGetAssetInventory
     */
    created: string;
    /**
     *
     * @type {string}
     * @memberof AssetGetAssetInventory
     */
    drive?: string;
    /**
     *
     * @type {string}
     * @memberof AssetGetAssetInventory
     */
    driveId?: string;
    /**
     *
     * @type {string}
     * @memberof AssetGetAssetInventory
     */
    integrationAlias: string;
    /**
     *
     * @type {string}
     * @memberof AssetGetAssetInventory
     */
    integrationId: string;
    /**
     *
     * @type {string}
     * @memberof AssetGetAssetInventory
     */
    integrationName: string;
    /**
     *
     * @type {string}
     * @memberof AssetGetAssetInventory
     */
    lastAccessed: string;
    /**
     *
     * @type {string}
     * @memberof AssetGetAssetInventory
     */
    lastModified: string;
    /**
     *
     * @type {string}
     * @memberof AssetGetAssetInventory
     */
    parent?: string;
    /**
     *
     * @type {boolean}
     * @memberof AssetGetAssetInventory
     */
    passwordProtected?: boolean;
    /**
     *
     * @type {string}
     * @memberof AssetGetAssetInventory
     */
    permissionId?: string;
    /**
     *
     * @type {string}
     * @memberof AssetGetAssetInventory
     */
    resourceId: string;
    /**
     *
     * @type {string}
     * @memberof AssetGetAssetInventory
     */
    resourceName: string;
    /**
     *
     * @type {string}
     * @memberof AssetGetAssetInventory
     */
    resourceOwner: string;
    /**
     *
     * @type {string}
     * @memberof AssetGetAssetInventory
     */
    resourceOwnerDepartment: string;
    /**
     *
     * @type {boolean}
     * @memberof AssetGetAssetInventory
     */
    resourceOwnerEnabled: boolean;
    /**
     *
     * @type {string}
     * @memberof AssetGetAssetInventory
     */
    resourceType: string;
    /**
     *
     * @type {Array<string>}
     * @memberof AssetGetAssetInventory
     */
    sharedWith?: Array<string>;
}

/**
 * Check if a given object implements the AssetGetAssetInventory interface.
 */
export function instanceOfAssetGetAssetInventory(value: object): value is AssetGetAssetInventory {
    if (!("accountId" in value) || value["accountId"] === undefined) return false;
    if (!("created" in value) || value["created"] === undefined) return false;
    if (!("integrationAlias" in value) || value["integrationAlias"] === undefined) return false;
    if (!("integrationId" in value) || value["integrationId"] === undefined) return false;
    if (!("integrationName" in value) || value["integrationName"] === undefined) return false;
    if (!("lastAccessed" in value) || value["lastAccessed"] === undefined) return false;
    if (!("lastModified" in value) || value["lastModified"] === undefined) return false;
    if (!("resourceId" in value) || value["resourceId"] === undefined) return false;
    if (!("resourceName" in value) || value["resourceName"] === undefined) return false;
    if (!("resourceOwner" in value) || value["resourceOwner"] === undefined) return false;
    if (!("resourceOwnerDepartment" in value) || value["resourceOwnerDepartment"] === undefined) return false;
    if (!("resourceOwnerEnabled" in value) || value["resourceOwnerEnabled"] === undefined) return false;
    if (!("resourceType" in value) || value["resourceType"] === undefined) return false;
    return true;
}

export function AssetGetAssetInventoryFromJSON(json: any): AssetGetAssetInventory {
    return AssetGetAssetInventoryFromJSONTyped(json, false);
}

export function AssetGetAssetInventoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetGetAssetInventory {
    if (json == null) {
        return json;
    }
    return {
        accessLevel: json["access_level"] == null ? undefined : json["access_level"],
        accountId: json["account_id"],
        created: json["created"],
        drive: json["drive"] == null ? undefined : json["drive"],
        driveId: json["drive_id"] == null ? undefined : json["drive_id"],
        integrationAlias: json["integration_alias"],
        integrationId: json["integration_id"],
        integrationName: json["integration_name"],
        lastAccessed: json["last_accessed"],
        lastModified: json["last_modified"],
        parent: json["parent"] == null ? undefined : json["parent"],
        passwordProtected: json["password_protected"] == null ? undefined : json["password_protected"],
        permissionId: json["permission_id"] == null ? undefined : json["permission_id"],
        resourceId: json["resource_id"],
        resourceName: json["resource_name"],
        resourceOwner: json["resource_owner"],
        resourceOwnerDepartment: json["resource_owner_department"],
        resourceOwnerEnabled: json["resource_owner_enabled"],
        resourceType: json["resource_type"],
        sharedWith: json["shared_with"] == null ? undefined : json["shared_with"],
    };
}

export function AssetGetAssetInventoryToJSON(value?: AssetGetAssetInventory | null): any {
    if (value == null) {
        return value;
    }
    return {
        access_level: value["accessLevel"],
        account_id: value["accountId"],
        created: value["created"],
        drive: value["drive"],
        drive_id: value["driveId"],
        integration_alias: value["integrationAlias"],
        integration_id: value["integrationId"],
        integration_name: value["integrationName"],
        last_accessed: value["lastAccessed"],
        last_modified: value["lastModified"],
        parent: value["parent"],
        password_protected: value["passwordProtected"],
        permission_id: value["permissionId"],
        resource_id: value["resourceId"],
        resource_name: value["resourceName"],
        resource_owner: value["resourceOwner"],
        resource_owner_department: value["resourceOwnerDepartment"],
        resource_owner_enabled: value["resourceOwnerEnabled"],
        resource_type: value["resourceType"],
        shared_with: value["sharedWith"],
    };
}
