/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { AssetgroupmanagerV1CloudGroup } from "./AssetgroupmanagerV1CloudGroup";
import { AssetgroupmanagerV1CloudGroupFromJSON, AssetgroupmanagerV1CloudGroupFromJSONTyped, AssetgroupmanagerV1CloudGroupToJSON } from "./AssetgroupmanagerV1CloudGroup";
import type { AssetgroupmanagerV1Error } from "./AssetgroupmanagerV1Error";
import { AssetgroupmanagerV1ErrorFromJSON, AssetgroupmanagerV1ErrorFromJSONTyped, AssetgroupmanagerV1ErrorToJSON } from "./AssetgroupmanagerV1Error";
import type { AssetgroupmanagerV1Meta } from "./AssetgroupmanagerV1Meta";
import { AssetgroupmanagerV1MetaFromJSON, AssetgroupmanagerV1MetaFromJSONTyped, AssetgroupmanagerV1MetaToJSON } from "./AssetgroupmanagerV1Meta";

/**
 *
 * @export
 * @interface AssetgroupmanagerV1ListCloudGroupsResponse
 */
export interface AssetgroupmanagerV1ListCloudGroupsResponse {
    /**
     *
     * @type {Array<AssetgroupmanagerV1Error>}
     * @memberof AssetgroupmanagerV1ListCloudGroupsResponse
     */
    errors?: Array<AssetgroupmanagerV1Error>;
    /**
     *
     * @type {AssetgroupmanagerV1Meta}
     * @memberof AssetgroupmanagerV1ListCloudGroupsResponse
     */
    meta?: AssetgroupmanagerV1Meta;
    /**
     *
     * @type {Array<AssetgroupmanagerV1CloudGroup>}
     * @memberof AssetgroupmanagerV1ListCloudGroupsResponse
     */
    resources?: Array<AssetgroupmanagerV1CloudGroup>;
}

/**
 * Check if a given object implements the AssetgroupmanagerV1ListCloudGroupsResponse interface.
 */
export function instanceOfAssetgroupmanagerV1ListCloudGroupsResponse(value: object): value is AssetgroupmanagerV1ListCloudGroupsResponse {
    return true;
}

export function AssetgroupmanagerV1ListCloudGroupsResponseFromJSON(json: any): AssetgroupmanagerV1ListCloudGroupsResponse {
    return AssetgroupmanagerV1ListCloudGroupsResponseFromJSONTyped(json, false);
}

export function AssetgroupmanagerV1ListCloudGroupsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetgroupmanagerV1ListCloudGroupsResponse {
    if (json == null) {
        return json;
    }
    return {
        errors: json["errors"] == null ? undefined : (json["errors"] as Array<any>).map(AssetgroupmanagerV1ErrorFromJSON),
        meta: json["meta"] == null ? undefined : AssetgroupmanagerV1MetaFromJSON(json["meta"]),
        resources: json["resources"] == null ? undefined : (json["resources"] as Array<any>).map(AssetgroupmanagerV1CloudGroupFromJSON),
    };
}

export function AssetgroupmanagerV1ListCloudGroupsResponseToJSON(value?: AssetgroupmanagerV1ListCloudGroupsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        errors: value["errors"] == null ? undefined : (value["errors"] as Array<any>).map(AssetgroupmanagerV1ErrorToJSON),
        meta: AssetgroupmanagerV1MetaToJSON(value["meta"]),
        resources: value["resources"] == null ? undefined : (value["resources"] as Array<any>).map(AssetgroupmanagerV1CloudGroupToJSON),
    };
}
