/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ContentUpdateContentUpdateSettingsReqV1 } from "./ContentUpdateContentUpdateSettingsReqV1";
import {
    ContentUpdateContentUpdateSettingsReqV1FromJSON,
    ContentUpdateContentUpdateSettingsReqV1FromJSONTyped,
    ContentUpdateContentUpdateSettingsReqV1ToJSON,
} from "./ContentUpdateContentUpdateSettingsReqV1";

/**
 *
 * @export
 * @interface ContentUpdateCreatePolicyReqV1
 */
export interface ContentUpdateCreatePolicyReqV1 {
    /**
     * The description to use when creating the policy
     * @type {string}
     * @memberof ContentUpdateCreatePolicyReqV1
     */
    description?: string;
    /**
     * The name to use when creating the policy
     * @type {string}
     * @memberof ContentUpdateCreatePolicyReqV1
     */
    name: string;
    /**
     *
     * @type {ContentUpdateContentUpdateSettingsReqV1}
     * @memberof ContentUpdateCreatePolicyReqV1
     */
    settings?: ContentUpdateContentUpdateSettingsReqV1;
}

/**
 * Check if a given object implements the ContentUpdateCreatePolicyReqV1 interface.
 */
export function instanceOfContentUpdateCreatePolicyReqV1(value: object): value is ContentUpdateCreatePolicyReqV1 {
    if (!("name" in value) || value["name"] === undefined) return false;
    return true;
}

export function ContentUpdateCreatePolicyReqV1FromJSON(json: any): ContentUpdateCreatePolicyReqV1 {
    return ContentUpdateCreatePolicyReqV1FromJSONTyped(json, false);
}

export function ContentUpdateCreatePolicyReqV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentUpdateCreatePolicyReqV1 {
    if (json == null) {
        return json;
    }
    return {
        description: json["description"] == null ? undefined : json["description"],
        name: json["name"],
        settings: json["settings"] == null ? undefined : ContentUpdateContentUpdateSettingsReqV1FromJSON(json["settings"]),
    };
}

export function ContentUpdateCreatePolicyReqV1ToJSON(value?: ContentUpdateCreatePolicyReqV1 | null): any {
    if (value == null) {
        return value;
    }
    return {
        description: value["description"],
        name: value["name"],
        settings: ContentUpdateContentUpdateSettingsReqV1ToJSON(value["settings"]),
    };
}
