/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ActivitiesActivityExtField } from "./ActivitiesActivityExtField";
import { ActivitiesActivityExtFieldFromJSON, ActivitiesActivityExtFieldFromJSONTyped, ActivitiesActivityExtFieldToJSON } from "./ActivitiesActivityExtField";
import type { ActivitiesDependency } from "./ActivitiesDependency";
import { ActivitiesDependencyFromJSON, ActivitiesDependencyFromJSONTyped, ActivitiesDependencyToJSON } from "./ActivitiesDependency";

/**
 *
 * @export
 * @interface ContentActivityMetadata
 */
export interface ContentActivityMetadata {
    /**
     * List of dependencies including app details and logo URLs
     * @type {Array<ActivitiesDependency>}
     * @memberof ContentActivityMetadata
     */
    dependencies: Array<ActivitiesDependency>;
    /**
     * Description of the content.
     * @type {string}
     * @memberof ContentActivityMetadata
     */
    description: string;
    /**
     * Highlights the fields where search term appeared
     * @type {{ [key: string]: Array<string>; }}
     * @memberof ContentActivityMetadata
     */
    highlight?: { [key: string]: Array<string> };
    /**
     * ID of the content.
     * @type {string}
     * @memberof ContentActivityMetadata
     */
    id: string;
    /**
     * Field configs of the activity's output, derived by flattening the Input schema.
     * @type {Array<ActivitiesActivityExtField>}
     * @memberof ContentActivityMetadata
     */
    inputFields: Array<ActivitiesActivityExtField>;
    /**
     * Timestamp of when the content was last modified.
     * @type {Date}
     * @memberof ContentActivityMetadata
     */
    lastModified: Date;
    /**
     * Name of the content.
     * @type {string}
     * @memberof ContentActivityMetadata
     */
    name: string;
    /**
     * Field configs of the activity's output, derived by flattening the Output schema.
     * @type {Array<ActivitiesActivityExtField>}
     * @memberof ContentActivityMetadata
     */
    outputFields: Array<ActivitiesActivityExtField>;
    /**
     * Indicates relevancy of the result to the search query term
     * @type {number}
     * @memberof ContentActivityMetadata
     */
    score?: number;
    /**
     * Use cases associated with this activity
     * @type {Array<string>}
     * @memberof ContentActivityMetadata
     */
    useCases: Array<string>;
    /**
     * Vendor whose products are integrated by this activity
     * @type {string}
     * @memberof ContentActivityMetadata
     */
    vendor: string;
}

/**
 * Check if a given object implements the ContentActivityMetadata interface.
 */
export function instanceOfContentActivityMetadata(value: object): value is ContentActivityMetadata {
    if (!("dependencies" in value) || value["dependencies"] === undefined) return false;
    if (!("description" in value) || value["description"] === undefined) return false;
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("inputFields" in value) || value["inputFields"] === undefined) return false;
    if (!("lastModified" in value) || value["lastModified"] === undefined) return false;
    if (!("name" in value) || value["name"] === undefined) return false;
    if (!("outputFields" in value) || value["outputFields"] === undefined) return false;
    if (!("useCases" in value) || value["useCases"] === undefined) return false;
    if (!("vendor" in value) || value["vendor"] === undefined) return false;
    return true;
}

export function ContentActivityMetadataFromJSON(json: any): ContentActivityMetadata {
    return ContentActivityMetadataFromJSONTyped(json, false);
}

export function ContentActivityMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentActivityMetadata {
    if (json == null) {
        return json;
    }
    return {
        dependencies: (json["dependencies"] as Array<any>).map(ActivitiesDependencyFromJSON),
        description: json["description"],
        highlight: json["highlight"] == null ? undefined : json["highlight"],
        id: json["id"],
        inputFields: (json["input_fields"] as Array<any>).map(ActivitiesActivityExtFieldFromJSON),
        lastModified: new Date(json["last_modified"]),
        name: json["name"],
        outputFields: (json["output_fields"] as Array<any>).map(ActivitiesActivityExtFieldFromJSON),
        score: json["score"] == null ? undefined : json["score"],
        useCases: json["use_cases"],
        vendor: json["vendor"],
    };
}

export function ContentActivityMetadataToJSON(value?: ContentActivityMetadata | null): any {
    if (value == null) {
        return value;
    }
    return {
        dependencies: (value["dependencies"] as Array<any>).map(ActivitiesDependencyToJSON),
        description: value["description"],
        highlight: value["highlight"],
        id: value["id"],
        input_fields: (value["inputFields"] as Array<any>).map(ActivitiesActivityExtFieldToJSON),
        last_modified: value["lastModified"].toISOString(),
        name: value["name"],
        output_fields: (value["outputFields"] as Array<any>).map(ActivitiesActivityExtFieldToJSON),
        score: value["score"],
        use_cases: value["useCases"],
        vendor: value["vendor"],
    };
}
