/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface CorrelationrulesapiRuleResultMetadataV1
 */
export interface CorrelationrulesapiRuleResultMetadataV1 {
    /**
     *
     * @type {number}
     * @memberof CorrelationrulesapiRuleResultMetadataV1
     */
    executionDuration?: number;
    /**
     *
     * @type {Date}
     * @memberof CorrelationrulesapiRuleResultMetadataV1
     */
    executionFinish?: Date;
    /**
     *
     * @type {Date}
     * @memberof CorrelationrulesapiRuleResultMetadataV1
     */
    executionStart?: Date;
    /**
     *
     * @type {number}
     * @memberof CorrelationrulesapiRuleResultMetadataV1
     */
    resultCount?: number;
    /**
     *
     * @type {Date}
     * @memberof CorrelationrulesapiRuleResultMetadataV1
     */
    searchWindowEnd?: Date;
    /**
     *
     * @type {boolean}
     * @memberof CorrelationrulesapiRuleResultMetadataV1
     */
    useIngestTime?: boolean;
}

/**
 * Check if a given object implements the CorrelationrulesapiRuleResultMetadataV1 interface.
 */
export function instanceOfCorrelationrulesapiRuleResultMetadataV1(value: object): value is CorrelationrulesapiRuleResultMetadataV1 {
    return true;
}

export function CorrelationrulesapiRuleResultMetadataV1FromJSON(json: any): CorrelationrulesapiRuleResultMetadataV1 {
    return CorrelationrulesapiRuleResultMetadataV1FromJSONTyped(json, false);
}

export function CorrelationrulesapiRuleResultMetadataV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): CorrelationrulesapiRuleResultMetadataV1 {
    if (json == null) {
        return json;
    }
    return {
        executionDuration: json["execution_duration"] == null ? undefined : json["execution_duration"],
        executionFinish: json["execution_finish"] == null ? undefined : new Date(json["execution_finish"]),
        executionStart: json["execution_start"] == null ? undefined : new Date(json["execution_start"]),
        resultCount: json["result_count"] == null ? undefined : json["result_count"],
        searchWindowEnd: json["search_window_end"] == null ? undefined : new Date(json["search_window_end"]),
        useIngestTime: json["use_ingest_time"] == null ? undefined : json["use_ingest_time"],
    };
}

export function CorrelationrulesapiRuleResultMetadataV1ToJSON(value?: CorrelationrulesapiRuleResultMetadataV1 | null): any {
    if (value == null) {
        return value;
    }
    return {
        execution_duration: value["executionDuration"],
        execution_finish: value["executionFinish"] == null ? undefined : value["executionFinish"].toISOString(),
        execution_start: value["executionStart"] == null ? undefined : value["executionStart"].toISOString(),
        result_count: value["resultCount"],
        search_window_end: value["searchWindowEnd"] == null ? undefined : value["searchWindowEnd"].toISOString(),
        use_ingest_time: value["useIngestTime"],
    };
}
