/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface DeviceapiNetworkAddressV1
 */
export interface DeviceapiNetworkAddressV1 {
    /**
     *
     * @type {string}
     * @memberof DeviceapiNetworkAddressV1
     */
    ipAddress?: string;
    /**
     *
     * @type {string}
     * @memberof DeviceapiNetworkAddressV1
     */
    macAddress?: string;
    /**
     *
     * @type {string}
     * @memberof DeviceapiNetworkAddressV1
     */
    timestamp?: string;
}

/**
 * Check if a given object implements the DeviceapiNetworkAddressV1 interface.
 */
export function instanceOfDeviceapiNetworkAddressV1(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DeviceapiNetworkAddressV1FromJSON(json: any): DeviceapiNetworkAddressV1 {
    return DeviceapiNetworkAddressV1FromJSONTyped(json, false);
}

export function DeviceapiNetworkAddressV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceapiNetworkAddressV1 {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        ipAddress: !exists(json, "ip_address") ? undefined : json["ip_address"],
        macAddress: !exists(json, "mac_address") ? undefined : json["mac_address"],
        timestamp: !exists(json, "timestamp") ? undefined : json["timestamp"],
    };
}

export function DeviceapiNetworkAddressV1ToJSON(value?: DeviceapiNetworkAddressV1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ip_address: value.ipAddress,
        mac_address: value.macAddress,
        timestamp: value.timestamp,
    };
}
