/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface DevicecontrolapiUSBCustomNotification
 */
export interface DevicecontrolapiUSBCustomNotification {
    /**
     * Custom notification message text. Maximum length: 256 characters
     * @type {string}
     * @memberof DevicecontrolapiUSBCustomNotification
     */
    customMessage: string;
    /**
     *
     * @type {boolean}
     * @memberof DevicecontrolapiUSBCustomNotification
     */
    useCustom: boolean;
}

/**
 * Check if a given object implements the DevicecontrolapiUSBCustomNotification interface.
 */
export function instanceOfDevicecontrolapiUSBCustomNotification(value: object): value is DevicecontrolapiUSBCustomNotification {
    if (!("customMessage" in value) || value["customMessage"] === undefined) return false;
    if (!("useCustom" in value) || value["useCustom"] === undefined) return false;
    return true;
}

export function DevicecontrolapiUSBCustomNotificationFromJSON(json: any): DevicecontrolapiUSBCustomNotification {
    return DevicecontrolapiUSBCustomNotificationFromJSONTyped(json, false);
}

export function DevicecontrolapiUSBCustomNotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): DevicecontrolapiUSBCustomNotification {
    if (json == null) {
        return json;
    }
    return {
        customMessage: json["custom_message"],
        useCustom: json["use_custom"],
    };
}

export function DevicecontrolapiUSBCustomNotificationToJSON(value?: DevicecontrolapiUSBCustomNotification | null): any {
    if (value == null) {
        return value;
    }
    return {
        custom_message: value["customMessage"],
        use_custom: value["useCustom"],
    };
}
