/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { DomainExternalAssetDiscoveryAttributes } from "./DomainExternalAssetDiscoveryAttributes";
import {
    DomainExternalAssetDiscoveryAttributesFromJSON,
    DomainExternalAssetDiscoveryAttributesFromJSONTyped,
    DomainExternalAssetDiscoveryAttributesToJSON,
} from "./DomainExternalAssetDiscoveryAttributes";

/**
 *
 * @export
 * @interface DomainFemEcosystemSubsidiary
 */
export interface DomainFemEcosystemSubsidiary {
    /**
     * The number of assets associated with the subsidiary
     * @type {number}
     * @memberof DomainFemEcosystemSubsidiary
     */
    assetCount?: number;
    /**
     * The number of subsidiary children
     * @type {number}
     * @memberof DomainFemEcosystemSubsidiary
     */
    childrenCount: number;
    /**
     * The customer ID
     * @type {string}
     * @memberof DomainFemEcosystemSubsidiary
     */
    cid: string;
    /**
     *
     * @type {DomainExternalAssetDiscoveryAttributes}
     * @memberof DomainFemEcosystemSubsidiary
     */
    discovery?: DomainExternalAssetDiscoveryAttributes;
    /**
     * The ID of the subsidiary
     * @type {string}
     * @memberof DomainFemEcosystemSubsidiary
     */
    id: string;
    /**
     * The name of the subsidiary
     * @type {string}
     * @memberof DomainFemEcosystemSubsidiary
     */
    name: string;
    /**
     * The ID of the parent subsidiary
     * @type {string}
     * @memberof DomainFemEcosystemSubsidiary
     */
    parentId: string;
    /**
     * The primary domain of the subsidiary (Originally was called apex_domain)
     * @type {string}
     * @memberof DomainFemEcosystemSubsidiary
     */
    primaryDomain: string;
    /**
     * The risk score of the subsidiary
     * @type {number}
     * @memberof DomainFemEcosystemSubsidiary
     */
    riskScore?: number;
}

/**
 * Check if a given object implements the DomainFemEcosystemSubsidiary interface.
 */
export function instanceOfDomainFemEcosystemSubsidiary(value: object): value is DomainFemEcosystemSubsidiary {
    if (!("childrenCount" in value) || value["childrenCount"] === undefined) return false;
    if (!("cid" in value) || value["cid"] === undefined) return false;
    if (!("id" in value) || value["id"] === undefined) return false;
    if (!("name" in value) || value["name"] === undefined) return false;
    if (!("parentId" in value) || value["parentId"] === undefined) return false;
    if (!("primaryDomain" in value) || value["primaryDomain"] === undefined) return false;
    return true;
}

export function DomainFemEcosystemSubsidiaryFromJSON(json: any): DomainFemEcosystemSubsidiary {
    return DomainFemEcosystemSubsidiaryFromJSONTyped(json, false);
}

export function DomainFemEcosystemSubsidiaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainFemEcosystemSubsidiary {
    if (json == null) {
        return json;
    }
    return {
        assetCount: json["asset_count"] == null ? undefined : json["asset_count"],
        childrenCount: json["children_count"],
        cid: json["cid"],
        discovery: json["discovery"] == null ? undefined : DomainExternalAssetDiscoveryAttributesFromJSON(json["discovery"]),
        id: json["id"],
        name: json["name"],
        parentId: json["parent_id"],
        primaryDomain: json["primary_domain"],
        riskScore: json["risk_score"] == null ? undefined : json["risk_score"],
    };
}

export function DomainFemEcosystemSubsidiaryToJSON(value?: DomainFemEcosystemSubsidiary | null): any {
    if (value == null) {
        return value;
    }
    return {
        asset_count: value["assetCount"],
        children_count: value["childrenCount"],
        cid: value["cid"],
        discovery: DomainExternalAssetDiscoveryAttributesToJSON(value["discovery"]),
        id: value["id"],
        name: value["name"],
        parent_id: value["parentId"],
        primary_domain: value["primaryDomain"],
        risk_score: value["riskScore"],
    };
}
