/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { DomainAPIEvaluationLogicComparisonsV1 } from "./DomainAPIEvaluationLogicComparisonsV1";
import {
    DomainAPIEvaluationLogicComparisonsV1FromJSON,
    DomainAPIEvaluationLogicComparisonsV1FromJSONTyped,
    DomainAPIEvaluationLogicComparisonsV1ToJSON,
} from "./DomainAPIEvaluationLogicComparisonsV1";

/**
 *
 * @export
 * @interface DomainAPIEvaluationLogicItemV1
 */
export interface DomainAPIEvaluationLogicItemV1 {
    /**
     *
     * @type {string}
     * @memberof DomainAPIEvaluationLogicItemV1
     */
    comparisonCheck?: string;
    /**
     *
     * @type {DomainAPIEvaluationLogicComparisonsV1}
     * @memberof DomainAPIEvaluationLogicItemV1
     */
    comparisons?: DomainAPIEvaluationLogicComparisonsV1;
    /**
     *
     * @type {string}
     * @memberof DomainAPIEvaluationLogicItemV1
     */
    description?: string;
    /**
     *
     * @type {boolean}
     * @memberof DomainAPIEvaluationLogicItemV1
     */
    determinedByComparison?: boolean;
    /**
     *
     * @type {string}
     * @memberof DomainAPIEvaluationLogicItemV1
     */
    existenceCheck?: string;
    /**
     *
     * @type {number}
     * @memberof DomainAPIEvaluationLogicItemV1
     */
    id?: number;
    /**
     *
     * @type {Array<object>}
     * @memberof DomainAPIEvaluationLogicItemV1
     */
    items?: Array<object>;
    /**
     *
     * @type {boolean}
     * @memberof DomainAPIEvaluationLogicItemV1
     */
    negate?: boolean;
    /**
     *
     * @type {string}
     * @memberof DomainAPIEvaluationLogicItemV1
     */
    title: string;
    /**
     *
     * @type {string}
     * @memberof DomainAPIEvaluationLogicItemV1
     */
    type: string;
}

/**
 * Check if a given object implements the DomainAPIEvaluationLogicItemV1 interface.
 */
export function instanceOfDomainAPIEvaluationLogicItemV1(value: object): value is DomainAPIEvaluationLogicItemV1 {
    if (!("title" in value) || value["title"] === undefined) return false;
    if (!("type" in value) || value["type"] === undefined) return false;
    return true;
}

export function DomainAPIEvaluationLogicItemV1FromJSON(json: any): DomainAPIEvaluationLogicItemV1 {
    return DomainAPIEvaluationLogicItemV1FromJSONTyped(json, false);
}

export function DomainAPIEvaluationLogicItemV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainAPIEvaluationLogicItemV1 {
    if (json == null) {
        return json;
    }
    return {
        comparisonCheck: json["comparison_check"] == null ? undefined : json["comparison_check"],
        comparisons: json["comparisons"] == null ? undefined : DomainAPIEvaluationLogicComparisonsV1FromJSON(json["comparisons"]),
        description: json["description"] == null ? undefined : json["description"],
        determinedByComparison: json["determined_by_comparison"] == null ? undefined : json["determined_by_comparison"],
        existenceCheck: json["existence_check"] == null ? undefined : json["existence_check"],
        id: json["id"] == null ? undefined : json["id"],
        items: json["items"] == null ? undefined : json["items"],
        negate: json["negate"] == null ? undefined : json["negate"],
        title: json["title"],
        type: json["type"],
    };
}

export function DomainAPIEvaluationLogicItemV1ToJSON(value?: DomainAPIEvaluationLogicItemV1 | null): any {
    if (value == null) {
        return value;
    }
    return {
        comparison_check: value["comparisonCheck"],
        comparisons: DomainAPIEvaluationLogicComparisonsV1ToJSON(value["comparisons"]),
        description: value["description"],
        determined_by_comparison: value["determinedByComparison"],
        existence_check: value["existenceCheck"],
        id: value["id"],
        items: value["items"],
        negate: value["negate"],
        title: value["title"],
        type: value["type"],
    };
}
