/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface DomainDeployAgentsRequest
 */
export interface DomainDeployAgentsRequest {
    /**
     *
     * @type {Array<Array<number>>}
     * @memberof DomainDeployAgentsRequest
     */
    aids: Array<Array<number>>;
    /**
     *
     * @type {boolean}
     * @memberof DomainDeployAgentsRequest
     */
    noProxy?: boolean;
    /**
     *
     * @type {string}
     * @memberof DomainDeployAgentsRequest
     */
    proxyHost?: string;
    /**
     *
     * @type {number}
     * @memberof DomainDeployAgentsRequest
     */
    proxyPort?: number;
}

/**
 * Check if a given object implements the DomainDeployAgentsRequest interface.
 */
export function instanceOfDomainDeployAgentsRequest(value: object): value is DomainDeployAgentsRequest {
    if (!("aids" in value) || value["aids"] === undefined) return false;
    return true;
}

export function DomainDeployAgentsRequestFromJSON(json: any): DomainDeployAgentsRequest {
    return DomainDeployAgentsRequestFromJSONTyped(json, false);
}

export function DomainDeployAgentsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainDeployAgentsRequest {
    if (json == null) {
        return json;
    }
    return {
        aids: json["aids"],
        noProxy: json["no_proxy"] == null ? undefined : json["no_proxy"],
        proxyHost: json["proxy_host"] == null ? undefined : json["proxy_host"],
        proxyPort: json["proxy_port"] == null ? undefined : json["proxy_port"],
    };
}

export function DomainDeployAgentsRequestToJSON(value?: DomainDeployAgentsRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        aids: value["aids"],
        no_proxy: value["noProxy"],
        proxy_host: value["proxyHost"],
        proxy_port: value["proxyPort"],
    };
}
