/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { DomainProductFeatures } from "./DomainProductFeatures";
import { DomainProductFeaturesFromJSON, DomainProductFeaturesFromJSONTyped, DomainProductFeaturesToJSON } from "./DomainProductFeatures";
import type { DomainProductPermission } from "./DomainProductPermission";
import { DomainProductPermissionFromJSON, DomainProductPermissionFromJSONTyped, DomainProductPermissionToJSON } from "./DomainProductPermission";
import type { DomainCloudCondition } from "./DomainCloudCondition";
import { DomainCloudConditionFromJSON, DomainCloudConditionFromJSONTyped, DomainCloudConditionToJSON } from "./DomainCloudCondition";
import type { DomainProductFeaturesStatus } from "./DomainProductFeaturesStatus";
import { DomainProductFeaturesStatusFromJSON, DomainProductFeaturesStatusFromJSONTyped, DomainProductFeaturesStatusToJSON } from "./DomainProductFeaturesStatus";
import type { DomainAWSAccountResourceMetadata } from "./DomainAWSAccountResourceMetadata";
import { DomainAWSAccountResourceMetadataFromJSON, DomainAWSAccountResourceMetadataFromJSONTyped, DomainAWSAccountResourceMetadataToJSON } from "./DomainAWSAccountResourceMetadata";
import type { DomainAWSInventoryFilterSetting } from "./DomainAWSInventoryFilterSetting";
import { DomainAWSInventoryFilterSettingFromJSON, DomainAWSInventoryFilterSettingFromJSONTyped, DomainAWSInventoryFilterSettingToJSON } from "./DomainAWSInventoryFilterSetting";

/**
 *
 * @export
 * @interface DomainCloudAWSAccountV1
 */
export interface DomainCloudAWSAccountV1 {
    /**
     *
     * @type {Date}
     * @memberof DomainCloudAWSAccountV1
     */
    createdAt: Date;
    /**
     *
     * @type {Date}
     * @memberof DomainCloudAWSAccountV1
     */
    deletedAt: Date;
    /**
     *
     * @type {number}
     * @memberof DomainCloudAWSAccountV1
     */
    iD: number;
    /**
     *
     * @type {Date}
     * @memberof DomainCloudAWSAccountV1
     */
    updatedAt: Date;
    /**
     * 12 digit AWS provided unique identifier for the account.
     * @type {string}
     * @memberof DomainCloudAWSAccountV1
     */
    accountId?: string;
    /**
     * AWS account name
     * @type {string}
     * @memberof DomainCloudAWSAccountV1
     */
    accountName?: string;
    /**
     *
     * @type {string}
     * @memberof DomainCloudAWSAccountV1
     */
    accountType?: string;
    /**
     *
     * @type {Array<string>}
     * @memberof DomainCloudAWSAccountV1
     */
    activeRegions?: Array<string>;
    /**
     *
     * @type {string}
     * @memberof DomainCloudAWSAccountV1
     */
    cid?: string;
    /**
     *
     * @type {string}
     * @memberof DomainCloudAWSAccountV1
     */
    cloudformationStackArn?: string;
    /**
     *
     * @type {string}
     * @memberof DomainCloudAWSAccountV1
     */
    cloudformationUpdateUrl?: string;
    /**
     *
     * @type {string}
     * @memberof DomainCloudAWSAccountV1
     */
    cloudformationUrl?: string;
    /**
     *
     * @type {Array<DomainCloudCondition>}
     * @memberof DomainCloudAWSAccountV1
     */
    conditions?: Array<DomainCloudCondition>;
    /**
     * csp live events are enabled
     * @type {boolean}
     * @memberof DomainCloudAWSAccountV1
     */
    cspEvents?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof DomainCloudAWSAccountV1
     */
    cspmEnabled?: boolean;
    /**
     *
     * @type {string}
     * @memberof DomainCloudAWSAccountV1
     */
    environment?: string;
    /**
     *
     * @type {string}
     * @memberof DomainCloudAWSAccountV1
     */
    falconClientId?: string;
    /**
     * Permissions status for each product returned via API.
     * @type {Array<DomainProductPermission>}
     * @memberof DomainCloudAWSAccountV1
     */
    iamServicePermissionsStatus: Array<DomainProductPermission>;
    /**
     *
     * @type {Array<DomainAWSInventoryFilterSetting>}
     * @memberof DomainCloudAWSAccountV1
     */
    inventoryFilter: Array<DomainAWSInventoryFilterSetting>;
    /**
     * Is CSPM Lite enabled.
     * @type {boolean}
     * @memberof DomainCloudAWSAccountV1
     */
    isCspmLite?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof DomainCloudAWSAccountV1
     */
    isCustomRolename: boolean;
    /**
     *
     * @type {boolean}
     * @memberof DomainCloudAWSAccountV1
     */
    isDelegatedAdmin?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof DomainCloudAWSAccountV1
     */
    isMaster?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof DomainCloudAWSAccountV1
     */
    ngsiemEnabled?: boolean;
    /**
     * Up to 34 character AWS provided unique identifier for the organization.
     * @type {string}
     * @memberof DomainCloudAWSAccountV1
     */
    organizationId?: string;
    /**
     *
     * @type {Array<DomainProductFeatures>}
     * @memberof DomainCloudAWSAccountV1
     */
    products: Array<DomainProductFeatures>;
    /**
     *
     * @type {string}
     * @memberof DomainCloudAWSAccountV1
     */
    registrationStatus?: string;
    /**
     *
     * @type {string}
     * @memberof DomainCloudAWSAccountV1
     */
    remediationCloudformationUrl?: string;
    /**
     *
     * @type {DomainAWSAccountResourceMetadata}
     * @memberof DomainCloudAWSAccountV1
     */
    resourceMetadata: DomainAWSAccountResourceMetadata;
    /**
     *
     * @type {string}
     * @memberof DomainCloudAWSAccountV1
     */
    resourceNamePrefix?: string;
    /**
     *
     * @type {string}
     * @memberof DomainCloudAWSAccountV1
     */
    resourceNameSuffix?: string;
    /**
     * 12 digit AWS provided unique identifier for the root account (of the organization this account belongs to).
     * @type {string}
     * @memberof DomainCloudAWSAccountV1
     */
    rootAccountId?: string;
    /**
     *
     * @type {boolean}
     * @memberof DomainCloudAWSAccountV1
     */
    rootIamRole?: boolean;
    /**
     *
     * @type {string}
     * @memberof DomainCloudAWSAccountV1
     */
    s3Url?: string;
    /**
     *
     * @type {object}
     * @memberof DomainCloudAWSAccountV1
     */
    settings?: object;
    /**
     * Account registration status for each product and feature
     * @type {Array<DomainProductFeaturesStatus>}
     * @memberof DomainCloudAWSAccountV1
     */
    status?: Array<DomainProductFeaturesStatus>;
    /**
     *
     * @type {Array<string>}
     * @memberof DomainCloudAWSAccountV1
     */
    targetOus?: Array<string>;
    /**
     *
     * @type {string}
     * @memberof DomainCloudAWSAccountV1
     */
    templateSourceRegion?: string;
    /**
     *
     * @type {boolean}
     * @memberof DomainCloudAWSAccountV1
     */
    useExistingCloudtrail?: boolean;
}

/**
 * Check if a given object implements the DomainCloudAWSAccountV1 interface.
 */
export function instanceOfDomainCloudAWSAccountV1(value: object): value is DomainCloudAWSAccountV1 {
    if (!("createdAt" in value) || value["createdAt"] === undefined) return false;
    if (!("deletedAt" in value) || value["deletedAt"] === undefined) return false;
    if (!("iD" in value) || value["iD"] === undefined) return false;
    if (!("updatedAt" in value) || value["updatedAt"] === undefined) return false;
    if (!("iamServicePermissionsStatus" in value) || value["iamServicePermissionsStatus"] === undefined) return false;
    if (!("inventoryFilter" in value) || value["inventoryFilter"] === undefined) return false;
    if (!("isCustomRolename" in value) || value["isCustomRolename"] === undefined) return false;
    if (!("products" in value) || value["products"] === undefined) return false;
    if (!("resourceMetadata" in value) || value["resourceMetadata"] === undefined) return false;
    return true;
}

export function DomainCloudAWSAccountV1FromJSON(json: any): DomainCloudAWSAccountV1 {
    return DomainCloudAWSAccountV1FromJSONTyped(json, false);
}

export function DomainCloudAWSAccountV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainCloudAWSAccountV1 {
    if (json == null) {
        return json;
    }
    return {
        createdAt: new Date(json["CreatedAt"]),
        deletedAt: new Date(json["DeletedAt"]),
        iD: json["ID"],
        updatedAt: new Date(json["UpdatedAt"]),
        accountId: json["account_id"] == null ? undefined : json["account_id"],
        accountName: json["account_name"] == null ? undefined : json["account_name"],
        accountType: json["account_type"] == null ? undefined : json["account_type"],
        activeRegions: json["active_regions"] == null ? undefined : json["active_regions"],
        cid: json["cid"] == null ? undefined : json["cid"],
        cloudformationStackArn: json["cloudformation_stack_arn"] == null ? undefined : json["cloudformation_stack_arn"],
        cloudformationUpdateUrl: json["cloudformation_update_url"] == null ? undefined : json["cloudformation_update_url"],
        cloudformationUrl: json["cloudformation_url"] == null ? undefined : json["cloudformation_url"],
        conditions: json["conditions"] == null ? undefined : (json["conditions"] as Array<any>).map(DomainCloudConditionFromJSON),
        cspEvents: json["csp_events"] == null ? undefined : json["csp_events"],
        cspmEnabled: json["cspm_enabled"] == null ? undefined : json["cspm_enabled"],
        environment: json["environment"] == null ? undefined : json["environment"],
        falconClientId: json["falcon_client_id"] == null ? undefined : json["falcon_client_id"],
        iamServicePermissionsStatus: (json["iam_service_permissions_status"] as Array<any>).map(DomainProductPermissionFromJSON),
        inventoryFilter: (json["inventory_filter"] as Array<any>).map(DomainAWSInventoryFilterSettingFromJSON),
        isCspmLite: json["is_cspm_lite"] == null ? undefined : json["is_cspm_lite"],
        isCustomRolename: json["is_custom_rolename"],
        isDelegatedAdmin: json["is_delegated_admin"] == null ? undefined : json["is_delegated_admin"],
        isMaster: json["is_master"] == null ? undefined : json["is_master"],
        ngsiemEnabled: json["ngsiem_enabled"] == null ? undefined : json["ngsiem_enabled"],
        organizationId: json["organization_id"] == null ? undefined : json["organization_id"],
        products: (json["products"] as Array<any>).map(DomainProductFeaturesFromJSON),
        registrationStatus: json["registration_status"] == null ? undefined : json["registration_status"],
        remediationCloudformationUrl: json["remediation_cloudformation_url"] == null ? undefined : json["remediation_cloudformation_url"],
        resourceMetadata: DomainAWSAccountResourceMetadataFromJSON(json["resource_metadata"]),
        resourceNamePrefix: json["resource_name_prefix"] == null ? undefined : json["resource_name_prefix"],
        resourceNameSuffix: json["resource_name_suffix"] == null ? undefined : json["resource_name_suffix"],
        rootAccountId: json["root_account_id"] == null ? undefined : json["root_account_id"],
        rootIamRole: json["root_iam_role"] == null ? undefined : json["root_iam_role"],
        s3Url: json["s3_url"] == null ? undefined : json["s3_url"],
        settings: json["settings"] == null ? undefined : json["settings"],
        status: json["status"] == null ? undefined : (json["status"] as Array<any>).map(DomainProductFeaturesStatusFromJSON),
        targetOus: json["target_ous"] == null ? undefined : json["target_ous"],
        templateSourceRegion: json["template_source_region"] == null ? undefined : json["template_source_region"],
        useExistingCloudtrail: json["use_existing_cloudtrail"] == null ? undefined : json["use_existing_cloudtrail"],
    };
}

export function DomainCloudAWSAccountV1ToJSON(value?: DomainCloudAWSAccountV1 | null): any {
    if (value == null) {
        return value;
    }
    return {
        CreatedAt: value["createdAt"].toISOString(),
        DeletedAt: value["deletedAt"].toISOString(),
        ID: value["iD"],
        UpdatedAt: value["updatedAt"].toISOString(),
        account_id: value["accountId"],
        account_name: value["accountName"],
        account_type: value["accountType"],
        active_regions: value["activeRegions"],
        cid: value["cid"],
        cloudformation_stack_arn: value["cloudformationStackArn"],
        cloudformation_update_url: value["cloudformationUpdateUrl"],
        cloudformation_url: value["cloudformationUrl"],
        conditions: value["conditions"] == null ? undefined : (value["conditions"] as Array<any>).map(DomainCloudConditionToJSON),
        csp_events: value["cspEvents"],
        cspm_enabled: value["cspmEnabled"],
        environment: value["environment"],
        falcon_client_id: value["falconClientId"],
        iam_service_permissions_status: (value["iamServicePermissionsStatus"] as Array<any>).map(DomainProductPermissionToJSON),
        inventory_filter: (value["inventoryFilter"] as Array<any>).map(DomainAWSInventoryFilterSettingToJSON),
        is_cspm_lite: value["isCspmLite"],
        is_custom_rolename: value["isCustomRolename"],
        is_delegated_admin: value["isDelegatedAdmin"],
        is_master: value["isMaster"],
        ngsiem_enabled: value["ngsiemEnabled"],
        organization_id: value["organizationId"],
        products: (value["products"] as Array<any>).map(DomainProductFeaturesToJSON),
        registration_status: value["registrationStatus"],
        remediation_cloudformation_url: value["remediationCloudformationUrl"],
        resource_metadata: DomainAWSAccountResourceMetadataToJSON(value["resourceMetadata"]),
        resource_name_prefix: value["resourceNamePrefix"],
        resource_name_suffix: value["resourceNameSuffix"],
        root_account_id: value["rootAccountId"],
        root_iam_role: value["rootIamRole"],
        s3_url: value["s3Url"],
        settings: value["settings"],
        status: value["status"] == null ? undefined : (value["status"] as Array<any>).map(DomainProductFeaturesStatusToJSON),
        target_ous: value["targetOus"],
        template_source_region: value["templateSourceRegion"],
        use_existing_cloudtrail: value["useExistingCloudtrail"],
    };
}
