/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { DomainProductFeatureStatus } from "./DomainProductFeatureStatus";
import { DomainProductFeatureStatusFromJSON, DomainProductFeatureStatusFromJSONTyped, DomainProductFeatureStatusToJSON } from "./DomainProductFeatureStatus";

/**
 *
 * @export
 * @interface DomainOCITenancyValidated
 */
export interface DomainOCITenancyValidated {
    /**
     *
     * @type {string}
     * @memberof DomainOCITenancyValidated
     */
    cid: string;
    /**
     * Region of OCI Account/Tenancy
     * @type {string}
     * @memberof DomainOCITenancyValidated
     */
    homeRegion: string;
    /**
     * OCI Tenancy Registration status
     * @type {string}
     * @memberof DomainOCITenancyValidated
     */
    overallStatus: string;
    /**
     * Tenancy registration details for each product and feature
     * @type {{ [key: string]: { [key: string]: DomainProductFeatureStatus; }; }}
     * @memberof DomainOCITenancyValidated
     */
    products: { [key: string]: { [key: string]: DomainProductFeatureStatus } };
    /**
     *
     * @type {string}
     * @memberof DomainOCITenancyValidated
     */
    tenancyOcid: string;
}

/**
 * Check if a given object implements the DomainOCITenancyValidated interface.
 */
export function instanceOfDomainOCITenancyValidated(value: object): value is DomainOCITenancyValidated {
    if (!("cid" in value) || value["cid"] === undefined) return false;
    if (!("homeRegion" in value) || value["homeRegion"] === undefined) return false;
    if (!("overallStatus" in value) || value["overallStatus"] === undefined) return false;
    if (!("products" in value) || value["products"] === undefined) return false;
    if (!("tenancyOcid" in value) || value["tenancyOcid"] === undefined) return false;
    return true;
}

export function DomainOCITenancyValidatedFromJSON(json: any): DomainOCITenancyValidated {
    return DomainOCITenancyValidatedFromJSONTyped(json, false);
}

export function DomainOCITenancyValidatedFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainOCITenancyValidated {
    if (json == null) {
        return json;
    }
    return {
        cid: json["cid"],
        homeRegion: json["home_region"],
        overallStatus: json["overall_status"],
        products: json["products"],
        tenancyOcid: json["tenancy_ocid"],
    };
}

export function DomainOCITenancyValidatedToJSON(value?: DomainOCITenancyValidated | null): any {
    if (value == null) {
        return value;
    }
    return {
        cid: value["cid"],
        home_region: value["homeRegion"],
        overall_status: value["overallStatus"],
        products: value["products"],
        tenancy_ocid: value["tenancyOcid"],
    };
}
