/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface DomainAPIRemediationInfo
 */
export interface DomainAPIRemediationInfo {
    /**
     * Contains the ID of the minimum remediation
     * @type {string}
     * @memberof DomainAPIRemediationInfo
     */
    minimumId?: string;
    /**
     * Contains the timestamp when earliest remediation was published
     * @type {string}
     * @memberof DomainAPIRemediationInfo
     */
    patchPublicationDate?: string;
    /**
     * Contains the ID of the recommended remediation
     * @type {string}
     * @memberof DomainAPIRemediationInfo
     */
    recommendedId?: string;
}

/**
 * Check if a given object implements the DomainAPIRemediationInfo interface.
 */
export function instanceOfDomainAPIRemediationInfo(value: object): value is DomainAPIRemediationInfo {
    return true;
}

export function DomainAPIRemediationInfoFromJSON(json: any): DomainAPIRemediationInfo {
    return DomainAPIRemediationInfoFromJSONTyped(json, false);
}

export function DomainAPIRemediationInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainAPIRemediationInfo {
    if (json == null) {
        return json;
    }
    return {
        minimumId: json["minimum_id"] == null ? undefined : json["minimum_id"],
        patchPublicationDate: json["patch_publication_date"] == null ? undefined : json["patch_publication_date"],
        recommendedId: json["recommended_id"] == null ? undefined : json["recommended_id"],
    };
}

export function DomainAPIRemediationInfoToJSON(value?: DomainAPIRemediationInfo | null): any {
    if (value == null) {
        return value;
    }
    return {
        minimum_id: value["minimumId"],
        patch_publication_date: value["patchPublicationDate"],
        recommended_id: value["recommendedId"],
    };
}
