/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface FigapiIPv6
 */
export interface FigapiIPv6 {
    /**
     * An array of Autonomous System Numbers (ASNs)
     * @type {Array<number>}
     * @memberof FigapiIPv6
     */
    aSN?: Array<number>;
    /**
     * This can be one of: `AdversaryControlled`, `CDN`, `PublicDNSResolver`, `CaptivePortal`, `DNSSinkhole`, `DNSRootServer`, `HoneypotHoneypot`, etc.
     * @type {Array<string>}
     * @memberof FigapiIPv6
     */
    iPProperties?: Array<string>;
    /**
     * The IPv6 address as a string
     * @type {string}
     * @memberof FigapiIPv6
     */
    iPv6?: string;
    /**
     * Internet service provider
     * @type {string}
     * @memberof FigapiIPv6
     */
    iSP?: string;
}

/**
 * Check if a given object implements the FigapiIPv6 interface.
 */
export function instanceOfFigapiIPv6(value: object): value is FigapiIPv6 {
    return true;
}

export function FigapiIPv6FromJSON(json: any): FigapiIPv6 {
    return FigapiIPv6FromJSONTyped(json, false);
}

export function FigapiIPv6FromJSONTyped(json: any, ignoreDiscriminator: boolean): FigapiIPv6 {
    if (json == null) {
        return json;
    }
    return {
        aSN: json["ASN"] == null ? undefined : json["ASN"],
        iPProperties: json["IPProperties"] == null ? undefined : json["IPProperties"],
        iPv6: json["IPv6"] == null ? undefined : json["IPv6"],
        iSP: json["ISP"] == null ? undefined : json["ISP"],
    };
}

export function FigapiIPv6ToJSON(value?: FigapiIPv6 | null): any {
    if (value == null) {
        return value;
    }
    return {
        ASN: value["aSN"],
        IPProperties: value["iPProperties"],
        IPv6: value["iPv6"],
        ISP: value["iSP"],
    };
}
