/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FwmgrApiFilepathTestResult
 */
export interface FwmgrApiFilepathTestResult {
    /**
     * 
     * @type {string}
     * @memberof FwmgrApiFilepathTestResult
     */
    filepathPattern: string;
    /**
     * 
     * @type {string}
     * @memberof FwmgrApiFilepathTestResult
     */
    filepathTestString: string;
    /**
     * 
     * @type {boolean}
     * @memberof FwmgrApiFilepathTestResult
     */
    isMatch: boolean;
}

/**
 * Check if a given object implements the FwmgrApiFilepathTestResult interface.
 */
export function instanceOfFwmgrApiFilepathTestResult(value: object): value is FwmgrApiFilepathTestResult {
    if (!('filepathPattern' in value) || value['filepathPattern'] === undefined) return false;
    if (!('filepathTestString' in value) || value['filepathTestString'] === undefined) return false;
    if (!('isMatch' in value) || value['isMatch'] === undefined) return false;
    return true;
}

export function FwmgrApiFilepathTestResultFromJSON(json: any): FwmgrApiFilepathTestResult {
    return FwmgrApiFilepathTestResultFromJSONTyped(json, false);
}

export function FwmgrApiFilepathTestResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): FwmgrApiFilepathTestResult {
    if (json == null) {
        return json;
    }
    return {
        
        'filepathPattern': json['filepath_pattern'],
        'filepathTestString': json['filepath_test_string'],
        'isMatch': json['is_match'],
    };
}

export function FwmgrApiFilepathTestResultToJSON(value?: FwmgrApiFilepathTestResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'filepath_pattern': value['filepathPattern'],
        'filepath_test_string': value['filepathTestString'],
        'is_match': value['isMatch'],
    };
}

