/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and more information about API endpoints that don\'t yet support OAuth2, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation). To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`. Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 * A host group which targets a set of devices either through a dynamic assignment rule or a static set of hosts
 * @export
 * @interface HostGroupsHostGroupV1
 */
export interface HostGroupsHostGroupV1 {
    /**
     * The assignment rule of a group
     * @type {string}
     * @memberof HostGroupsHostGroupV1
     */
    assignmentRule?: string;
    /**
     * The email of the user which created the policy
     * @type {string}
     * @memberof HostGroupsHostGroupV1
     */
    createdBy: string;
    /**
     * The time at which the policy was created
     * @type {Date}
     * @memberof HostGroupsHostGroupV1
     */
    createdTimestamp: Date;
    /**
     * An additional description of the group or the devices it targets
     * @type {string}
     * @memberof HostGroupsHostGroupV1
     */
    description: string;
    /**
     * The method by which this host group is managed
     * @type {string}
     * @memberof HostGroupsHostGroupV1
     */
    groupType?: HostGroupsHostGroupV1GroupTypeEnum;
    /**
     * The identifier of this host group
     * @type {string}
     * @memberof HostGroupsHostGroupV1
     */
    id: string;
    /**
     * The email of the user which last modified the policy
     * @type {string}
     * @memberof HostGroupsHostGroupV1
     */
    modifiedBy: string;
    /**
     * The time at which the policy was last modified
     * @type {Date}
     * @memberof HostGroupsHostGroupV1
     */
    modifiedTimestamp: Date;
    /**
     * The name of the group
     * @type {string}
     * @memberof HostGroupsHostGroupV1
     */
    name: string;
}

/**
 * @export
 */
export const HostGroupsHostGroupV1GroupTypeEnum = {
    Static: "static",
    Dynamic: "dynamic",
    StaticById: "staticByID",
} as const;
export type HostGroupsHostGroupV1GroupTypeEnum = (typeof HostGroupsHostGroupV1GroupTypeEnum)[keyof typeof HostGroupsHostGroupV1GroupTypeEnum];

/**
 * Check if a given object implements the HostGroupsHostGroupV1 interface.
 */
export function instanceOfHostGroupsHostGroupV1(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "createdBy" in value;
    isInstance = isInstance && "createdTimestamp" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "modifiedBy" in value;
    isInstance = isInstance && "modifiedTimestamp" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function HostGroupsHostGroupV1FromJSON(json: any): HostGroupsHostGroupV1 {
    return HostGroupsHostGroupV1FromJSONTyped(json, false);
}

export function HostGroupsHostGroupV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): HostGroupsHostGroupV1 {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        assignmentRule: !exists(json, "assignment_rule") ? undefined : json["assignment_rule"],
        createdBy: json["created_by"],
        createdTimestamp: new Date(json["created_timestamp"]),
        description: json["description"],
        groupType: !exists(json, "group_type") ? undefined : json["group_type"],
        id: json["id"],
        modifiedBy: json["modified_by"],
        modifiedTimestamp: new Date(json["modified_timestamp"]),
        name: json["name"],
    };
}

export function HostGroupsHostGroupV1ToJSON(value?: HostGroupsHostGroupV1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        assignment_rule: value.assignmentRule,
        created_by: value.createdBy,
        created_timestamp: value.createdTimestamp.toISOString(),
        description: value.description,
        group_type: value.groupType,
        id: value.id,
        modified_by: value.modifiedBy,
        modified_timestamp: value.modifiedTimestamp.toISOString(),
        name: value.name,
    };
}
