/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ItautomationUpdatePoliciesHostGroupsRequest
 */
export interface ItautomationUpdatePoliciesHostGroupsRequest {
    /**
     * The action to perform with the provided ids, must be one of: assign, unassign.
     * @type {string}
     * @memberof ItautomationUpdatePoliciesHostGroupsRequest
     */
    action: string;
    /**
     * The ids of the host groups on which to perform the action.
     * @type {Array<string>}
     * @memberof ItautomationUpdatePoliciesHostGroupsRequest
     */
    hostGroupIds: Array<string>;
    /**
     * The id of the policy on which to perform the action.
     * @type {string}
     * @memberof ItautomationUpdatePoliciesHostGroupsRequest
     */
    policyId: string;
}

/**
 * Check if a given object implements the ItautomationUpdatePoliciesHostGroupsRequest interface.
 */
export function instanceOfItautomationUpdatePoliciesHostGroupsRequest(value: object): value is ItautomationUpdatePoliciesHostGroupsRequest {
    if (!("action" in value) || value["action"] === undefined) return false;
    if (!("hostGroupIds" in value) || value["hostGroupIds"] === undefined) return false;
    if (!("policyId" in value) || value["policyId"] === undefined) return false;
    return true;
}

export function ItautomationUpdatePoliciesHostGroupsRequestFromJSON(json: any): ItautomationUpdatePoliciesHostGroupsRequest {
    return ItautomationUpdatePoliciesHostGroupsRequestFromJSONTyped(json, false);
}

export function ItautomationUpdatePoliciesHostGroupsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItautomationUpdatePoliciesHostGroupsRequest {
    if (json == null) {
        return json;
    }
    return {
        action: json["action"],
        hostGroupIds: json["host_group_ids"],
        policyId: json["policy_id"],
    };
}

export function ItautomationUpdatePoliciesHostGroupsRequestToJSON(value?: ItautomationUpdatePoliciesHostGroupsRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        action: value["action"],
        host_group_ids: value["hostGroupIds"],
        policy_id: value["policyId"],
    };
}
