/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { FalconforitapiSchedule } from "./FalconforitapiSchedule";
import { FalconforitapiScheduleFromJSON, FalconforitapiScheduleFromJSONTyped, FalconforitapiScheduleToJSON } from "./FalconforitapiSchedule";
import type { FalconforitapiConditionGroup } from "./FalconforitapiConditionGroup";
import { FalconforitapiConditionGroupFromJSON, FalconforitapiConditionGroupFromJSONTyped, FalconforitapiConditionGroupToJSON } from "./FalconforitapiConditionGroup";
import type { FalconforitapiGuardrails } from "./FalconforitapiGuardrails";
import { FalconforitapiGuardrailsFromJSON, FalconforitapiGuardrailsFromJSONTyped, FalconforitapiGuardrailsToJSON } from "./FalconforitapiGuardrails";

/**
 *
 * @export
 * @interface ItautomationCreateScheduledTaskRequest
 */
export interface ItautomationCreateScheduledTaskRequest {
    /**
     * Whether to discover new hosts for the scheduled task. Example: true
     * @type {boolean}
     * @memberof ItautomationCreateScheduledTaskRequest
     */
    discoverNewHosts?: boolean;
    /**
     * Whether to discover offline hosts for the scheduled task. Example: true
     * @type {boolean}
     * @memberof ItautomationCreateScheduledTaskRequest
     */
    discoverOfflineHosts?: boolean;
    /**
     * Whether to distribute the scheduled task. Example: true
     * @type {boolean}
     * @memberof ItautomationCreateScheduledTaskRequest
     */
    distribute?: boolean;
    /**
     * Additional arguments for the scheduled task. Example: {"state": "running"}
     * @type {{ [key: string]: string; }}
     * @memberof ItautomationCreateScheduledTaskRequest
     */
    executionArgs?: { [key: string]: string };
    /**
     *  Duration for which the task stays active. Once expired, new and offline hosts won't be targeted. Example: 1m
     * @type {string}
     * @memberof ItautomationCreateScheduledTaskRequest
     */
    expirationInterval?: string;
    /**
     *
     * @type {FalconforitapiGuardrails}
     * @memberof ItautomationCreateScheduledTaskRequest
     */
    guardrails?: FalconforitapiGuardrails;
    /**
     * Whether the scheduled task is active. Example: true
     * @type {boolean}
     * @memberof ItautomationCreateScheduledTaskRequest
     */
    isActive: boolean;
    /**
     *
     * @type {FalconforitapiSchedule}
     * @memberof ItautomationCreateScheduledTaskRequest
     */
    schedule: FalconforitapiSchedule;
    /**
     * Custom name for the scheduled task. Example: Weekly Security Scan
     * @type {string}
     * @memberof ItautomationCreateScheduledTaskRequest
     */
    scheduleName?: string;
    /**
     * Filter expression to select target hosts. Example: platform_name:'Windows'
     * @type {string}
     * @memberof ItautomationCreateScheduledTaskRequest
     */
    target: string;
    /**
     * Unique identifier of the task to be scheduled. Example: f64b95555ef54ea682619ce880d267cc
     * @type {string}
     * @memberof ItautomationCreateScheduledTaskRequest
     */
    taskId: string;
    /**
     * Conditions that trigger remediation actions
     * @type {Array<FalconforitapiConditionGroup>}
     * @memberof ItautomationCreateScheduledTaskRequest
     */
    triggerCondition?: Array<FalconforitapiConditionGroup>;
}

/**
 * Check if a given object implements the ItautomationCreateScheduledTaskRequest interface.
 */
export function instanceOfItautomationCreateScheduledTaskRequest(value: object): value is ItautomationCreateScheduledTaskRequest {
    if (!("isActive" in value) || value["isActive"] === undefined) return false;
    if (!("schedule" in value) || value["schedule"] === undefined) return false;
    if (!("target" in value) || value["target"] === undefined) return false;
    if (!("taskId" in value) || value["taskId"] === undefined) return false;
    return true;
}

export function ItautomationCreateScheduledTaskRequestFromJSON(json: any): ItautomationCreateScheduledTaskRequest {
    return ItautomationCreateScheduledTaskRequestFromJSONTyped(json, false);
}

export function ItautomationCreateScheduledTaskRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItautomationCreateScheduledTaskRequest {
    if (json == null) {
        return json;
    }
    return {
        discoverNewHosts: json["discover_new_hosts"] == null ? undefined : json["discover_new_hosts"],
        discoverOfflineHosts: json["discover_offline_hosts"] == null ? undefined : json["discover_offline_hosts"],
        distribute: json["distribute"] == null ? undefined : json["distribute"],
        executionArgs: json["execution_args"] == null ? undefined : json["execution_args"],
        expirationInterval: json["expiration_interval"] == null ? undefined : json["expiration_interval"],
        guardrails: json["guardrails"] == null ? undefined : FalconforitapiGuardrailsFromJSON(json["guardrails"]),
        isActive: json["is_active"],
        schedule: FalconforitapiScheduleFromJSON(json["schedule"]),
        scheduleName: json["schedule_name"] == null ? undefined : json["schedule_name"],
        target: json["target"],
        taskId: json["task_id"],
        triggerCondition: json["trigger_condition"] == null ? undefined : (json["trigger_condition"] as Array<any>).map(FalconforitapiConditionGroupFromJSON),
    };
}

export function ItautomationCreateScheduledTaskRequestToJSON(value?: ItautomationCreateScheduledTaskRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        discover_new_hosts: value["discoverNewHosts"],
        discover_offline_hosts: value["discoverOfflineHosts"],
        distribute: value["distribute"],
        execution_args: value["executionArgs"],
        expiration_interval: value["expirationInterval"],
        guardrails: FalconforitapiGuardrailsToJSON(value["guardrails"]),
        is_active: value["isActive"],
        schedule: FalconforitapiScheduleToJSON(value["schedule"]),
        schedule_name: value["scheduleName"],
        target: value["target"],
        task_id: value["taskId"],
        trigger_condition: value["triggerCondition"] == null ? undefined : (value["triggerCondition"] as Array<any>).map(FalconforitapiConditionGroupToJSON),
    };
}
