/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { FalconforitapiGuardrails } from "./FalconforitapiGuardrails";
import { FalconforitapiGuardrailsFromJSON, FalconforitapiGuardrailsFromJSONTyped, FalconforitapiGuardrailsToJSON } from "./FalconforitapiGuardrails";
import type { ItautomationScripts } from "./ItautomationScripts";
import { ItautomationScriptsFromJSON, ItautomationScriptsFromJSONTyped, ItautomationScriptsToJSON } from "./ItautomationScripts";
import type { ItautomationOutputParserConfig } from "./ItautomationOutputParserConfig";
import { ItautomationOutputParserConfigFromJSON, ItautomationOutputParserConfigFromJSONTyped, ItautomationOutputParserConfigToJSON } from "./ItautomationOutputParserConfig";
import type { ItautomationCompositeQuery } from "./ItautomationCompositeQuery";
import { ItautomationCompositeQueryFromJSON, ItautomationCompositeQueryFromJSONTyped, ItautomationCompositeQueryToJSON } from "./ItautomationCompositeQuery";
import type { ItautomationRowsParserConfig } from "./ItautomationRowsParserConfig";
import { ItautomationRowsParserConfigFromJSON, ItautomationRowsParserConfigFromJSONTyped, ItautomationRowsParserConfigToJSON } from "./ItautomationRowsParserConfig";

/**
 *
 * @export
 * @interface ItautomationRunLiveQueryRequest
 */
export interface ItautomationRunLiveQueryRequest {
    /**
     *
     * @type {ItautomationCompositeQuery}
     * @memberof ItautomationRunLiveQueryRequest
     */
    compositeQuery?: ItautomationCompositeQuery;
    /**
     * Whether to discover new hosts for the scheduled task. Example: true
     * @type {boolean}
     * @memberof ItautomationRunLiveQueryRequest
     */
    discoverNewHosts?: boolean;
    /**
     * Whether to discover offline hosts for the scheduled task. Example: true
     * @type {boolean}
     * @memberof ItautomationRunLiveQueryRequest
     */
    discoverOfflineHosts?: boolean;
    /**
     * Whether to distribute the scheduled task. Example: true
     * @type {boolean}
     * @memberof ItautomationRunLiveQueryRequest
     */
    distribute?: boolean;
    /**
     *  Duration for which the task stays active. Once expired, new and offline hosts won't be targeted. Example: 1m
     * @type {string}
     * @memberof ItautomationRunLiveQueryRequest
     */
    expirationInterval?: string;
    /**
     *
     * @type {FalconforitapiGuardrails}
     * @memberof ItautomationRunLiveQueryRequest
     */
    guardrails?: FalconforitapiGuardrails;
    /**
     * OSQuery to execute. Example: select * from users
     * @type {string}
     * @memberof ItautomationRunLiveQueryRequest
     */
    osquery?: string;
    /**
     *
     * @type {ItautomationOutputParserConfig}
     * @memberof ItautomationRunLiveQueryRequest
     */
    outputParserConfig?: ItautomationOutputParserConfig;
    /**
     *
     * @type {ItautomationScripts}
     * @memberof ItautomationRunLiveQueryRequest
     */
    queries?: ItautomationScripts;
    /**
     *
     * @type {ItautomationRowsParserConfig}
     * @memberof ItautomationRunLiveQueryRequest
     */
    rowsParserConfig?: ItautomationRowsParserConfig;
    /**
     * Target filter in FQL format. Example: platform_name: 'Windows'
     * @type {string}
     * @memberof ItautomationRunLiveQueryRequest
     */
    target: string;
}

/**
 * Check if a given object implements the ItautomationRunLiveQueryRequest interface.
 */
export function instanceOfItautomationRunLiveQueryRequest(value: object): value is ItautomationRunLiveQueryRequest {
    if (!("target" in value) || value["target"] === undefined) return false;
    return true;
}

export function ItautomationRunLiveQueryRequestFromJSON(json: any): ItautomationRunLiveQueryRequest {
    return ItautomationRunLiveQueryRequestFromJSONTyped(json, false);
}

export function ItautomationRunLiveQueryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ItautomationRunLiveQueryRequest {
    if (json == null) {
        return json;
    }
    return {
        compositeQuery: json["composite_query"] == null ? undefined : ItautomationCompositeQueryFromJSON(json["composite_query"]),
        discoverNewHosts: json["discover_new_hosts"] == null ? undefined : json["discover_new_hosts"],
        discoverOfflineHosts: json["discover_offline_hosts"] == null ? undefined : json["discover_offline_hosts"],
        distribute: json["distribute"] == null ? undefined : json["distribute"],
        expirationInterval: json["expiration_interval"] == null ? undefined : json["expiration_interval"],
        guardrails: json["guardrails"] == null ? undefined : FalconforitapiGuardrailsFromJSON(json["guardrails"]),
        osquery: json["osquery"] == null ? undefined : json["osquery"],
        outputParserConfig: json["output_parser_config"] == null ? undefined : ItautomationOutputParserConfigFromJSON(json["output_parser_config"]),
        queries: json["queries"] == null ? undefined : ItautomationScriptsFromJSON(json["queries"]),
        rowsParserConfig: json["rows_parser_config"] == null ? undefined : ItautomationRowsParserConfigFromJSON(json["rows_parser_config"]),
        target: json["target"],
    };
}

export function ItautomationRunLiveQueryRequestToJSON(value?: ItautomationRunLiveQueryRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        composite_query: ItautomationCompositeQueryToJSON(value["compositeQuery"]),
        discover_new_hosts: value["discoverNewHosts"],
        discover_offline_hosts: value["discoverOfflineHosts"],
        distribute: value["distribute"],
        expiration_interval: value["expirationInterval"],
        guardrails: FalconforitapiGuardrailsToJSON(value["guardrails"]),
        osquery: value["osquery"],
        output_parser_config: ItautomationOutputParserConfigToJSON(value["outputParserConfig"]),
        queries: ItautomationScriptsToJSON(value["queries"]),
        rows_parser_config: ItautomationRowsParserConfigToJSON(value["rowsParserConfig"]),
        target: value["target"],
    };
}
