/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { PaginationMetaGetTransactionStatus } from "./PaginationMetaGetTransactionStatus";
import { PaginationMetaGetTransactionStatusFromJSON, PaginationMetaGetTransactionStatusFromJSONTyped, PaginationMetaGetTransactionStatusToJSON } from "./PaginationMetaGetTransactionStatus";

/**
 *
 * @export
 * @interface MetaGetTransactionStatus
 */
export interface MetaGetTransactionStatus {
    /**
     *
     * @type {PaginationMetaGetTransactionStatus}
     * @memberof MetaGetTransactionStatus
     */
    pagination?: PaginationMetaGetTransactionStatus | null;
    /**
     *
     * @type {number}
     * @memberof MetaGetTransactionStatus
     */
    queryTime?: number | null;
    /**
     *
     * @type {string}
     * @memberof MetaGetTransactionStatus
     */
    traceId?: string | null;
}

/**
 * Check if a given object implements the MetaGetTransactionStatus interface.
 */
export function instanceOfMetaGetTransactionStatus(value: object): value is MetaGetTransactionStatus {
    return true;
}

export function MetaGetTransactionStatusFromJSON(json: any): MetaGetTransactionStatus {
    return MetaGetTransactionStatusFromJSONTyped(json, false);
}

export function MetaGetTransactionStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetaGetTransactionStatus {
    if (json == null) {
        return json;
    }
    return {
        pagination: json["pagination"] == null ? undefined : PaginationMetaGetTransactionStatusFromJSON(json["pagination"]),
        queryTime: json["query_time"] == null ? undefined : json["query_time"],
        traceId: json["trace_id"] == null ? undefined : json["trace_id"],
    };
}

export function MetaGetTransactionStatusToJSON(value?: MetaGetTransactionStatus | null): any {
    if (value == null) {
        return value;
    }
    return {
        pagination: PaginationMetaGetTransactionStatusToJSON(value["pagination"]),
        query_time: value["queryTime"],
        trace_id: value["traceId"],
    };
}
