/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelsContainer
 */
export interface ModelsContainer {
    /**
     * 
     * @type {Array<{ [key: string]: string; }>}
     * @memberof ModelsContainer
     */
    agents?: Array<{ [key: string]: string; }>;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsContainer
     */
    allowPrivilegeEscalation?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    cid: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    cloud?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    cloudAccountId?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    cloudRegion?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    clusterId?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    clusterName?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    configLabels?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    configUser?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    containerImageId?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsContainer
     */
    createdAt?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ModelsContainer
     */
    cveIds?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    firstSeen?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    hostConfigDevices?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsContainer
     */
    imageApplicationPackageCount?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsContainer
     */
    imageAssessedAt?: number;
    /**
     * 
     * @type {number}
     * @memberof ModelsContainer
     */
    imageDetectionCount?: number;
    /**
     * 
     * @type {Array<string>}
     * @memberof ModelsContainer
     */
    imageDetectionIdList?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ModelsContainer
     */
    imageDetectionNameList?: Array<string>;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof ModelsContainer
     */
    imageDetectionSeverityByType?: { [key: string]: number; };
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    imageDigest?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsContainer
     */
    imageHasBeenAssessed?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    imageHighestSeverityVulnerability?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    imageId?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsContainer
     */
    imagePackageCount?: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    imageRegistry?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    imageRepo?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    imageTag?: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsContainer
     */
    imageVulnerabilityCount?: number;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof ModelsContainer
     */
    imageVulnerabilitySeverityByType?: { [key: string]: number; };
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    insecureMountSource?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    insecureMountType?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsContainer
     */
    insecurePropagationMode?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsContainer
     */
    interactiveMode?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    ipv4?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    ipv6?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsContainer
     */
    kpaCoverage?: boolean;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ModelsContainer
     */
    labels?: { [key: string]: string; };
    /**
     * 
     * @type {Array<string>}
     * @memberof ModelsContainer
     */
    labelsList?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    lastSeen?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    linuxSensorAid?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    linuxSensorConfigBuild?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsContainer
     */
    linuxSensorCoverage?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    lumosSensorAid?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    lumosSensorConfigBuild?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsContainer
     */
    lumosSensorCoverage?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    namespace?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    nodeId?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    nodeName?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    podId?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    podName?: string;
    /**
     * 
     * @type {Array<{ [key: string]: string; }>}
     * @memberof ModelsContainer
     */
    portList?: Array<{ [key: string]: string; }>;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsContainer
     */
    privileged?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsContainer
     */
    rootWriteAccess?: boolean;
    /**
     * 
     * @type {Array<number>}
     * @memberof ModelsContainer
     */
    rpd?: Array<number>;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsContainer
     */
    runAsRootGroup?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsContainer
     */
    runAsRootUser?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsContainer
     */
    runningStatus?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsContainer
     */
    snapshotCoverage?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsContainer
     */
    unidentified?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainer
     */
    volumeMounts?: string;
}

/**
 * Check if a given object implements the ModelsContainer interface.
 */
export function instanceOfModelsContainer(value: object): value is ModelsContainer {
    if (!('cid' in value) || value['cid'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function ModelsContainerFromJSON(json: any): ModelsContainer {
    return ModelsContainerFromJSONTyped(json, false);
}

export function ModelsContainerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsContainer {
    if (json == null) {
        return json;
    }
    return {
        
        'agents': json['agents'] == null ? undefined : json['agents'],
        'allowPrivilegeEscalation': json['allow_privilege_escalation'] == null ? undefined : json['allow_privilege_escalation'],
        'cid': json['cid'],
        'cloud': json['cloud'] == null ? undefined : json['cloud'],
        'cloudAccountId': json['cloud_account_id'] == null ? undefined : json['cloud_account_id'],
        'cloudRegion': json['cloud_region'] == null ? undefined : json['cloud_region'],
        'clusterId': json['cluster_id'] == null ? undefined : json['cluster_id'],
        'clusterName': json['cluster_name'] == null ? undefined : json['cluster_name'],
        'configLabels': json['config_labels'] == null ? undefined : json['config_labels'],
        'configUser': json['config_user'] == null ? undefined : json['config_user'],
        'containerImageId': json['container_image_id'] == null ? undefined : json['container_image_id'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'cveIds': json['cve_ids'] == null ? undefined : json['cve_ids'],
        'firstSeen': json['first_seen'] == null ? undefined : json['first_seen'],
        'hostConfigDevices': json['host_config_devices'] == null ? undefined : json['host_config_devices'],
        'id': json['id'],
        'imageApplicationPackageCount': json['image_application_package_count'] == null ? undefined : json['image_application_package_count'],
        'imageAssessedAt': json['image_assessed_at'] == null ? undefined : json['image_assessed_at'],
        'imageDetectionCount': json['image_detection_count'] == null ? undefined : json['image_detection_count'],
        'imageDetectionIdList': json['image_detection_id_list'] == null ? undefined : json['image_detection_id_list'],
        'imageDetectionNameList': json['image_detection_name_list'] == null ? undefined : json['image_detection_name_list'],
        'imageDetectionSeverityByType': json['image_detection_severity_by_type'] == null ? undefined : json['image_detection_severity_by_type'],
        'imageDigest': json['image_digest'] == null ? undefined : json['image_digest'],
        'imageHasBeenAssessed': json['image_has_been_assessed'] == null ? undefined : json['image_has_been_assessed'],
        'imageHighestSeverityVulnerability': json['image_highest_severity_vulnerability'] == null ? undefined : json['image_highest_severity_vulnerability'],
        'imageId': json['image_id'] == null ? undefined : json['image_id'],
        'imagePackageCount': json['image_package_count'] == null ? undefined : json['image_package_count'],
        'imageRegistry': json['image_registry'] == null ? undefined : json['image_registry'],
        'imageRepo': json['image_repo'] == null ? undefined : json['image_repo'],
        'imageTag': json['image_tag'] == null ? undefined : json['image_tag'],
        'imageVulnerabilityCount': json['image_vulnerability_count'] == null ? undefined : json['image_vulnerability_count'],
        'imageVulnerabilitySeverityByType': json['image_vulnerability_severity_by_type'] == null ? undefined : json['image_vulnerability_severity_by_type'],
        'insecureMountSource': json['insecure_mount_source'] == null ? undefined : json['insecure_mount_source'],
        'insecureMountType': json['insecure_mount_type'] == null ? undefined : json['insecure_mount_type'],
        'insecurePropagationMode': json['insecure_propagation_mode'] == null ? undefined : json['insecure_propagation_mode'],
        'interactiveMode': json['interactive_mode'] == null ? undefined : json['interactive_mode'],
        'ipv4': json['ipv4'] == null ? undefined : json['ipv4'],
        'ipv6': json['ipv6'] == null ? undefined : json['ipv6'],
        'kpaCoverage': json['kpa_coverage'] == null ? undefined : json['kpa_coverage'],
        'labels': json['labels'] == null ? undefined : json['labels'],
        'labelsList': json['labels_list'] == null ? undefined : json['labels_list'],
        'lastSeen': json['last_seen'] == null ? undefined : json['last_seen'],
        'linuxSensorAid': json['linux_sensor_aid'] == null ? undefined : json['linux_sensor_aid'],
        'linuxSensorConfigBuild': json['linux_sensor_config_build'] == null ? undefined : json['linux_sensor_config_build'],
        'linuxSensorCoverage': json['linux_sensor_coverage'] == null ? undefined : json['linux_sensor_coverage'],
        'lumosSensorAid': json['lumos_sensor_aid'] == null ? undefined : json['lumos_sensor_aid'],
        'lumosSensorConfigBuild': json['lumos_sensor_config_build'] == null ? undefined : json['lumos_sensor_config_build'],
        'lumosSensorCoverage': json['lumos_sensor_coverage'] == null ? undefined : json['lumos_sensor_coverage'],
        'name': json['name'] == null ? undefined : json['name'],
        'namespace': json['namespace'] == null ? undefined : json['namespace'],
        'nodeId': json['node_id'] == null ? undefined : json['node_id'],
        'nodeName': json['node_name'] == null ? undefined : json['node_name'],
        'podId': json['pod_id'] == null ? undefined : json['pod_id'],
        'podName': json['pod_name'] == null ? undefined : json['pod_name'],
        'portList': json['port_list'] == null ? undefined : json['port_list'],
        'privileged': json['privileged'] == null ? undefined : json['privileged'],
        'rootWriteAccess': json['root_write_access'] == null ? undefined : json['root_write_access'],
        'rpd': json['rpd'] == null ? undefined : json['rpd'],
        'runAsRootGroup': json['run_as_root_group'] == null ? undefined : json['run_as_root_group'],
        'runAsRootUser': json['run_as_root_user'] == null ? undefined : json['run_as_root_user'],
        'runningStatus': json['running_status'] == null ? undefined : json['running_status'],
        'snapshotCoverage': json['snapshot_coverage'] == null ? undefined : json['snapshot_coverage'],
        'unidentified': json['unidentified'] == null ? undefined : json['unidentified'],
        'volumeMounts': json['volume_mounts'] == null ? undefined : json['volume_mounts'],
    };
}

export function ModelsContainerToJSON(value?: ModelsContainer | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'agents': value['agents'],
        'allow_privilege_escalation': value['allowPrivilegeEscalation'],
        'cid': value['cid'],
        'cloud': value['cloud'],
        'cloud_account_id': value['cloudAccountId'],
        'cloud_region': value['cloudRegion'],
        'cluster_id': value['clusterId'],
        'cluster_name': value['clusterName'],
        'config_labels': value['configLabels'],
        'config_user': value['configUser'],
        'container_image_id': value['containerImageId'],
        'created_at': value['createdAt'],
        'cve_ids': value['cveIds'],
        'first_seen': value['firstSeen'],
        'host_config_devices': value['hostConfigDevices'],
        'id': value['id'],
        'image_application_package_count': value['imageApplicationPackageCount'],
        'image_assessed_at': value['imageAssessedAt'],
        'image_detection_count': value['imageDetectionCount'],
        'image_detection_id_list': value['imageDetectionIdList'],
        'image_detection_name_list': value['imageDetectionNameList'],
        'image_detection_severity_by_type': value['imageDetectionSeverityByType'],
        'image_digest': value['imageDigest'],
        'image_has_been_assessed': value['imageHasBeenAssessed'],
        'image_highest_severity_vulnerability': value['imageHighestSeverityVulnerability'],
        'image_id': value['imageId'],
        'image_package_count': value['imagePackageCount'],
        'image_registry': value['imageRegistry'],
        'image_repo': value['imageRepo'],
        'image_tag': value['imageTag'],
        'image_vulnerability_count': value['imageVulnerabilityCount'],
        'image_vulnerability_severity_by_type': value['imageVulnerabilitySeverityByType'],
        'insecure_mount_source': value['insecureMountSource'],
        'insecure_mount_type': value['insecureMountType'],
        'insecure_propagation_mode': value['insecurePropagationMode'],
        'interactive_mode': value['interactiveMode'],
        'ipv4': value['ipv4'],
        'ipv6': value['ipv6'],
        'kpa_coverage': value['kpaCoverage'],
        'labels': value['labels'],
        'labels_list': value['labelsList'],
        'last_seen': value['lastSeen'],
        'linux_sensor_aid': value['linuxSensorAid'],
        'linux_sensor_config_build': value['linuxSensorConfigBuild'],
        'linux_sensor_coverage': value['linuxSensorCoverage'],
        'lumos_sensor_aid': value['lumosSensorAid'],
        'lumos_sensor_config_build': value['lumosSensorConfigBuild'],
        'lumos_sensor_coverage': value['lumosSensorCoverage'],
        'name': value['name'],
        'namespace': value['namespace'],
        'node_id': value['nodeId'],
        'node_name': value['nodeName'],
        'pod_id': value['podId'],
        'pod_name': value['podName'],
        'port_list': value['portList'],
        'privileged': value['privileged'],
        'root_write_access': value['rootWriteAccess'],
        'rpd': value['rpd'],
        'run_as_root_group': value['runAsRootGroup'],
        'run_as_root_user': value['runAsRootUser'],
        'running_status': value['runningStatus'],
        'snapshot_coverage': value['snapshotCoverage'],
        'unidentified': value['unidentified'],
        'volume_mounts': value['volumeMounts'],
    };
}

