/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ModelsAPIPackageCombinedV2
 */
export interface ModelsAPIPackageCombinedV2 {
    /**
     *
     * @type {boolean}
     * @memberof ModelsAPIPackageCombinedV2
     */
    aiRelated: boolean;
    /**
     *
     * @type {number}
     * @memberof ModelsAPIPackageCombinedV2
     */
    allImages: number;
    /**
     *
     * @type {string}
     * @memberof ModelsAPIPackageCombinedV2
     */
    cid: string;
    /**
     *
     * @type {string}
     * @memberof ModelsAPIPackageCombinedV2
     */
    cveid: string;
    /**
     *
     * @type {Array<string>}
     * @memberof ModelsAPIPackageCombinedV2
     */
    fixResolution: Array<string>;
    /**
     *
     * @type {string}
     * @memberof ModelsAPIPackageCombinedV2
     */
    license: string;
    /**
     *
     * @type {string}
     * @memberof ModelsAPIPackageCombinedV2
     */
    packageNameVersion: string;
    /**
     *
     * @type {number}
     * @memberof ModelsAPIPackageCombinedV2
     */
    runningImages: number;
    /**
     *
     * @type {string}
     * @memberof ModelsAPIPackageCombinedV2
     */
    severity: string;
    /**
     *
     * @type {string}
     * @memberof ModelsAPIPackageCombinedV2
     */
    type: string;
    /**
     *
     * @type {string}
     * @memberof ModelsAPIPackageCombinedV2
     */
    vulnerabilityDescription: string;
}

/**
 * Check if a given object implements the ModelsAPIPackageCombinedV2 interface.
 */
export function instanceOfModelsAPIPackageCombinedV2(value: object): value is ModelsAPIPackageCombinedV2 {
    if (!("aiRelated" in value) || value["aiRelated"] === undefined) return false;
    if (!("allImages" in value) || value["allImages"] === undefined) return false;
    if (!("cid" in value) || value["cid"] === undefined) return false;
    if (!("cveid" in value) || value["cveid"] === undefined) return false;
    if (!("fixResolution" in value) || value["fixResolution"] === undefined) return false;
    if (!("license" in value) || value["license"] === undefined) return false;
    if (!("packageNameVersion" in value) || value["packageNameVersion"] === undefined) return false;
    if (!("runningImages" in value) || value["runningImages"] === undefined) return false;
    if (!("severity" in value) || value["severity"] === undefined) return false;
    if (!("type" in value) || value["type"] === undefined) return false;
    if (!("vulnerabilityDescription" in value) || value["vulnerabilityDescription"] === undefined) return false;
    return true;
}

export function ModelsAPIPackageCombinedV2FromJSON(json: any): ModelsAPIPackageCombinedV2 {
    return ModelsAPIPackageCombinedV2FromJSONTyped(json, false);
}

export function ModelsAPIPackageCombinedV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsAPIPackageCombinedV2 {
    if (json == null) {
        return json;
    }
    return {
        aiRelated: json["ai_related"],
        allImages: json["all_images"],
        cid: json["cid"],
        cveid: json["cveid"],
        fixResolution: json["fix_resolution"],
        license: json["license"],
        packageNameVersion: json["package_name_version"],
        runningImages: json["running_images"],
        severity: json["severity"],
        type: json["type"],
        vulnerabilityDescription: json["vulnerability_description"],
    };
}

export function ModelsAPIPackageCombinedV2ToJSON(value?: ModelsAPIPackageCombinedV2 | null): any {
    if (value == null) {
        return value;
    }
    return {
        ai_related: value["aiRelated"],
        all_images: value["allImages"],
        cid: value["cid"],
        cveid: value["cveid"],
        fix_resolution: value["fixResolution"],
        license: value["license"],
        package_name_version: value["packageNameVersion"],
        running_images: value["runningImages"],
        severity: value["severity"],
        type: value["type"],
        vulnerability_description: value["vulnerabilityDescription"],
    };
}
