/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ModelsHEStringFileInfoType } from "./ModelsHEStringFileInfoType";
import { ModelsHEStringFileInfoTypeFromJSON, ModelsHEStringFileInfoTypeFromJSONTyped, ModelsHEStringFileInfoTypeToJSON } from "./ModelsHEStringFileInfoType";
import type { ModelsInventoryType } from "./ModelsInventoryType";
import { ModelsInventoryTypeFromJSON, ModelsInventoryTypeFromJSONTyped, ModelsInventoryTypeToJSON } from "./ModelsInventoryType";
import type { ModelsScanRequestType } from "./ModelsScanRequestType";
import { ModelsScanRequestTypeFromJSON, ModelsScanRequestTypeFromJSONTyped, ModelsScanRequestTypeToJSON } from "./ModelsScanRequestType";

/**
 *
 * @export
 * @interface ModelsInventoryScanRequestType
 */
export interface ModelsInventoryScanRequestType {
    /**
     *
     * @type {string}
     * @memberof ModelsInventoryScanRequestType
     */
    agentUuid: string;
    /**
     *
     * @type {string}
     * @memberof ModelsInventoryScanRequestType
     */
    agentVersion: string;
    /**
     *
     * @type {string}
     * @memberof ModelsInventoryScanRequestType
     */
    agentVersionHash: string;
    /**
     *
     * @type {string}
     * @memberof ModelsInventoryScanRequestType
     */
    clusterId: string;
    /**
     *
     * @type {string}
     * @memberof ModelsInventoryScanRequestType
     */
    clusterName: string;
    /**
     *
     * @type {string}
     * @memberof ModelsInventoryScanRequestType
     */
    containerId?: string;
    /**
     *
     * @type {boolean}
     * @memberof ModelsInventoryScanRequestType
     */
    ephemeralScan?: boolean;
    /**
     *
     * @type {string}
     * @memberof ModelsInventoryScanRequestType
     */
    helmVersion: string;
    /**
     *
     * @type {Array<ModelsHEStringFileInfoType>}
     * @memberof ModelsInventoryScanRequestType
     */
    highEntropyStrings?: Array<ModelsHEStringFileInfoType>;
    /**
     *
     * @type {string}
     * @memberof ModelsInventoryScanRequestType
     */
    hostIp: string;
    /**
     *
     * @type {string}
     * @memberof ModelsInventoryScanRequestType
     */
    hostName: string;
    /**
     *
     * @type {ModelsInventoryType}
     * @memberof ModelsInventoryScanRequestType
     */
    inventory: ModelsInventoryType;
    /**
     *
     * @type {string}
     * @memberof ModelsInventoryScanRequestType
     */
    originalImageName: string;
    /**
     *
     * @type {string}
     * @memberof ModelsInventoryScanRequestType
     */
    podId?: string;
    /**
     *
     * @type {string}
     * @memberof ModelsInventoryScanRequestType
     */
    podName?: string;
    /**
     *
     * @type {string}
     * @memberof ModelsInventoryScanRequestType
     */
    podNamespace?: string;
    /**
     *
     * @type {string}
     * @memberof ModelsInventoryScanRequestType
     */
    runmode: string;
    /**
     *
     * @type {string}
     * @memberof ModelsInventoryScanRequestType
     */
    runtimeType?: string;
    /**
     *
     * @type {ModelsScanRequestType}
     * @memberof ModelsInventoryScanRequestType
     */
    scanRequest: ModelsScanRequestType;
}

/**
 * Check if a given object implements the ModelsInventoryScanRequestType interface.
 */
export function instanceOfModelsInventoryScanRequestType(value: object): value is ModelsInventoryScanRequestType {
    if (!("agentUuid" in value) || value["agentUuid"] === undefined) return false;
    if (!("agentVersion" in value) || value["agentVersion"] === undefined) return false;
    if (!("agentVersionHash" in value) || value["agentVersionHash"] === undefined) return false;
    if (!("clusterId" in value) || value["clusterId"] === undefined) return false;
    if (!("clusterName" in value) || value["clusterName"] === undefined) return false;
    if (!("helmVersion" in value) || value["helmVersion"] === undefined) return false;
    if (!("hostIp" in value) || value["hostIp"] === undefined) return false;
    if (!("hostName" in value) || value["hostName"] === undefined) return false;
    if (!("inventory" in value) || value["inventory"] === undefined) return false;
    if (!("originalImageName" in value) || value["originalImageName"] === undefined) return false;
    if (!("runmode" in value) || value["runmode"] === undefined) return false;
    if (!("scanRequest" in value) || value["scanRequest"] === undefined) return false;
    return true;
}

export function ModelsInventoryScanRequestTypeFromJSON(json: any): ModelsInventoryScanRequestType {
    return ModelsInventoryScanRequestTypeFromJSONTyped(json, false);
}

export function ModelsInventoryScanRequestTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsInventoryScanRequestType {
    if (json == null) {
        return json;
    }
    return {
        agentUuid: json["agent_uuid"],
        agentVersion: json["agent_version"],
        agentVersionHash: json["agent_version_hash"],
        clusterId: json["cluster_id"],
        clusterName: json["cluster_name"],
        containerId: json["container_id"] == null ? undefined : json["container_id"],
        ephemeralScan: json["ephemeral_scan"] == null ? undefined : json["ephemeral_scan"],
        helmVersion: json["helm_version"],
        highEntropyStrings: json["high_entropy_strings"] == null ? undefined : (json["high_entropy_strings"] as Array<any>).map(ModelsHEStringFileInfoTypeFromJSON),
        hostIp: json["host_ip"],
        hostName: json["host_name"],
        inventory: ModelsInventoryTypeFromJSON(json["inventory"]),
        originalImageName: json["original_image_name"],
        podId: json["pod_id"] == null ? undefined : json["pod_id"],
        podName: json["pod_name"] == null ? undefined : json["pod_name"],
        podNamespace: json["pod_namespace"] == null ? undefined : json["pod_namespace"],
        runmode: json["runmode"],
        runtimeType: json["runtime_type"] == null ? undefined : json["runtime_type"],
        scanRequest: ModelsScanRequestTypeFromJSON(json["scan_request"]),
    };
}

export function ModelsInventoryScanRequestTypeToJSON(value?: ModelsInventoryScanRequestType | null): any {
    if (value == null) {
        return value;
    }
    return {
        agent_uuid: value["agentUuid"],
        agent_version: value["agentVersion"],
        agent_version_hash: value["agentVersionHash"],
        cluster_id: value["clusterId"],
        cluster_name: value["clusterName"],
        container_id: value["containerId"],
        ephemeral_scan: value["ephemeralScan"],
        helm_version: value["helmVersion"],
        high_entropy_strings: value["highEntropyStrings"] == null ? undefined : (value["highEntropyStrings"] as Array<any>).map(ModelsHEStringFileInfoTypeToJSON),
        host_ip: value["hostIp"],
        host_name: value["hostName"],
        inventory: ModelsInventoryTypeToJSON(value["inventory"]),
        original_image_name: value["originalImageName"],
        pod_id: value["podId"],
        pod_name: value["podName"],
        pod_namespace: value["podNamespace"],
        runmode: value["runmode"],
        runtime_type: value["runtimeType"],
        scan_request: ModelsScanRequestTypeToJSON(value["scanRequest"]),
    };
}
