/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ModelsComplianceExportGroupedByRulesReport
 */
export interface ModelsComplianceExportGroupedByRulesReport {
    /**
     *
     * @type {string}
     * @memberof ModelsComplianceExportGroupedByRulesReport
     */
    assetType: string;
    /**
     *
     * @type {string}
     * @memberof ModelsComplianceExportGroupedByRulesReport
     */
    authority: string;
    /**
     *
     * @type {number}
     * @memberof ModelsComplianceExportGroupedByRulesReport
     */
    clusters: number;
    /**
     *
     * @type {string}
     * @memberof ModelsComplianceExportGroupedByRulesReport
     */
    clustersList: string;
    /**
     *
     * @type {number}
     * @memberof ModelsComplianceExportGroupedByRulesReport
     */
    failedContainers: number;
    /**
     *
     * @type {number}
     * @memberof ModelsComplianceExportGroupedByRulesReport
     */
    failedImages: number;
    /**
     *
     * @type {string}
     * @memberof ModelsComplianceExportGroupedByRulesReport
     */
    name: string;
    /**
     *
     * @type {number}
     * @memberof ModelsComplianceExportGroupedByRulesReport
     */
    passedContainers: number;
    /**
     *
     * @type {number}
     * @memberof ModelsComplianceExportGroupedByRulesReport
     */
    passedImages: number;
    /**
     *
     * @type {string}
     * @memberof ModelsComplianceExportGroupedByRulesReport
     */
    ruleId: string;
    /**
     *
     * @type {number}
     * @memberof ModelsComplianceExportGroupedByRulesReport
     */
    severity: number;
    /**
     *
     * @type {number}
     * @memberof ModelsComplianceExportGroupedByRulesReport
     */
    totalContainers: number;
    /**
     *
     * @type {number}
     * @memberof ModelsComplianceExportGroupedByRulesReport
     */
    totalImages: number;
}

/**
 * Check if a given object implements the ModelsComplianceExportGroupedByRulesReport interface.
 */
export function instanceOfModelsComplianceExportGroupedByRulesReport(value: object): value is ModelsComplianceExportGroupedByRulesReport {
    if (!("assetType" in value) || value["assetType"] === undefined) return false;
    if (!("authority" in value) || value["authority"] === undefined) return false;
    if (!("clusters" in value) || value["clusters"] === undefined) return false;
    if (!("clustersList" in value) || value["clustersList"] === undefined) return false;
    if (!("failedContainers" in value) || value["failedContainers"] === undefined) return false;
    if (!("failedImages" in value) || value["failedImages"] === undefined) return false;
    if (!("name" in value) || value["name"] === undefined) return false;
    if (!("passedContainers" in value) || value["passedContainers"] === undefined) return false;
    if (!("passedImages" in value) || value["passedImages"] === undefined) return false;
    if (!("ruleId" in value) || value["ruleId"] === undefined) return false;
    if (!("severity" in value) || value["severity"] === undefined) return false;
    if (!("totalContainers" in value) || value["totalContainers"] === undefined) return false;
    if (!("totalImages" in value) || value["totalImages"] === undefined) return false;
    return true;
}

export function ModelsComplianceExportGroupedByRulesReportFromJSON(json: any): ModelsComplianceExportGroupedByRulesReport {
    return ModelsComplianceExportGroupedByRulesReportFromJSONTyped(json, false);
}

export function ModelsComplianceExportGroupedByRulesReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsComplianceExportGroupedByRulesReport {
    if (json == null) {
        return json;
    }
    return {
        assetType: json["asset_type"],
        authority: json["authority"],
        clusters: json["clusters"],
        clustersList: json["clusters_list"],
        failedContainers: json["failed_containers"],
        failedImages: json["failed_images"],
        name: json["name"],
        passedContainers: json["passed_containers"],
        passedImages: json["passed_images"],
        ruleId: json["rule_id"],
        severity: json["severity"],
        totalContainers: json["total_containers"],
        totalImages: json["total_images"],
    };
}

export function ModelsComplianceExportGroupedByRulesReportToJSON(value?: ModelsComplianceExportGroupedByRulesReport | null): any {
    if (value == null) {
        return value;
    }
    return {
        asset_type: value["assetType"],
        authority: value["authority"],
        clusters: value["clusters"],
        clusters_list: value["clustersList"],
        failed_containers: value["failedContainers"],
        failed_images: value["failedImages"],
        name: value["name"],
        passed_containers: value["passedContainers"],
        passed_images: value["passedImages"],
        rule_id: value["ruleId"],
        severity: value["severity"],
        total_containers: value["totalContainers"],
        total_images: value["totalImages"],
    };
}
