/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ModelsHEStringInfoType
 */
export interface ModelsHEStringInfoType {
    /**
     *
     * @type {string}
     * @memberof ModelsHEStringInfoType
     */
    hash?: string;
    /**
     *
     * @type {number}
     * @memberof ModelsHEStringInfoType
     */
    line: number;
    /**
     *
     * @type {string}
     * @memberof ModelsHEStringInfoType
     */
    name?: string;
    /**
     *
     * @type {string}
     * @memberof ModelsHEStringInfoType
     */
    regexName: string;
    /**
     *
     * @type {string}
     * @memberof ModelsHEStringInfoType
     */
    string?: string;
}

/**
 * Check if a given object implements the ModelsHEStringInfoType interface.
 */
export function instanceOfModelsHEStringInfoType(value: object): value is ModelsHEStringInfoType {
    if (!("line" in value) || value["line"] === undefined) return false;
    if (!("regexName" in value) || value["regexName"] === undefined) return false;
    return true;
}

export function ModelsHEStringInfoTypeFromJSON(json: any): ModelsHEStringInfoType {
    return ModelsHEStringInfoTypeFromJSONTyped(json, false);
}

export function ModelsHEStringInfoTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsHEStringInfoType {
    if (json == null) {
        return json;
    }
    return {
        hash: json["Hash"] == null ? undefined : json["Hash"],
        line: json["Line"],
        name: json["Name"] == null ? undefined : json["Name"],
        regexName: json["RegexName"],
        string: json["String"] == null ? undefined : json["String"],
    };
}

export function ModelsHEStringInfoTypeToJSON(value?: ModelsHEStringInfoType | null): any {
    if (value == null) {
        return value;
    }
    return {
        Hash: value["hash"],
        Line: value["line"],
        Name: value["name"],
        RegexName: value["regexName"],
        String: value["string"],
    };
}
