/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ModelsJobMetaData } from "./ModelsJobMetaData";
import { ModelsJobMetaDataFromJSON, ModelsJobMetaDataFromJSONTyped, ModelsJobMetaDataToJSON } from "./ModelsJobMetaData";
import type { ModelsOSInfoType } from "./ModelsOSInfoType";
import { ModelsOSInfoTypeFromJSON, ModelsOSInfoTypeFromJSONTyped, ModelsOSInfoTypeToJSON } from "./ModelsOSInfoType";
import type { ModelsPackageVulnerabilityType } from "./ModelsPackageVulnerabilityType";
import { ModelsPackageVulnerabilityTypeFromJSON, ModelsPackageVulnerabilityTypeFromJSONTyped, ModelsPackageVulnerabilityTypeToJSON } from "./ModelsPackageVulnerabilityType";
import type { ModelsApplicationPackageInfoType } from "./ModelsApplicationPackageInfoType";
import { ModelsApplicationPackageInfoTypeFromJSON, ModelsApplicationPackageInfoTypeFromJSONTyped, ModelsApplicationPackageInfoTypeToJSON } from "./ModelsApplicationPackageInfoType";
import type { ModelsDetectionEngineInfoType } from "./ModelsDetectionEngineInfoType";
import { ModelsDetectionEngineInfoTypeFromJSON, ModelsDetectionEngineInfoTypeFromJSONTyped, ModelsDetectionEngineInfoTypeToJSON } from "./ModelsDetectionEngineInfoType";
import type { ModelsDetectionInfoType } from "./ModelsDetectionInfoType";
import { ModelsDetectionInfoTypeFromJSON, ModelsDetectionInfoTypeFromJSONTyped, ModelsDetectionInfoTypeToJSON } from "./ModelsDetectionInfoType";
import type { ModelsVulnerabilitiesType } from "./ModelsVulnerabilitiesType";
import { ModelsVulnerabilitiesTypeFromJSON, ModelsVulnerabilitiesTypeFromJSONTyped, ModelsVulnerabilitiesTypeToJSON } from "./ModelsVulnerabilitiesType";
import type { ModelsScanResults } from "./ModelsScanResults";
import { ModelsScanResultsFromJSON, ModelsScanResultsFromJSONTyped, ModelsScanResultsToJSON } from "./ModelsScanResults";

/**
 *
 * @export
 * @interface ModelsScanReportType
 */
export interface ModelsScanReportType {
    /**
     *
     * @type {Array<ModelsApplicationPackageInfoType>}
     * @memberof ModelsScanReportType
     */
    applicationPackages?: Array<ModelsApplicationPackageInfoType>;
    /**
     *
     * @type {ModelsDetectionEngineInfoType}
     * @memberof ModelsScanReportType
     */
    detectionEngineInfo: ModelsDetectionEngineInfoType;
    /**
     *
     * @type {Array<ModelsDetectionInfoType>}
     * @memberof ModelsScanReportType
     */
    detections: Array<ModelsDetectionInfoType>;
    /**
     *
     * @type {Array<ModelsPackageVulnerabilityType>}
     * @memberof ModelsScanReportType
     */
    vulnerabilities: Array<ModelsPackageVulnerabilityType>;
    /**
     *
     * @type {ModelsVulnerabilitiesType}
     * @memberof ModelsScanReportType
     */
    vulnerabilitiesTruncated?: ModelsVulnerabilitiesType;
    /**
     *
     * @type {ModelsJobMetaData}
     * @memberof ModelsScanReportType
     */
    jobMetadata: ModelsJobMetaData;
    /**
     *
     * @type {ModelsOSInfoType}
     * @memberof ModelsScanReportType
     */
    osInfo: ModelsOSInfoType;
    /**
     *
     * @type {ModelsScanResults}
     * @memberof ModelsScanReportType
     */
    results: ModelsScanResults;
}

/**
 * Check if a given object implements the ModelsScanReportType interface.
 */
export function instanceOfModelsScanReportType(value: object): value is ModelsScanReportType {
    if (!("detectionEngineInfo" in value) || value["detectionEngineInfo"] === undefined) return false;
    if (!("detections" in value) || value["detections"] === undefined) return false;
    if (!("vulnerabilities" in value) || value["vulnerabilities"] === undefined) return false;
    if (!("jobMetadata" in value) || value["jobMetadata"] === undefined) return false;
    if (!("osInfo" in value) || value["osInfo"] === undefined) return false;
    if (!("results" in value) || value["results"] === undefined) return false;
    return true;
}

export function ModelsScanReportTypeFromJSON(json: any): ModelsScanReportType {
    return ModelsScanReportTypeFromJSONTyped(json, false);
}

export function ModelsScanReportTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsScanReportType {
    if (json == null) {
        return json;
    }
    return {
        applicationPackages: json["ApplicationPackages"] == null ? undefined : (json["ApplicationPackages"] as Array<any>).map(ModelsApplicationPackageInfoTypeFromJSON),
        detectionEngineInfo: ModelsDetectionEngineInfoTypeFromJSON(json["DetectionEngineInfo"]),
        detections: (json["Detections"] as Array<any>).map(ModelsDetectionInfoTypeFromJSON),
        vulnerabilities: (json["Vulnerabilities"] as Array<any>).map(ModelsPackageVulnerabilityTypeFromJSON),
        vulnerabilitiesTruncated: json["VulnerabilitiesTruncated"] == null ? undefined : ModelsVulnerabilitiesTypeFromJSON(json["VulnerabilitiesTruncated"]),
        jobMetadata: ModelsJobMetaDataFromJSON(json["job_metadata"]),
        osInfo: ModelsOSInfoTypeFromJSON(json["os_info"]),
        results: ModelsScanResultsFromJSON(json["results"]),
    };
}

export function ModelsScanReportTypeToJSON(value?: ModelsScanReportType | null): any {
    if (value == null) {
        return value;
    }
    return {
        ApplicationPackages: value["applicationPackages"] == null ? undefined : (value["applicationPackages"] as Array<any>).map(ModelsApplicationPackageInfoTypeToJSON),
        DetectionEngineInfo: ModelsDetectionEngineInfoTypeToJSON(value["detectionEngineInfo"]),
        Detections: (value["detections"] as Array<any>).map(ModelsDetectionInfoTypeToJSON),
        Vulnerabilities: (value["vulnerabilities"] as Array<any>).map(ModelsPackageVulnerabilityTypeToJSON),
        VulnerabilitiesTruncated: ModelsVulnerabilitiesTypeToJSON(value["vulnerabilitiesTruncated"]),
        job_metadata: ModelsJobMetaDataToJSON(value["jobMetadata"]),
        os_info: ModelsOSInfoTypeToJSON(value["osInfo"]),
        results: ModelsScanResultsToJSON(value["results"]),
    };
}
