/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ModelsClusterInfo } from './ModelsClusterInfo';
import {
    ModelsClusterInfoFromJSON,
    ModelsClusterInfoFromJSONTyped,
    ModelsClusterInfoToJSON,
} from './ModelsClusterInfo';

/**
 * 
 * @export
 * @interface ModelsContainerImage
 */
export interface ModelsContainerImage {
    /**
     * 
     * @type {string}
     * @memberof ModelsContainerImage
     */
    cid: string;
    /**
     * 
     * @type {Array<ModelsClusterInfo>}
     * @memberof ModelsContainerImage
     */
    clusterInfo: Array<ModelsClusterInfo>;
    /**
     * 
     * @type {number}
     * @memberof ModelsContainerImage
     */
    containerCount: number;
    /**
     * 
     * @type {{ [key: string]: boolean; }}
     * @memberof ModelsContainerImage
     */
    containersRunningStatus: { [key: string]: boolean; };
    /**
     * 
     * @type {Array<string>}
     * @memberof ModelsContainerImage
     */
    hosts: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainerImage
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsContainerImage
     */
    imageDetectionCount: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainerImage
     */
    imageDigest: string;
    /**
     * 
     * @type {boolean}
     * @memberof ModelsContainerImage
     */
    imageHasBeenAssessed: boolean;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainerImage
     */
    imageId: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainerImage
     */
    imageName: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainerImage
     */
    imageRegistry: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainerImage
     */
    imageRepository: string;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainerImage
     */
    imageTag: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsContainerImage
     */
    imageVulnerabilityCount: number;
    /**
     * 
     * @type {string}
     * @memberof ModelsContainerImage
     */
    lastSeen: string;
    /**
     * 
     * @type {number}
     * @memberof ModelsContainerImage
     */
    runningContainerCount: number;
}

/**
 * Check if a given object implements the ModelsContainerImage interface.
 */
export function instanceOfModelsContainerImage(value: object): value is ModelsContainerImage {
    if (!('cid' in value) || value['cid'] === undefined) return false;
    if (!('clusterInfo' in value) || value['clusterInfo'] === undefined) return false;
    if (!('containerCount' in value) || value['containerCount'] === undefined) return false;
    if (!('containersRunningStatus' in value) || value['containersRunningStatus'] === undefined) return false;
    if (!('hosts' in value) || value['hosts'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('imageDetectionCount' in value) || value['imageDetectionCount'] === undefined) return false;
    if (!('imageDigest' in value) || value['imageDigest'] === undefined) return false;
    if (!('imageHasBeenAssessed' in value) || value['imageHasBeenAssessed'] === undefined) return false;
    if (!('imageId' in value) || value['imageId'] === undefined) return false;
    if (!('imageName' in value) || value['imageName'] === undefined) return false;
    if (!('imageRegistry' in value) || value['imageRegistry'] === undefined) return false;
    if (!('imageRepository' in value) || value['imageRepository'] === undefined) return false;
    if (!('imageTag' in value) || value['imageTag'] === undefined) return false;
    if (!('imageVulnerabilityCount' in value) || value['imageVulnerabilityCount'] === undefined) return false;
    if (!('lastSeen' in value) || value['lastSeen'] === undefined) return false;
    if (!('runningContainerCount' in value) || value['runningContainerCount'] === undefined) return false;
    return true;
}

export function ModelsContainerImageFromJSON(json: any): ModelsContainerImage {
    return ModelsContainerImageFromJSONTyped(json, false);
}

export function ModelsContainerImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelsContainerImage {
    if (json == null) {
        return json;
    }
    return {
        
        'cid': json['cid'],
        'clusterInfo': ((json['cluster_info'] as Array<any>).map(ModelsClusterInfoFromJSON)),
        'containerCount': json['container_count'],
        'containersRunningStatus': json['containers_running_status'],
        'hosts': json['hosts'],
        'id': json['id'],
        'imageDetectionCount': json['image_detection_count'],
        'imageDigest': json['image_digest'],
        'imageHasBeenAssessed': json['image_has_been_assessed'],
        'imageId': json['image_id'],
        'imageName': json['image_name'],
        'imageRegistry': json['image_registry'],
        'imageRepository': json['image_repository'],
        'imageTag': json['image_tag'],
        'imageVulnerabilityCount': json['image_vulnerability_count'],
        'lastSeen': json['last_seen'],
        'runningContainerCount': json['running_container_count'],
    };
}

export function ModelsContainerImageToJSON(value?: ModelsContainerImage | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'cid': value['cid'],
        'cluster_info': ((value['clusterInfo'] as Array<any>).map(ModelsClusterInfoToJSON)),
        'container_count': value['containerCount'],
        'containers_running_status': value['containersRunningStatus'],
        'hosts': value['hosts'],
        'id': value['id'],
        'image_detection_count': value['imageDetectionCount'],
        'image_digest': value['imageDigest'],
        'image_has_been_assessed': value['imageHasBeenAssessed'],
        'image_id': value['imageId'],
        'image_name': value['imageName'],
        'image_registry': value['imageRegistry'],
        'image_repository': value['imageRepository'],
        'image_tag': value['imageTag'],
        'image_vulnerability_count': value['imageVulnerabilityCount'],
        'last_seen': value['lastSeen'],
        'running_container_count': value['runningContainerCount'],
    };
}

