/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and more information about API endpoints that don\'t yet support OAuth2, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation). To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`. Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RegistrationAWSAccountD4CExtV2
 */
export interface RegistrationAWSAccountD4CExtV2 {
    /**
     *
     * @type {string}
     * @memberof RegistrationAWSAccountD4CExtV2
     */
    accountId: string;
    /**
     *
     * @type {string}
     * @memberof RegistrationAWSAccountD4CExtV2
     */
    accountType?: string;
    /**
     *
     * @type {string}
     * @memberof RegistrationAWSAccountD4CExtV2
     */
    cloudtrailRegion: string;
    /**
     *
     * @type {boolean}
     * @memberof RegistrationAWSAccountD4CExtV2
     */
    isMaster?: boolean;
    /**
     *
     * @type {string}
     * @memberof RegistrationAWSAccountD4CExtV2
     */
    organizationId: string;
}

/**
 * Check if a given object implements the RegistrationAWSAccountD4CExtV2 interface.
 */
export function instanceOfRegistrationAWSAccountD4CExtV2(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "accountId" in value;
    isInstance = isInstance && "cloudtrailRegion" in value;
    isInstance = isInstance && "organizationId" in value;

    return isInstance;
}

export function RegistrationAWSAccountD4CExtV2FromJSON(json: any): RegistrationAWSAccountD4CExtV2 {
    return RegistrationAWSAccountD4CExtV2FromJSONTyped(json, false);
}

export function RegistrationAWSAccountD4CExtV2FromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistrationAWSAccountD4CExtV2 {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        accountId: json["account_id"],
        accountType: !exists(json, "account_type") ? undefined : json["account_type"],
        cloudtrailRegion: json["cloudtrail_region"],
        isMaster: !exists(json, "is_master") ? undefined : json["is_master"],
        organizationId: json["organization_id"],
    };
}

export function RegistrationAWSAccountD4CExtV2ToJSON(value?: RegistrationAWSAccountD4CExtV2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        account_id: value.accountId,
        account_type: value.accountType,
        cloudtrail_region: value.cloudtrailRegion,
        is_master: value.isMaster,
        organization_id: value.organizationId,
    };
}
