/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and more information about API endpoints that don\'t yet support OAuth2, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation). To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`. Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
/**
 *
 * @export
 * @interface RegistrationAzureKeyV1
 */
export interface RegistrationAzureKeyV1 {
    /**
     *
     * @type {string}
     * @memberof RegistrationAzureKeyV1
     */
    clientId: string;
    /**
     *
     * @type {string}
     * @memberof RegistrationAzureKeyV1
     */
    endDate?: string;
    /**
     *
     * @type {string}
     * @memberof RegistrationAzureKeyV1
     */
    publicCertificate?: string;
    /**
     *
     * @type {string}
     * @memberof RegistrationAzureKeyV1
     */
    tenantId: string;
    /**
     *
     * @type {boolean}
     * @memberof RegistrationAzureKeyV1
     */
    valid?: boolean;
}

/**
 * Check if a given object implements the RegistrationAzureKeyV1 interface.
 */
export function instanceOfRegistrationAzureKeyV1(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "clientId" in value;
    isInstance = isInstance && "tenantId" in value;

    return isInstance;
}

export function RegistrationAzureKeyV1FromJSON(json: any): RegistrationAzureKeyV1 {
    return RegistrationAzureKeyV1FromJSONTyped(json, false);
}

export function RegistrationAzureKeyV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistrationAzureKeyV1 {
    if (json === undefined || json === null) {
        return json;
    }
    return {
        clientId: json["client_id"],
        endDate: !exists(json, "end_date") ? undefined : json["end_date"],
        publicCertificate: !exists(json, "public_certificate") ? undefined : json["public_certificate"],
        tenantId: json["tenant_id"],
        valid: !exists(json, "valid") ? undefined : json["valid"],
    };
}

export function RegistrationAzureKeyV1ToJSON(value?: RegistrationAzureKeyV1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        client_id: value.clientId,
        end_date: value.endDate,
        public_certificate: value.publicCertificate,
        tenant_id: value.tenantId,
        valid: value.valid,
    };
}
