/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { ResourcesCompliance } from "./ResourcesCompliance";
import { ResourcesComplianceFromJSON, ResourcesComplianceFromJSONTyped, ResourcesComplianceToJSON } from "./ResourcesCompliance";
import type { ResourcesDetectionCount } from "./ResourcesDetectionCount";
import { ResourcesDetectionCountFromJSON, ResourcesDetectionCountFromJSONTyped, ResourcesDetectionCountToJSON } from "./ResourcesDetectionCount";

/**
 *
 * @export
 * @interface ResourcesDetections
 */
export interface ResourcesDetections {
    /**
     *
     * @type {ResourcesCompliance}
     * @memberof ResourcesDetections
     */
    compliant?: ResourcesCompliance;
    /**
     *
     * @type {string}
     * @memberof ResourcesDetections
     */
    highestSeverity?: string;
    /**
     *
     * @type {number}
     * @memberof ResourcesDetections
     */
    ioaCounts: number;
    /**
     *
     * @type {ResourcesDetectionCount}
     * @memberof ResourcesDetections
     */
    ioaCountsBySeverity?: ResourcesDetectionCount;
    /**
     *
     * @type {number}
     * @memberof ResourcesDetections
     */
    iomCounts: number;
    /**
     *
     * @type {ResourcesDetectionCount}
     * @memberof ResourcesDetections
     */
    iomCountsBySeverity?: ResourcesDetectionCount;
    /**
     *
     * @type {ResourcesCompliance}
     * @memberof ResourcesDetections
     */
    nonCompliant?: ResourcesCompliance;
    /**
     *
     * @type {string}
     * @memberof ResourcesDetections
     */
    resourceUrl: string;
    /**
     *
     * @type {Array<string>}
     * @memberof ResourcesDetections
     */
    severities?: Array<string>;
}

/**
 * Check if a given object implements the ResourcesDetections interface.
 */
export function instanceOfResourcesDetections(value: object): value is ResourcesDetections {
    if (!("ioaCounts" in value) || value["ioaCounts"] === undefined) return false;
    if (!("iomCounts" in value) || value["iomCounts"] === undefined) return false;
    if (!("resourceUrl" in value) || value["resourceUrl"] === undefined) return false;
    return true;
}

export function ResourcesDetectionsFromJSON(json: any): ResourcesDetections {
    return ResourcesDetectionsFromJSONTyped(json, false);
}

export function ResourcesDetectionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourcesDetections {
    if (json == null) {
        return json;
    }
    return {
        compliant: json["compliant"] == null ? undefined : ResourcesComplianceFromJSON(json["compliant"]),
        highestSeverity: json["highest_severity"] == null ? undefined : json["highest_severity"],
        ioaCounts: json["ioa_counts"],
        ioaCountsBySeverity: json["ioa_counts_by_severity"] == null ? undefined : ResourcesDetectionCountFromJSON(json["ioa_counts_by_severity"]),
        iomCounts: json["iom_counts"],
        iomCountsBySeverity: json["iom_counts_by_severity"] == null ? undefined : ResourcesDetectionCountFromJSON(json["iom_counts_by_severity"]),
        nonCompliant: json["non_compliant"] == null ? undefined : ResourcesComplianceFromJSON(json["non_compliant"]),
        resourceUrl: json["resource_url"],
        severities: json["severities"] == null ? undefined : json["severities"],
    };
}

export function ResourcesDetectionsToJSON(value?: ResourcesDetections | null): any {
    if (value == null) {
        return value;
    }
    return {
        compliant: ResourcesComplianceToJSON(value["compliant"]),
        highest_severity: value["highestSeverity"],
        ioa_counts: value["ioaCounts"],
        ioa_counts_by_severity: ResourcesDetectionCountToJSON(value["ioaCountsBySeverity"]),
        iom_counts: value["iomCounts"],
        iom_counts_by_severity: ResourcesDetectionCountToJSON(value["iomCountsBySeverity"]),
        non_compliant: ResourcesComplianceToJSON(value["nonCompliant"]),
        resource_url: value["resourceUrl"],
        severities: value["severities"],
    };
}
