/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { SyntaxInst } from "./SyntaxInst";
import { SyntaxInstFromJSON, SyntaxInstFromJSONTyped, SyntaxInstToJSON } from "./SyntaxInst";

/**
 *
 * @export
 * @interface SyntaxProg
 */
export interface SyntaxProg {
    /**
     *
     * @type {Array<SyntaxInst>}
     * @memberof SyntaxProg
     */
    inst: Array<SyntaxInst>;
    /**
     *
     * @type {number}
     * @memberof SyntaxProg
     */
    numCap: number;
    /**
     *
     * @type {number}
     * @memberof SyntaxProg
     */
    start: number;
}

/**
 * Check if a given object implements the SyntaxProg interface.
 */
export function instanceOfSyntaxProg(value: object): value is SyntaxProg {
    if (!("inst" in value) || value["inst"] === undefined) return false;
    if (!("numCap" in value) || value["numCap"] === undefined) return false;
    if (!("start" in value) || value["start"] === undefined) return false;
    return true;
}

export function SyntaxProgFromJSON(json: any): SyntaxProg {
    return SyntaxProgFromJSONTyped(json, false);
}

export function SyntaxProgFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyntaxProg {
    if (json == null) {
        return json;
    }
    return {
        inst: (json["Inst"] as Array<any>).map(SyntaxInstFromJSON),
        numCap: json["NumCap"],
        start: json["Start"],
    };
}

export function SyntaxProgToJSON(value?: SyntaxProg | null): any {
    if (value == null) {
        return value;
    }
    return {
        Inst: (value["inst"] as Array<any>).map(SyntaxInstToJSON),
        NumCap: value["numCap"],
        Start: value["start"],
    };
}
