/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and examples, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation).     To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`.    Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
import type { TypesUser } from "./TypesUser";
import { TypesUserFromJSON, TypesUserFromJSONTyped, TypesUserToJSON } from "./TypesUser";

/**
 *
 * @export
 * @interface TypesUsersResponse
 */
export interface TypesUsersResponse {
    /**
     *
     * @type {number}
     * @memberof TypesUsersResponse
     */
    totalCount: number;
    /**
     *
     * @type {Array<TypesUser>}
     * @memberof TypesUsersResponse
     */
    users: Array<TypesUser>;
}

/**
 * Check if a given object implements the TypesUsersResponse interface.
 */
export function instanceOfTypesUsersResponse(value: object): value is TypesUsersResponse {
    if (!("totalCount" in value) || value["totalCount"] === undefined) return false;
    if (!("users" in value) || value["users"] === undefined) return false;
    return true;
}

export function TypesUsersResponseFromJSON(json: any): TypesUsersResponse {
    return TypesUsersResponseFromJSONTyped(json, false);
}

export function TypesUsersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesUsersResponse {
    if (json == null) {
        return json;
    }
    return {
        totalCount: json["totalCount"],
        users: (json["users"] as Array<any>).map(TypesUserFromJSON),
    };
}

export function TypesUsersResponseToJSON(value?: TypesUsersResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        totalCount: value["totalCount"],
        users: (value["users"] as Array<any>).map(TypesUserToJSON),
    };
}
