/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and more information about API endpoints that don\'t yet support OAuth2, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation). To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`. Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DomainKillChain
 */
export interface DomainKillChain {
    /**
     * 
     * @type {string}
     * @memberof DomainKillChain
     */
    actionsAndObjectives?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainKillChain
     */
    commandAndControl?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainKillChain
     */
    delivery?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainKillChain
     */
    exploitation?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainKillChain
     */
    installation?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainKillChain
     */
    objectives?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainKillChain
     */
    reconnaissance?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainKillChain
     */
    richTextActionsAndObjectives?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainKillChain
     */
    richTextCommandAndControl?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainKillChain
     */
    richTextDelivery?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainKillChain
     */
    richTextExploitation?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainKillChain
     */
    richTextInstallation?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainKillChain
     */
    richTextObjectives?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainKillChain
     */
    richTextReconnaissance?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainKillChain
     */
    richTextWeaponization?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainKillChain
     */
    weaponization?: string;
}

export function DomainKillChainFromJSON(json: any): DomainKillChain {
    return DomainKillChainFromJSONTyped(json, false);
}

export function DomainKillChainFromJSONTyped(json: any, ignoreDiscriminator: boolean): DomainKillChain {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'actionsAndObjectives': !exists(json, 'actions_and_objectives') ? undefined : json['actions_and_objectives'],
        'commandAndControl': !exists(json, 'command_and_control') ? undefined : json['command_and_control'],
        'delivery': !exists(json, 'delivery') ? undefined : json['delivery'],
        'exploitation': !exists(json, 'exploitation') ? undefined : json['exploitation'],
        'installation': !exists(json, 'installation') ? undefined : json['installation'],
        'objectives': !exists(json, 'objectives') ? undefined : json['objectives'],
        'reconnaissance': !exists(json, 'reconnaissance') ? undefined : json['reconnaissance'],
        'richTextActionsAndObjectives': !exists(json, 'rich_text_actions_and_objectives') ? undefined : json['rich_text_actions_and_objectives'],
        'richTextCommandAndControl': !exists(json, 'rich_text_command_and_control') ? undefined : json['rich_text_command_and_control'],
        'richTextDelivery': !exists(json, 'rich_text_delivery') ? undefined : json['rich_text_delivery'],
        'richTextExploitation': !exists(json, 'rich_text_exploitation') ? undefined : json['rich_text_exploitation'],
        'richTextInstallation': !exists(json, 'rich_text_installation') ? undefined : json['rich_text_installation'],
        'richTextObjectives': !exists(json, 'rich_text_objectives') ? undefined : json['rich_text_objectives'],
        'richTextReconnaissance': !exists(json, 'rich_text_reconnaissance') ? undefined : json['rich_text_reconnaissance'],
        'richTextWeaponization': !exists(json, 'rich_text_weaponization') ? undefined : json['rich_text_weaponization'],
        'weaponization': !exists(json, 'weaponization') ? undefined : json['weaponization'],
    };
}

export function DomainKillChainToJSON(value?: DomainKillChain | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'actions_and_objectives': value.actionsAndObjectives,
        'command_and_control': value.commandAndControl,
        'delivery': value.delivery,
        'exploitation': value.exploitation,
        'installation': value.installation,
        'objectives': value.objectives,
        'reconnaissance': value.reconnaissance,
        'rich_text_actions_and_objectives': value.richTextActionsAndObjectives,
        'rich_text_command_and_control': value.richTextCommandAndControl,
        'rich_text_delivery': value.richTextDelivery,
        'rich_text_exploitation': value.richTextExploitation,
        'rich_text_installation': value.richTextInstallation,
        'rich_text_objectives': value.richTextObjectives,
        'rich_text_reconnaissance': value.richTextReconnaissance,
        'rich_text_weaponization': value.richTextWeaponization,
        'weaponization': value.weaponization,
    };
}

