/* tslint:disable */
/* eslint-disable */
/**
 * CrowdStrike API Specification
 * Use this API specification as a reference for the API endpoints you can use to interact with your Falcon environment. These endpoints support authentication via OAuth2 and interact with detections and network containment. For detailed usage guides and more information about API endpoints that don\'t yet support OAuth2, see our [documentation inside the Falcon console](https://falcon.crowdstrike.com/support/documentation). To use the APIs described below, combine the base URL with the path shown for each API endpoint. For commercial cloud customers, your base URL is `https://api.crowdstrike.com`. Each API endpoint requires authorization via an OAuth2 token. Your first API request should retrieve an OAuth2 token using the `oauth2/token` endpoint, such as `https://api.crowdstrike.com/oauth2/token`. For subsequent requests, include the OAuth2 token in an HTTP authorization header. Tokens expire after 30 minutes, after which you should make a new token request to continue making API requests.
 *
 * The version of the OpenAPI document: rolling
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RequestsDeviceControlPolicyExceptionV1,
    RequestsDeviceControlPolicyExceptionV1FromJSON,
    RequestsDeviceControlPolicyExceptionV1FromJSONTyped,
    RequestsDeviceControlPolicyExceptionV1ToJSON,
} from './RequestsDeviceControlPolicyExceptionV1';

/**
 * 
 * @export
 * @interface RequestsDeviceControlPolicyClassSettingsV1
 */
export interface RequestsDeviceControlPolicyClassSettingsV1 {
    /**
     * Policy action
     * @type {string}
     * @memberof RequestsDeviceControlPolicyClassSettingsV1
     */
    action: RequestsDeviceControlPolicyClassSettingsV1ActionEnum;
    /**
     * Exceptions to the rules of this policy setting
     * @type {Array<RequestsDeviceControlPolicyExceptionV1>}
     * @memberof RequestsDeviceControlPolicyClassSettingsV1
     */
    exceptions: Array<RequestsDeviceControlPolicyExceptionV1>;
    /**
     * USB Class id
     * @type {string}
     * @memberof RequestsDeviceControlPolicyClassSettingsV1
     */
    id: string;
}

/**
* @export
* @enum {string}
*/
export enum RequestsDeviceControlPolicyClassSettingsV1ActionEnum {
    FullAccess = 'FULL_ACCESS',
    FullBlock = 'FULL_BLOCK',
    ReadOnly = 'READ_ONLY'
}

export function RequestsDeviceControlPolicyClassSettingsV1FromJSON(json: any): RequestsDeviceControlPolicyClassSettingsV1 {
    return RequestsDeviceControlPolicyClassSettingsV1FromJSONTyped(json, false);
}

export function RequestsDeviceControlPolicyClassSettingsV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestsDeviceControlPolicyClassSettingsV1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': json['action'],
        'exceptions': ((json['exceptions'] as Array<any>).map(RequestsDeviceControlPolicyExceptionV1FromJSON)),
        'id': json['id'],
    };
}

export function RequestsDeviceControlPolicyClassSettingsV1ToJSON(value?: RequestsDeviceControlPolicyClassSettingsV1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
        'exceptions': ((value.exceptions as Array<any>).map(RequestsDeviceControlPolicyExceptionV1ToJSON)),
        'id': value.id,
    };
}

